input {
  file {
    path => "/var/logs/*.log"
    start_position => "beginning"
  }
}

filter {
  # Parse incoming logs as JSON
  json {
    source => "message"
    target => "hexaind3"
    remove_field => ["message"]
  }

  # Add a field for 6-hour interval
  date {
    match => ["@timestamp", "ISO8601"]
    target => "@timestamp"
  }

  ruby {
    code => "
      interval = 6*3600
      timestamp = event.get('@timestamp').time.to_i
      interval_start = (timestamp / interval).floor * interval
      event.set('index_time', Time.at(interval_start).utc.strftime('%Y.%m.%d.%H'))
    "
  }
}

output {
  elasticsearch {
    index => "logs-%{index_time}"
    hosts => ["${ELASTIC_HOSTS}"]
    user => "${ELASTIC_USERNAME}"
    password => "${ELASTIC_PASSWORD}"
    action => "create"
  } 
  stdout {
    codec => rubydebug
  }
}