# sonar.exclusions=**/*.json,**/*.yml,app/services/apps/image_analysis/segmentation1.py,**/test/**,**/*.spec.js,**/*.xml
sonar.exclusions=**/*.json,**/*.yml,**/*.xml
sonar.python.ignoreHeaderComments=true
sonar.ws.timeout=120
# sonar.exclusions=**/large-file.js
