# coding: utf-8

# flake8: noqa
"""
    JupyterHub REST API

    The REST API for JupyterHub. <a href=\"./\">Return to JupyterHub documentation</a>. 

    The version of the OpenAPI document: 5.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.delete_group_users_request import DeleteGroupUsersRequest
from openapi_client.models.delete_user_server_name_request import DeleteUserServerNameRequest
from openapi_client.models.get_api200_response import GetApi200Response
from openapi_client.models.get_group_shared200_response import GetGroupShared200Response
from openapi_client.models.get_info200_response import GetInfo200Response
from openapi_client.models.get_info200_response_authenticator import GetInfo200ResponseAuthenticator
from openapi_client.models.get_info200_response_spawner import GetInfo200ResponseSpawner
from openapi_client.models.get_user_shared200_response import GetUserShared200Response
from openapi_client.models.get_user_tokens200_response import GetUserTokens200Response
from openapi_client.models.group import Group
from openapi_client.models.new_token import NewToken
from openapi_client.models.paginated_list import PaginatedList
from openapi_client.models.pagination import Pagination
from openapi_client.models.pagination_next import PaginationNext
from openapi_client.models.patch_proxy_request import PatchProxyRequest
from openapi_client.models.patch_shares_server_request import PatchSharesServerRequest
from openapi_client.models.patch_user_request import PatchUserRequest
from openapi_client.models.post_auth_token200_response import PostAuthToken200Response
from openapi_client.models.post_auth_token_request import PostAuthTokenRequest
from openapi_client.models.post_group_users_request import PostGroupUsersRequest
from openapi_client.models.post_oauth_token200_response import PostOauthToken200Response
from openapi_client.models.post_share_code200_response import PostShareCode200Response
from openapi_client.models.post_share_code_request import PostShareCodeRequest
from openapi_client.models.post_shares_server_request import PostSharesServerRequest
from openapi_client.models.post_shutdown_request import PostShutdownRequest
from openapi_client.models.post_user_activity_request import PostUserActivityRequest
from openapi_client.models.post_user_activity_request_servers import PostUserActivityRequestServers
from openapi_client.models.post_user_activity_request_servers_server_name import PostUserActivityRequestServersServerName
from openapi_client.models.post_user_tokens_request import PostUserTokensRequest
from openapi_client.models.post_users_request import PostUsersRequest
from openapi_client.models.request_identity import RequestIdentity
from openapi_client.models.server import Server
from openapi_client.models.service import Service
from openapi_client.models.share import Share
from openapi_client.models.share_code import ShareCode
from openapi_client.models.share_group import ShareGroup
from openapi_client.models.share_user import ShareUser
from openapi_client.models.shared_server import SharedServer
from openapi_client.models.shared_server_user import SharedServerUser
from openapi_client.models.token import Token
from openapi_client.models.user import User
