# coding: utf-8

"""
    JupyterHub REST API

    The REST API for JupyterHub. <a href=\"./\">Return to JupyterHub documentation</a>. 

    The version of the OpenAPI document: 5.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.shared_server_user import SharedServerUser
from typing import Optional, Set
from typing_extensions import Self

class SharedServer(BaseModel):
    """
    Subset of Server model present in Share responses
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="the server name. '' for the default server.")
    url: Optional[StrictStr] = Field(default=None, description="the server's URL (path only when not using subdomains)")
    full_url: Optional[StrictStr] = Field(default=None, description="The full URL of the server (`https://hub.example.org/user/:name/:servername`). `null` unless JupyterHub.public_url or subdomains are configured. ")
    ready: Optional[StrictBool] = Field(default=None, description="whether the server is ready")
    user: Optional[SharedServerUser] = None
    __properties: ClassVar[List[str]] = ["name", "url", "full_url", "ready", "user"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SharedServer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        # set to None if full_url (nullable) is None
        # and model_fields_set contains the field
        if self.full_url is None and "full_url" in self.model_fields_set:
            _dict['full_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SharedServer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "url": obj.get("url"),
            "full_url": obj.get("full_url"),
            "ready": obj.get("ready"),
            "user": SharedServerUser.from_dict(obj["user"]) if obj.get("user") is not None else None
        })
        return _obj


