# coding: utf-8

"""
    JupyterHub REST API

    The REST API for JupyterHub. <a href=\"./\">Return to JupyterHub documentation</a>. 

    The version of the OpenAPI document: 5.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.share_group import ShareGroup
from openapi_client.models.share_user import ShareUser
from openapi_client.models.shared_server import SharedServer
from typing import Optional, Set
from typing_extensions import Self

class Share(BaseModel):
    """
    A single sharing permission. There is at most one of these objects per (server, user) or (server, group) combination. 
    """ # noqa: E501
    server: Optional[SharedServer] = Field(default=None, description="the server granting shared access")
    scopes: Optional[List[StrictStr]] = Field(default=None, description="the scopes granted by this Share")
    group: Optional[ShareGroup] = None
    user: Optional[ShareUser] = None
    created_at: Optional[datetime] = Field(default=None, description="when the share was first granted")
    __properties: ClassVar[List[str]] = ["server", "scopes", "group", "user", "created_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Share from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of server
        if self.server:
            _dict['server'] = self.server.to_dict()
        # override the default output from pydantic by calling `to_dict()` of group
        if self.group:
            _dict['group'] = self.group.to_dict()
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Share from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "server": SharedServer.from_dict(obj["server"]) if obj.get("server") is not None else None,
            "scopes": obj.get("scopes"),
            "group": ShareGroup.from_dict(obj["group"]) if obj.get("group") is not None else None,
            "user": ShareUser.from_dict(obj["user"]) if obj.get("user") is not None else None,
            "created_at": obj.get("created_at")
        })
        return _obj


