# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_cropinfobar.ipynb (unless otherwise specified).

__all__ = ['cropinfobar']

# Cell
# Load modules
import skimage
import matplotlib.pyplot as plt
import numpy as np

from skimage import io
from skimage.color import rgb2gray
from skimage.morphology import erosion, dilation, remove_small_holes, rectangle
from skimage.filters import threshold_otsu
from skimage.util import invert

import os
import glob
from pathlib import Path
from skimage import io

from statistics import mode
import pandas as pd

# Cell
def cropinfobar(image:'RGB or grayscale image'):
    '''
    Separates the image from the information bar.
    >Inputs
    >>image : RGB or grayscale image;

    >Outputs
    >>returns : cutoff, image, infobar, G_crop, crop_cutoff
    - cutoff : y-pixel cutoff point to crop the information bar from the image
    - image : image without the scalebar
    - infobar : cropped information bar containing scalebar
    - G_crop & crop_cutoff : only for visual confirmation of correct cutoff (see example below)
    '''

    try:
        # Convert image to grayscale image
        G = rgb2gray(image);
        test_continue = 1;
    except:
#         print('Error: Could not read image.') # do not use print statement, use logger
        test_continue = 0;

    if test_continue == 1:
        # Preliminary cropping of the image, used as an initial guess
        G_crop = G[list(range(round(image.shape[0]*13/16),
                          image.shape[0])),:]

        # get histogram of the grayscale values of the image
        G_crop_flat = G_crop.flatten()
        b, bins = np.histogram(G_crop_flat, bins=256)

        # find which grayscale value is the most commonly occurring
        # (this is usually the information bar)
        pixel_ind = np.where(b==max(b))[0][0]
        low, high = bins[[pixel_ind,pixel_ind+1]]

        # find locations of pixels that are identified as info bar
        G_seg = (G_crop<=high) & (G_crop>=low)

        # Treatment of image to help locate information bar
        G_seg = invert(G_seg) # invert image
        G_seg = remove_small_holes(G_seg) # fill small holes
        E2 = invert(G_seg) # invert image

        # Erosion, then dilation, horizontal direction ONLY
        E2 = erosion(E2,
                     rectangle(1,int(np.round(image.shape[1])/40)),
                     shift_x = True, shift_y=False)
        E2 = dilation(E2,
                      rectangle(1,int(np.round(image.shape[1])/10)),
                      shift_x = True, shift_y=False)

        # Coordinates of pixels that are in the info bar
        coords = (np.where(E2==1))

        try:
            # find the info bar
            cutoff = min(coords[0])
            image_crop = G[list(range(0,cutoff+round(image.shape[0]*13/16))),:]
            infobar = G_crop[list(range(cutoff,G_crop.shape[0])),:]

            return cutoff+round(image.shape[0]*13/16), image_crop, infobar, G_crop, cutoff

        except ValueError:
            # return error if it cannot find info bar
#             print('Error: Could not find information bar in the image.')
            return

    elif test_continue == 0:
        coords=[];
        return None, None, None, None, None

