# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_Random_Forest.ipynb (unless otherwise specified).

__all__ = ['RegressionXGboost']

# Cell
#export
import logging
import numpy as np
import pandas as pd
import xgboost as xgb
import dask.array as da
import dask.dataframe as dd
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.model_selection import cross_val_predict, KFold
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error, median_absolute_error
from app.services.AI.models.service import categorical_encoding, custom_scikit_train_test_split, custom_dask_train_test_split
# from dask_ml.model_selection import train_test_split as dask_train_test_split
# from dask_ml.metrics import mean_absolute_error as dask_mean_absolute_error
# from dask_ml.metrics import mean_squared_error as dask_mean_squared_error
# from dask_ml.metrics import r2_score as dask_r2_score
# from dask.distributed import LocalCluster, Client

logger = logging.getLogger(__package__)
logger.setLevel(logging.DEBUG)
handler = logging.StreamHandler()
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
handler.setFormatter(formatter)
logger.addHandler(handler)

# Cell
class RegressionXGBoost(object):
    
    def __init__(self, X , y, split_type="Random", n_estimators=10, max_depth=6, subsample=0.5, learning_rate=0.2, \
                 colsample_bytree=1, colsample_bylevel=1, colsample_bynode=1, reg_alpha=0, \
                 reg_lambda=1, gamma=20, num_parallel_tree=1, k_fold=None, split_ratio=0.2, \
                 split_random_state=None, use_dask=False, dr_basis=None, encoding_type=None, input_scaling='Standard'):
        
        logger.debug("Initializing RegressionXGBoost with parameters: ")
        
        self.feature_columns:pd.DataFrame = X.copy(deep=True)
        self.target_columns:pd.DataFrame = y.copy(deep=True)

        self.X = X
        self.y = y
        self.split_type = split_type
        self.n_estimators = n_estimators
        self.max_depth = max_depth
        self.subsample = subsample
        self.learning_rate = learning_rate
        self.colsample_bytree = colsample_bytree
        self.colsample_bylevel = colsample_bylevel
        self.colsample_bynode = colsample_bynode
        self.reg_alpha = reg_alpha
        self.reg_lambda = reg_lambda
        self.gamma = gamma
        self.num_parallel_tree = num_parallel_tree
        self.CV_folds = k_fold
        self.split_ratio = split_ratio / 100
        self.split_random_state = split_random_state
        self.use_dask = use_dask
        self.dr_basis = dr_basis
        self.cat_encoding = encoding_type
        self.input_scaling = input_scaling        

    def preprocess_xgboost(self):
        logger.debug("Starting preprocessing for XGBoost")
        
        # Setting model type for backend services of web-platform
        self.ml_method = 'XGBoost'
        X = self.X
        y = self.y

        # Adding feature names to the model instance
        if isinstance(self.X, (pd.DataFrame, dd.DataFrame)):
            self.feature_names = self.X.columns
        else:
            self.feature_names = ['Feature ' + str(i) for i in np.arange(self.X.shape[1]) + 1]

        logger.debug("Feature names: %s", self.feature_names)
        
        # Encoding for categorical variables
        self.cat_var_names = None
        if isinstance(self.X, pd.DataFrame):
            logger.debug("Encoding categorical variables")
            # Extracting categorical variables
            cat_var_names = self.X.select_dtypes(['object', 'category', 'string']).columns.to_list()

            if cat_var_names.__len__() > 0:
                self.cat_var_names = cat_var_names

                if self.cat_encoding == 'Onehot':
                    X = categorical_encoding(self.X.copy(), self.cat_var_names, None, cat_encoding=self.cat_encoding)
                    self.cat_encoding_info = self.encoded_feature_names = X.columns
                    y = self.y

                elif self.cat_encoding == 'Mean':
                    X, self.cat_encoding_info = categorical_encoding(self.X.copy().assign(**{self.y.name: self.y.values}), \
                                                                     self.cat_var_names, self.y.name, \
                                                                     cat_encoding=self.cat_encoding)
                    y = X[self.y.name]
                    X = X.drop(y.name, axis=1)

                else:
                    raise ValueError('cat_encoding parameter must be either "Onehot" or "Mean". but you entered {}'.format(self.cat_encoding))

        if isinstance(y, (pd.Series, dd.Series)):
            self.output_name = y.name
        else:
            self.output_name = 'Output'

        if self.use_dask and isinstance(X, dd.DataFrame):
            X = X.to_dask_array(lengths=True)
            y = y.to_dask_array(lengths=True)
        elif not self.use_dask and isinstance(X, np.ndarray):
            X = pd.DataFrame(X, columns=self.feature_names)
            y = pd.Series(y, name=self.output_name)

        if self.split_ratio == 100 or self.split_ratio == 0:
            self.X_train = X
            self.y_train = y
            self.X_test = self.X_train.copy() ; self.y_test = self.y_train.copy()
            
            self.train_ind = self.X_train.index.tolist(); self.test_ind = self.y_train.index.tolist()
            self.all_ind = self.X_train.index.tolist()
        # elif not 0 < self.split_ratio < 1:
        #     raise ValueError('Train-test split ratio must be between 0 and 1.')
        else:
            if self.use_dask:
                self.X_train, self.X_test, self.y_train, self.y_test, self.train_ind, self.test_ind = custom_dask_train_test_split(X, y,
                                                                                                     test_size=self.split_ratio,
                                                                                                     split_type=self.split_type,
                                                                                                     random_state=self.split_random_state
                                                                                                     )
                self.X_train = dd.from_dask_array(self.X_train, columns=self.feature_names)
                self.X_test = dd.from_dask_array(self.X_test, columns=self.feature_names)
                self.y_train = dd.from_dask_array(self.y_train, columns=self.output_name)
                self.y_test = dd.from_dask_array(self.y_test, columns=self.output_name)
            else:
                self.X_train, self.X_test, self.y_train, self.y_test, self.train_ind, self.test_ind = custom_scikit_train_test_split(X, y, 
                                                                                                       test_size=self.split_ratio,
                                                                                                       split_type=self.split_type,
                                                                                                       random_state=self.split_random_state
                                                                                                       )
                self.all_ind = self.train_ind.tolist() + self.test_ind.tolist()
                self.train_ind = self.train_ind.tolist(); self.test_ind =self.test_ind.tolist()
        
        logger.debug("Data split into training and testing sets")
        
        if self.input_scaling is not None:
            if self.input_scaling == "Standard":
                self.scaling_func = StandardScaler()
            elif self.input_scaling == "Min-Max":
                self.scaling_func = MinMaxScaler()
            elif self.input_scaling == "Robust":
                self.scaling_func = RobustScaler()
            
            self.X_train[self.X_train.columns] = self.scaling_func.fit_transform(self.X_train)
            self.X_test[self.X_test.columns] = self.scaling_func.transform(self.X_test)
            logger.debug("Data scaled using %s", self.input_scaling)
            
        elif self.input_scaling is None:
            self.scaling_func = None 
            logger.info("Data is not scaled")
        
        X = None; y = None;  # Removing original X and y to save memory    
        
    def train_xgb(self):
        logger.debug("Starting training for XGBoost")
        
        params = {'n_estimators': self.n_estimators, 'max_depth': self.max_depth, 'subsample': self.subsample, \
                  'learning_rate': self.learning_rate, 'colsample_bytree': self.colsample_bytree, \
                  'colsample_bylevel': self.colsample_bylevel, 'reg_alpha': self.reg_alpha, \
                  'colsample_bynode': self.colsample_bytree, 'gamma': self.gamma, 'reg_lambda': self.reg_lambda, \
                    'num_parallel_tree':self.num_parallel_tree
                 }

        params['tree_method'] = 'auto'
        
        X_train = self.X_train
        y_train = self.y_train
        X_test = self.X_test
        y_test = self.y_test
        self.test_y = y_test
        
        self.XGB = xgb.XGBRegressor(**params, booster='gbtree', objective='reg:squarederror')
        self.XGB.fit(X_train, y_train)
        logger.debug("Model training completed")

        self.yh_train = self.XGB.predict(X_train)
        self.Res_train = y_train - self.yh_train
        self.R2 = r2_score(y_train, self.yh_train)
        self.MAE_train = mean_absolute_error(y_train, self.yh_train)
        self.MSE_train = mean_squared_error(y_train, self.yh_train)
        self.PE_train = self.MAE_train * 100 / np.mean(np.abs(y_train))
        self.SSE_train = np.sum((y_train - self.yh_train) ** 2)
        self.RMSE_train = np.sqrt(self.MSE_train)
        self.cv_metrics = None
        
        logger.debug("Training metrics: R2: %s, MAE: %s, MSE: %s, PE: %s, SSE: %s, RMSE: %s", 
                     self.R2, self.MAE_train, self.MSE_train, self.PE_train, self.SSE_train, self.RMSE_train)
        
        if self.CV_folds:
            cv_ind = KFold(n_splits=self.CV_folds, random_state=self.split_random_state, shuffle=True)
            self.yh_CV = cross_val_predict(self.XGB, X_train, y_train, cv=cv_ind)
            self.Res_CV = y_train - self.yh_CV

            self.R2_CV = r2_score(y_train, self.yh_CV)
            self.MAE_CV = mean_absolute_error(y_train, self.yh_CV)
            self.MSE_CV = mean_squared_error(y_train, self.yh_CV)
            self.PE_CV = self.MAE_CV * 100 / np.mean(np.abs(y_train))
            self.SSE_CV = np.sum((y_train - self.yh_CV) ** 2)
            self.RMSE_CV = np.sqrt(self.MSE_CV)
            mape = mean_absolute_percentage_error(y_train, self.yh_CV) * 100
            medae = median_absolute_error(y_train, self.yh_CV)
            self.cv_metrics = {
                "Mean Absolute Error (MAE)": self.MAE_CV,
                "Mean Squared Error (MSE)": self.MSE_CV,
                "Root Mean Squared Error (RMSE)": self.RMSE_CV,
                "R2 Score": self.R2_CV,
                "Mean Absolute Percentage Error (MAPE)": mape,
                "Median Absolute Error (MedAE)": medae,
            }
            logger.debug("Cross-validation metrics: %s", self.cv_metrics)

        if not self.split_ratio is None:
            self.yh_test = self.XGB.predict(X_test)
            self.Res_test = y_test - self.yh_test
            self.R2_test = r2_score(y_test, self.yh_test)
            self.MAE_test = mean_absolute_error(y_test, self.yh_test)
            self.MSE_test = mean_squared_error(y_test, self.yh_test)
            self.PE_test = self.MAE_test * 100 / np.mean(np.abs(y_train))
            self.SSE_test = np.sum((y_test - self.yh_test) ** 2)
            self.RMSE_test = np.sqrt(self.MSE_test)
            logger.debug("Test metrics: R2: %s, MAE: %s, MSE: %s, PE: %s, SSE: %s, RMSE: %s", 
                         self.R2_test, self.MAE_test, self.MSE_test, self.PE_test, self.SSE_test, self.RMSE_test)

    def feature_importance(self):
        logger.debug("Calculating feature importance")
        n_features = self.feature_columns.shape[1]
        
        if len(self.test_ind) < 5:
            X_fi, y_fi = self.feature_columns, self.target_columns
        else:
            X_fi, y_fi = self.feature_columns.iloc[self.test_ind], self.target_columns.iloc[self.test_ind]
            
        y_pred = self.predict(X_fi)
        baseline_performance = mean_squared_error(y_fi, y_pred)
        logger.info(f'Baseline metric: {baseline_performance}')
        
        if len(y_fi) < 5:
            raise ValueError("Data must be longer than 5 samples to compute Permutation Feature Importance")
        elif len(y_fi) < 20:
            n_run = 10
        elif len(y_fi) < 50:
            n_run = 3
        else:
            n_run = 1
        
        importances = np.zeros([n_features, n_run])
        importances_avg = np.zeros([n_features, n_run])
        
        for j in range(n_run):
            for i, label in enumerate(X_fi):
                permuted_X = X_fi.copy(deep=True)
                # permuted_X[label] = permuted_X[label].values[np.random.permutation(len(y_fi))]
                permuted_X[label] = permuted_X[label].values[np.random.RandomState(seed=42).permutation(len(y_fi))]
                y_pred = self.predict(permuted_X)
                permuted_performance = mean_squared_error(y_fi, y_pred)
                importances[i, j] = baseline_performance - permuted_performance
            importances[:, j] /= importances[:, j].sum(axis=0)
            importances_avg[:, j] = importances[:, :j+1].mean(axis=1)
        
        return importances
    
    def predict(self, X_t, client=None):
        logger.debug("Making predictions")
        
        if hasattr(self, 'cat_encoding_info') and isinstance(X_t, pd.DataFrame):
            if self.cat_encoding == 'Mean':
                for i in self.cat_encoding_info:
                    X_t[i] = X_t[i].copy().map(self.cat_encoding_info[i])
            elif self.cat_encoding == 'Onehot':
                X_t = pd.get_dummies(X_t, self.cat_var_names)
                missing_cols = set(self.cat_encoding_info) - set(X_t.columns)
                for i in missing_cols:
                    X_t[i] = 0
                X_t = X_t[self.cat_encoding_info]

        if not self.dr_basis is None:
            X_t = self.dr_basis.transform(X_t)

        if self.input_scaling is not None:
            X_t = self.scaling_func.transform(X_t)

        # if isinstance(X_t, np.ndarray):
        #     if hasattr(self, 'cat_var_names') and self.cat_var_names is not None:
        #         X_t = pd.DataFrame(X_t, columns=self.cat_encoding_info)
        #     else:
        #         X_t = pd.DataFrame(X_t, columns=self.feature_names)

        return self.XGB.predict(X_t)
