{
 "title": "Active Users Information",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Daily Active Users (DAU)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(user_id) (increase(user_actions_total{action=~\"Run Workflow |Save Workflow\"}[1d]))>0) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weekly Active Users (WAU)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(user_id) (increase(user_actions_total{action=~\"Run Workflow |Save Workflow\"}[7d]))>0) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monthly Active Users (MAU)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(user_id) (increase(user_actions_total{action=~\"Run Workflow |Save Workflow\"}[30d]))>0) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active logins",
   "type": "gauge",
   "description": "This metrics is used to track the number of active users on the platform ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "active_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "User Based API call count",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "count(token_validation_total) by (user_email)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}