{
 "title": "API And Metrics Tracking",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Active Users",
   "type": "gauge",
   "description": "This metrics is used to track the number of active users on the platform ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Computation of the Memory usage, averaged over a 30s time interval ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(node_memory_MemTotal_bytes[30s]) - (avg_over_time(node_memory_MemFree_bytes[30s]) + avg_over_time(node_memory_Buffers_bytes[30s]) + avg_over_time(node_memory_Cached_bytes[30s]))\r\n",
     "legendFormat": "USED"
    },
    {
     "expr": "avg_over_time(node_memory_MemFree_bytes[30s])",
     "legendFormat": "FREE"
    },
    {
     "expr": "avg_over_time(node_memory_Buffers_bytes[30s])",
     "legendFormat": "BUFFER"
    },
    {
     "expr": "avg_over_time(node_memory_Cached_bytes[30s])",
     "legendFormat": "CACHED"
    }
   ]
  },
  {
   "title": "API Request in Progress",
   "type": "timeseries",
   "description": "The number of API requests in progress can be tracked here (A dot at 1 describes there is 1 API request in progress; a dot at 2 describes 2 API requests are occurring at the same time)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "api_requests_in_progress{endpoint!=\"\"}\r\n",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "description": "Computation of the Disk usage, averaged over a 30 second interval ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg_over_time(node_filesystem_free_bytes{mountpoint=\"/\"}[30s]) / avg_over_time(node_filesystem_size_bytes{mountpoint=\"/\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 API Call Based on Latency",
   "type": "timeseries",
   "description": "This metrics consists of top 10 API calls with respect to time in minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, rate(api_request_latency_seconds_sum{endpoint!=\"\"}[30s]) / rate(api_request_latency_seconds_count{endpoint!=\"\"}[30s]))\r\n",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Disk Operations",
   "type": "timeseries",
   "description": "The dual graph displays the time taken for read and write disk operation and the total i/o time consumed in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[30s]))",
     "legendFormat": "Read Operation"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[30s]))",
     "legendFormat": "Write Operation"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[30s]))",
     "legendFormat": "Time Spent"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Computation of the CPU usage percentage, averaged over a 30-second interval for each CPU mode. It sums the CPU time spent in each mode and divides it by the total number of CPU cores. The resultant indicates how CPU resources are allocated across various operational modes over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total[30s])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "node_processes_state", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "The network I/O operation are tracked over an average time interval of 30s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[30s]))",
     "legendFormat": "Network Input (Received Bytes)"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[30s]))",
     "legendFormat": "Network Output (Transmitted Bytes)"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total[30s])) + sum(rate(node_network_transmit_bytes_total[30s]))",
     "legendFormat": "Combined Network I/O (Receive + Transmit)"
    }
   ]
  },
  {
   "title": "Memory Usage (RSS and VIRT)",
   "type": "timeseries",
   "description": "Computation of the Resident and Virtual memory usage, averaged over a 30 second interval ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (process) (rate(process_virtual_memory_bytes[30s]))",
     "legendFormat": "VIRT"
    },
    {
     "expr": "sum by (process) (rate(process_resident_memory_bytes[30s]))",
     "legendFormat": "RSS"
    }
   ]
  }
 ]
}