{
 "title": "Error-Tracing",
 "description": "For finding and back tracing errors",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "user_email" },
   { "name": "correlation_ID" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Errors Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "hexaind3.levelname:\"ERROR\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logged Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "hexaind3.levelname:\"ERROR\"\n",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Errors From Identified User",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "hexaind3.levelname:\"ERROR\" AND hexaind3.user_email:\"$user_email\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log messages of identified user",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "hexaind3.user_email:\"$user_email\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log messages with given correlation ID",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "hexaind3.correlation_id:\"$correlation_ID\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}