# -*- coding: utf-8 -*-
"""
Created on Wed Oct 2 10:59:19 2024

@author: leclerc
"""

import gpytorch
import torch
import textwrap

# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_MultiPolynomial_Regression.ipynb (unless otherwise specified).

__all__ = ["RegressionMPR"]

# Cell
# export
import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# import dask.dataframe as dd
# import dask.array as da

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold, cross_val_predict, train_test_split
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
    mean_absolute_percentage_error,
    median_absolute_error,
)
from sklearn.preprocessing import PolynomialFeatures
from sklearn.utils import resample
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
import mlflow
import logging
import warnings
import sys

# from .Visualizations import parity_plot
# from .Utilities import categorical_encoding, CategoricalTransformer, PolynomialTransformer, custom_scikit_train_test_split, custom_dask_train_test_split
from app.services.AI.multi_polynomial_regression.Utilities import (
    CategoricalTransformer,
    PolynomialTransformer,
)
from app.services.AI.models.service import custom_scikit_train_test_split

# from dask_ml.preprocessing import PolynomialFeatures as dask_PolynomialFeatures
# from dask_ml.model_selection import train_test_split as dask_train_test_split
# from dask_ml.metrics import mean_absolute_error as dask_mean_absolute_error
# from dask_ml.metrics import mean_squared_error as dask_mean_squared_error
# from dask_ml.metrics import r2_score as dask_r2_score
# from dask_ml.linear_model import LinearRegression as dask_LinearRegression
# from dask import delayed
# from dask.distributed import Client, LocalCluster

logger = logging.getLogger(__package__)
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler(sys.stdout))


# Cell
class RegressionMPR(object):

    # Function for checking overfitting
    def _overfit_warning(self, num_var, num_datap):
        self.premature_exit = False
        if num_var > 0.5 * num_datap and num_var < num_datap:
            self.fit_warning = "overfit"
            msg = """
                The number of variables in feature space is larger than half of the number of
                datapoints. Overfitting may occur. Reducing the polynomial power may address
                the potential overfitting problem.
                """

            logger.warning(msg)
        elif num_var > num_datap:
            self.fit_warning = "nomodel"
            msg = """
                The number of variables in feature space is larger than the number of
                datapoints. Please provide more datapoints or select lower degrees of polynomials.
                """
            self.premature_exit = True
            self.premature_exit_msg = msg
            logger.warning(msg)
            return
        else:
            self.fit_warning = None

    # This function creates a custom polynomial power matrix ---> Is not used
    #     def _arrange_polynomials(PD, num_var, use_dask):

    #         if PD is None:
    #             # Setting the power of variables to 1 if nothing is entered. This applies linear
    #             # regression by default.
    #             PD = 1

    #         if isinstance(PD, int):
    #             # If an integer is entered for PD, it is replicated to accommodate all variables
    #             PD = PD * np.ones((1, num_var))
    #         elif PD.__len__() < num_var:
    #             raise ValueError('PD variable must either be an integer or a list/numpy array with'\
    #                              'with the same number of arrays as the number of variables in input.')

    #         # Converting the PV to np.array in case it is a tuple or list and setting the negative
    #         # values to 0
    #         PD = np.asarray(PD)
    #         PD[PD < 0] = 0

    #         # Maximum degree for polynomials
    #         max_pow = np.max(PD).astype(int)

    #         if use_dask:
    #             poly = dask_PolynomialFeatures(max_pow, include_bias = True)
    #         else:
    #             poly = PolynomialFeatures(max_pow, include_bias = True)
    #         poly.fit(np.zeros((1, num_var)))

    #         # Removing the monomials with variables that have larger powers than
    #         # assigned in power array
    #         valid_poly_indices = (poly.powers_ <= np.tile(PD,(poly.powers_.shape[0],1))).all(1)

    #         return poly, valid_poly_indices

    # MultiPolynomial Regression
    def __init__(
        self,
        X,
        y,
        split_type=None,
        PD=None,
        CV_folds=None,
        split_ratio=None,
        split_random_state=None,
        use_dask=False,
        dr_basis=None,
        n_models=20,
        cat_encoding=None,
        input_scaling=None,
    ):
        self.feature_columns: pd.DataFrame = X
        self.target_columns: pd.DataFrame = y

        self.X = self.feature_columns.copy(deep=True)
        self.y = self.target_columns.copy(deep=True)
        # split_type:
        self.split_type = split_type
        self.input_scaling = input_scaling
        self.cat_encoding = cat_encoding

        # Adding feature names to the model instance
        if isinstance(self.X, (pd.DataFrame)):  # , dd.DataFrame)):
            self.feature_names = self.X.columns
        else:
            self.feature_names = [
                "Feature " + str(i) for i in np.arange(self.X.shape[1]) + 1
            ]

        # Encoding for categorical variables
        if isinstance(self.X, pd.DataFrame):
            # Initialization of categorical transformer
            CT = CategoricalTransformer(cat_encoding=self.cat_encoding)

            # Fitting the categorical transformer
            CT.fit(self.X, self.y)
            self.X = CT.transform(self.X.copy())
            # Writing the transformer to class
            self.categorical_transformer = CT
            logger.info("Encoding Applied")
        # Adding output name to the model instance
        if isinstance(self.y, (pd.Series)):  # , dd.Series)):
            self.output_name = self.y.name
        else:
            self.output_name = "Output"

        # Setting model type for backend services of web-platform
        self.ml_method = "MPR"

        # Adding use_dask flag to model instance
        self.use_dask = use_dask

        # Updating the X array to appropriate type of dataframe
        #         if self.use_dask and isinstance(X, dd.DataFrame):
        #             X = X.to_dask_array(lengths = True)
        #             y = y.to_dask_array(lengths = True)
        if not self.use_dask and isinstance(self.X, np.ndarray):
            self.X = pd.DataFrame(self.X, columns=self.feature_names)
            self.y = pd.Series(self.y, name=self.output_name)

        # Setting up the train test ratio
        if split_ratio is None or split_ratio == 0:
            self.X_train = self.X
            self.y_train = self.y
            self.X_test = self.X_train.copy()
            self.y_test = self.y_train.copy()
            self.train_ind = self.X_train.index.tolist()
            self.test_ind = self.y_train.index.tolist()
            self.all_ind = self.X_train.index.tolist()
        # elif not 0 < split_ratio < 1:
        #     raise ValueError('Train-test split ratio must be between 0 and 1.')
        else:
            if self.use_dask:
                (
                    self.X_train,
                    self.X_test,
                    self.y_train,
                    self.y_test,
                    self.train_ind,
                    self.test_ind,
                ) = custom_dask_train_test_split(
                    self.X,
                    self.y,
                    test_size=split_ratio,
                    split_type=self.split_type,
                    random_state=split_random_state,
                )
            else:
                (
                    self.X_train,
                    self.X_test,
                    self.y_train,
                    self.y_test,
                    self.train_ind,
                    self.test_ind,
                ) = custom_scikit_train_test_split(
                    self.X,
                    self.y,
                    test_size=split_ratio,
                    split_type=self.split_type,
                    random_state=split_random_state,
                )

                self.all_ind = self.train_ind.tolist() + self.test_ind.tolist()
                self.train_ind = self.train_ind.tolist()
                self.test_ind = self.test_ind.tolist()

                self.y_train, self.y_test = np.array(self.y_train), np.array(
                    self.y_test
                )

        self.X = None
        self.y = None
        # Removing original X, y and train_ind to save memory

        # self.train_ind, self.test_ind = self.train_ind, self.test_ind

        if not self.input_scaling is None:
            # Scale the data based on user selection options are : Standardization, Normalization, Robust Scaler
            if self.input_scaling == "Standard":
                self.scaling_func = StandardScaler()
            elif self.input_scaling == "Min_Max":
                self.scaling_func = MinMaxScaler()
            elif self.input_scaling == "Robust":
                self.scaling_func = RobustScaler()

            self.X_train[self.X_train.columns] = self.scaling_func.fit_transform(
                self.X_train
            )
            self.X_test[self.X_test.columns] = self.scaling_func.transform(self.X_test)
            logger.debug("Data scaled using %s", self.input_scaling)

        else:
            # Maybe we can raise warning that data is not scaled
            logger.info("Data is not scaled")
            self.scaling_func = None

        # Adding basis information to model instance
        self.dr_basis = dr_basis

        # Creating the polynomial terms

        if PD != 1:
            self.polynomial_transformer = PolynomialTransformer(PD)
            self.polynomial_transformer.fit(self.X_train)
            Poly_for_coef = PolynomialFeatures(np.max(PD))
            Poly_for_coef.fit_transform(self.X_train)
            self.input_names = list(self.X_train.columns)
            # self.coef_index = [f"i{x+1}" for x in range(len(self.input_names))]
            self.coef_index = self.input_names
            self.coef_names = Poly_for_coef.get_feature_names_out(self.coef_index)
            self.coef_names[0] = "intercept"
            self.Xf_train = self.polynomial_transformer.transform(self.X_train)
            logger.info("Polynomial tranformer Applied")
            if split_ratio is not None:
                self.Xf_test = self.polynomial_transformer.transform(self.X_test)
        else:
            self.Xf_train = self.X_train.copy()
            Xf_test = self.X_test.copy()
            Coef_val = list(self.X_train.columns.values)
            self.input_names = Coef_val
            self.coef_index = [f"i{x+1}" for x in range(len(self.input_names))]
            self.coef_names = ["intercept"] + self.coef_index
            self.Xf_test = self.X_test.copy()
            # if split_ratio is not None:
            #     self.X_train = None; self.X_test = None

        # Raise overfit-warning if the number of variables in feature space is larger than half of
        # the data points or exiting class if the number of variables in feature space is larger
        # than the number of data points
        RegressionMPR._overfit_warning(
            self, self.Xf_train.shape[1], self.Xf_train.shape[0]
        )
        if self.fit_warning == "nomodel":
            logger.info(
                "No model can be built with the given data. Please provide more data or reduce the polynomial degree."
            )
            return

        # if self.use_dask:

        #     # Writing test indices to model instance
        #     self.test_ind = test_ind.compute()

        #     # Setting the number of points in resampled training sets
        #     n_samples = Xf_train.shape[1] * 10

        #     # Converting y_train to numpy version for digitization
        #     y_train = y_train.compute()

        #     # Binning the output array so stratified resampling can be done
        #     bins = np.linspace(np.min(y_train), np.max(y_train), 20)
        #     y_binned = np.digitize(y_train, bins)

        #     # Lazy computing of bagging of MPR models
        #     MPR_models = []  # Initialization of GP_models collection
        #     train_ind = []
        #     for m in range(n_models):
        #         data_ind = resample(np.arange(y_train.shape[0]), n_samples = n_samples, stratify = y_binned)
        #         train_ind.append(data_ind)
        #         MPR = delayed(LinearRegression().fit)(Xf_train[data_ind], y_train[data_ind])
        #         MPR_models.append(MPR)

        #     # Fitting the GPs with DASK
        #     all_submodels = delayed()(MPR_models)
        #     MPR_models = all_submodels.compute()

        #     # Taking the average of coefficients from all models and build a new model reflecting it
        #     coef_av = []
        #     intercept_av = []
        #     for model in MPR_models:
        #         coef_av.append(model.coef_)
        #         intercept_av.append(model.intercept_)
        #     coef_ = np.mean(np.vstack(coef_av), axis = 0)
        #     intercept_ = np.mean(intercept_av)
        #     X_dummy = da.random.random((coef_.shape[0] * 2, X_train.shape[1]))
        #     Xf_dummy = self.poly.transform(X_dummy)
        #     Xf_dummy = Xf_dummy[:, self.valid_poly_indices]
        #     y_dummy = Xf_dummy @ coef_[:, None] + intercept_
        #     self.MPR = dask_LinearRegression(solver = 'newton', tol = 1e-6, \
        #                                      max_iter = 300).fit(Xf_dummy, y_dummy[:, 0])

        #     # Extracting the unique indices of the training indices
        #     self.train_ind = np.unique([item for sublist in train_ind for item in sublist])

        #     # Results of the model built on all data
        #     self.yh_train = self.MPR.predict(Xf_train[self.train_ind])
        #     self.Res_train = y_train[self.train_ind] - self.yh_train  # Residuals
        #     self.R2 = r2_score(y_train[self.train_ind], self.yh_train)  # R2
        #     self.MAE_train = mean_absolute_error(y_train[self.train_ind], self.yh_train)  # Mean absolute error
        #     self.MSE_train = mean_squared_error(y_train[self.train_ind], self.yh_train)  # Mean squared error
        #     self.PE_train = self.MAE_train * 100 / np.mean(np.abs(y_train[self.train_ind]))

        #     if not split_ratio is None:

        #         # Metrics of test set
        #         self.yh_test = self.MPR.predict(Xf_test)
        #         self.Res_test = y_test.compute() - self.yh_test
        #         self.MAE_test = dask_mean_absolute_error(y_test, self.yh_test)
        #         self.MSE_test = dask_mean_squared_error(y_test, self.yh_test)
        #         self.PE_test = self.MAE_test * 100 / np.mean(np.abs(y_train))

        # Regular MPR on all data set
        if not self.use_dask:

            # Writing trainining and test indices to model instance
            # self.test_ind = self.test_ind
            # self.train_ind = self.train_ind

            # Fitting the model to the entire data
            self.MPR = LinearRegression()
            self.MPR.fit(self.Xf_train, self.y_train)
            # self.coefficients = self.MPR.coef_
            # self.intercept =  self.MPR.intercept_
            self.coefficients = np.concatenate(
                (self.MPR.intercept_, self.MPR.coef_), axis=None
            )

            # Results of the model built on all data
            mean_output = np.mean(np.abs(self.y_train))
            self.yh_train = self.MPR.predict(self.Xf_train)  # Predictions
            # self.Xf_test_pre = self.MPR.predict(Xf_test)
            # combined_X = pd.concat([self.Xf_train, self.Xf_test], axis=0)  # axis=0 for rows (samples)
            combined_X = np.concatenate((self.Xf_train, self.Xf_test), axis=0)
            # self.all_data_prediction  = self.MPR.predict(combined_X)
            self.Res_train = self.y_train - self.yh_train  # Residuals
            self.R2 = r2_score(self.y_train, self.yh_train)  # R2
            self.MAE_train = mean_absolute_error(
                self.y_train, self.yh_train
            )  # Mean absolute error
            self.MAPE = mean_absolute_percentage_error(self.y_train, self.yh_train)
            self.MSE_train = mean_squared_error(
                self.y_train, self.yh_train
            )  # Mean squared error
            self.MADEA_test = median_absolute_error(self.y_train, self.yh_train)

            self.PE_train = self.MAE_train * 100 / mean_output
            self.SSE_train = np.sum(
                (self.y_train - self.yh_train) ** 2
            )  # Sum of Squares error
            self.RMSE_train = np.sqrt(self.MSE_train)  # Root Mean Square Error
            self.metrics_report = {
                "Mean Absolute Error (MAE)": self.MAE_train,
                "Mean Squared Error (MSE)": self.MSE_train,
                "Root Mean Squared Error (RMSE)": self.RMSE_train,
                "R2 Score": self.R2,
                "Mean Absolute Percentage Error (MAPE)": self.MAPE,
                "Median Absolute Error (MedAE)": self.MADEA_test,
            }
            # logger.info(f"Metrics_report: {str(self.metrics_report)}")

            # Cross-validation50
            self.cv_metrics = None
            if not CV_folds is None:
                cv_ind = KFold(
                    n_splits=CV_folds, random_state=split_random_state, shuffle=True
                )
                self.yh_CV = cross_val_predict(
                    self.MPR, self.Xf_train, self.y_train, cv=cv_ind
                )
                self.Res_CV = (
                    self.y_train - self.yh_CV
                )  # Residuals based on cross-validation
                self.R2_CV = r2_score(self.y_train, self.yh_CV)
                self.MAE_CV = mean_absolute_error(self.y_train, self.yh_CV)
                self.MSE_CV = mean_squared_error(self.y_train, self.yh_CV)
                self.PE_CV = self.MAE_CV * 100 / mean_output
                self.SSE_CV = np.sum(
                    (self.y_train - self.yh_CV) ** 2
                )  # Sum of Squares error
                self.RMSE_CV = np.sqrt(self.MSE_CV)  # Root Mean Square Error
                self.MAPE = mean_absolute_percentage_error(self.y_train, self.yh_train)
                self.MADEA_test = median_absolute_error(self.y_train, self.yh_train)

                self.cv_metrics = {
                    "Mean Absolute Error (MAE)": self.MAE_CV,
                    "Mean Squared Error (MSE)": self.MSE_CV,
                    "Root Mean Squared Error (RMSE)": self.RMSE_CV,
                    "R2 Score": self.R2_CV,
                    "Mean Absolute Percentage Error (MAPE)": self.MAPE,
                    "Median Absolute Error (MedAE)": self.MADEA_test,
                }
                # logger.info(f"CV_metrics: {str(self.cv_metrics)}")

            if not split_ratio is None:
                logger.info(f"Xf_test shape{str(self.Xf_test.shape)}")
                # Metrics of test set
                self.yh_test = self.MPR.predict(self.Xf_test)
                self.Res_test = self.y_test - self.yh_test
                self.R2_test = r2_score(self.y_test, self.yh_test)
                self.MAE_test = mean_absolute_error(self.y_test, self.yh_test)
                self.MSE_test = mean_squared_error(self.y_test, self.yh_test)
                self.MAPE_test = mean_absolute_percentage_error(
                    self.y_test, self.yh_test
                )
                self.MADEA_test = median_absolute_error(self.y_test, self.yh_test)
                self.PE_test = self.MAE_test * 100 / mean_output
                self.SSE_test = np.sum(
                    (self.y_test - self.yh_test) ** 2
                )  # Sum of Squares error
                self.RMSE_test = np.sqrt(self.MSE_test)  # Root Mean Square Error

    #             # Building on entire dataset after train_test_split
    #             if split_ratio is None:
    #                 self.MPR = LinearRegression().fit(Xf_train, y_train)
    #             else:
    #                 self.MPR = LinearRegression().fit(np.concatenate([Xf_train, Xf_test], axis = 0), \
    #                                                   np.concatenate([y_train, y_test]))

    # Prediction by casting future points in feature space

    def feature_importance(self):
        # logger.debug("Calculating feature importance")
        n_features = self.feature_columns.shape[1]
        if len(self.test_ind) < 5:
            X_fi, y_fi = self.feature_columns, self.target_columns
        else:
            X_fi, y_fi = (
                self.feature_columns.iloc[self.test_ind],
                self.target_columns.iloc[self.test_ind],
            )

        y_pred = self.predict(X_fi)
        baseline_performance = mean_squared_error(y_fi, y_pred)
        logger.info(f"Baseline metric: {baseline_performance}")

        if len(y_fi) < 5:
            raise ValueError(
                "Data must be longer than 5 samples to compute Permutation Feature Importance"
            )
        elif len(y_fi) < 20:
            n_run = 10
        elif len(y_fi) < 50:
            n_run = 3
        else:
            n_run = 1

        importances = np.zeros([n_features, n_run])
        importances_avg = np.zeros([n_features, n_run])

        for j in range(n_run):
            for i, label in enumerate(X_fi):
                permuted_X = X_fi.copy(deep=True)
                permuted_X[label] = permuted_X[label].values[
                    np.random.permutation(len(y_fi))
                ]
                y_pred = self.predict(permuted_X)
                permuted_performance = mean_squared_error(y_fi, y_pred)
                importances[i, j] = baseline_performance - permuted_performance
            importances[:, j] /= importances[:, j].sum(axis=0)
            importances_avg[:, j] = importances[:, : j + 1].mean(axis=1)

        return importances

    def predict(self, X_t):

        if hasattr(self, "categorical_transformer") and isinstance(X_t, pd.DataFrame):
            X_t = self.categorical_transformer.transform(X_t)

        # Cast into a reduced order space if any
        if self.dr_basis is not None:
            X_t = self.dr_basis.transform(X_t)

        # Scale the data with same scaling
        if self.input_scaling is not None:

            X_t = self.scaling_func.transform(X_t)

        # Casting the test input into feature space
        if hasattr(self, "polynomial_transformer"):
            Xf_t = self.polynomial_transformer.transform(X_t)
        else:
            Xf_t = X_t.copy()
            X_t = None

        # Dask or regular version
        if self.use_dask:
            return self.MPR.predict(Xf_t).compute()
        else:
            return self.MPR.predict(Xf_t)

    # Method for visualizing parity plot


#     def parity_plot(self, split_type = 'cv', ax = None, interactive = True, fig_height = 5, dpi = 80, \
#                     imageloc = None, fig = None, return_fig = False, thumbnail = False):

#         params = {'ax': ax, 'fig': fig, 'interactive': interactive, 'fig_height': fig_height, \
#                   'imageloc': imageloc, 'split_type': split_type, 'dpi': dpi, 'return_fig': return_fig, \
#                   'thumbnail': thumbnail}

#         if split_type == 'test':
#             fig_out = parity_plot(self.Res_test + self.yh_test, self.yh_test, **params)
#         elif split_type == 'training':
#             fig_out = parity_plot(self.Res_train + self.yh_train, self.yh_train, **params)
#         elif split_type == 'cv':
#             fig_out = parity_plot(self.Res_CV + self.yh_CV, self.yh_CV, **params)

#         # Return figure. For platform purposes
#         if return_fig:
#             return fig_out
