mobo_wf = {
    "widgets": [
        {
            "urn": "4ed64d27-f849-4d63-98ba-9f6a187b454b",
            "name": "Widget-CSV_FILE-KlmW",
            "description": "DefaultWidgetDescription",
            "type": "DATA_COPY",
            "config": {
                "version": "1.0",
                "widget_type": "DATA_COPY",
                "source": {
                    "type": "LOCAL",
                    "configuration": {
                        "version": "1.0",
                        "dataset_id": "662bc62ada4184d5a7f22ade",
                    },
                },
                "sink": {
                    "dataset_name": "csv_dataset",
                    "dataset_description": "csv_dataset_description",
                },
            },
            "state": "IDLE",
            "on_success": ["88d4df12-5edf-4dc4-868e-18748b3a43d6"],
            "on_failure": [],
            "on_complete": [],
            "inputs": [],
            "outputs": [
                {
                    "urn": "4ed64d27-f849-4d63-98ba-9f6a187b454b",
                    "map_to_argument": "",
                    "type": "DATASET",
                    "name": "P1&P3-Demo_Widget-CSV_FILE-KlmW_Tabular",
                }
            ],
            "use_gpu": False,
            "retry_interval_in_sec": 30,
            "retry_count": 30,
            "client_tags": {
                "PositionX": 244.73684210526312,
                "PositionY": 121.02631578947368,
                "Width": 90,
                "Height": 90,
                "Color": "#1A7A7F",
                "ClientType": "CSV_FILE",
            },
        },
        {
            "urn": "d67def55-2daa-4e0b-8b51-206b2eb97d6a",
            "name": "Widget-SAVE-LsEh",
            "description": "DefaultWidgetDescription",
            "type": "SAVE",
            "config": {
                "version": "1.0",
                "widget_type": "SAVE",
                "datasetConfig": [
                    {
                        "dataset_name": "P1&P3-Demo_Widget-MOBO-eEZ9_Tabular",
                        "destination_type": "HEXAIND_PLATFORM",
                        "destination_config": {
                            "file_Format": "CSV",
                            "save_options": "SAVE_AS",
                            "save_option_config": {"file_name": "P1_results_042624"},
                            "destination_folder_path": "",
                        },
                        "doNotSaveFlag": False,
                    }
                ],
            },
            "state": "IDLE",
            "on_success": [],
            "on_failure": [],
            "on_complete": [],
            "inputs": [
                {
                    "urn": "f043bc87-4b05-4665-add1-b540822413d3",
                    "map_to_argument": "",
                    "type": "DATASET",
                    "name": "P1&P3-Demo_Widget-MOBO-eEZ9_Tabular",
                }
            ],
            "outputs": [],
            "use_gpu": False,
            "retry_interval_in_sec": 30,
            "retry_count": 30,
            "client_tags": {
                "PositionX": 800,
                "PositionY": 140,
                "Width": 90,
                "Height": 90,
                "Color": "#1A7A7F",
                "ClientType": "SAVE",
            },
        },
        {
            "urn": "f043bc87-4b05-4665-add1-b540822413d3",
            "name": "Widget-MOBO-eEZ9",
            "description": "DefaultWidgetDescription",
            "type": "MOBO",
            "config": {
                "version": "0.1",
                "widget_type": "MOBO",
                "experiment_type": "OPTIMIZATION",
                "features_detail": [
                    {
                        "name": "dcp_spacer",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "pp_spacer",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "ips_pressure",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "up_pressure",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "friction_coeff",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "upper_radius",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "lower_radius",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "t_value",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "lr_opening",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "catcher_depth",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "ips_radius",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "dcr_radius",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "dcp_radius_1",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "dcp_radius_2",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "buckle_pressure",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": False,
                        "output": True,
                    },
                    {
                        "name": "max_thinning",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": False,
                        "output": True,
                    },
                ],
                "input_variables": [
                    "dcp_spacer",
                    "pp_spacer",
                    "ips_pressure",
                    "up_pressure",
                    "friction_coeff",
                    "upper_radius",
                    "lower_radius",
                    "t_value",
                    "lr_opening",
                    "catcher_depth",
                    "ips_radius",
                    "dcr_radius",
                    "dcp_radius_1",
                    "dcp_radius_2",
                ],
                "input_variables_constraints": [
                    [0.18, 0.1800081872482225],
                    [0.144, 0.1440113157142549],
                    [61.75703273, 116.5307904],
                    [60.0, 60.00329545758292],
                    [0.05, 0.0500031855913903],
                    [0.005153495, 0.031429292],
                    [0.005101214, 0.030728065],
                    [0.010755824, 0.036],
                    [1.679, 1.729843213],
                    [0.085417634, 0.1],
                    [0.029229092, 0.1],
                    [0.060678336, 0.123677806],
                    [0.027145029, 0.1],
                    [0.02, 0.1],
                ],
                "output_variables": ["buckle_pressure", "max_thinning"],
                "output_variables_objectives": ["MAXIMUM", "MINIMUM"],
                "output_variables_thresholds": [111.0, 11.0],
                "num_iterations": 1,
                "batch_size": 1,
                "constraints_module_id": None,
                "outcome_constraints_active": False,
                "outcome_constraints_variable": None,
                "outcome_constraints_operator": "",
                "outcome_constaints_inputvalue": None,
                "dataset": None,
            },
            "state": "IDLE",
            "on_success": ["572fdfaf-ff88-421b-91e5-2fdfc0fc3f59"],
            "on_failure": [],
            "on_complete": [],
            "inputs": [
                {
                    "urn": "88d4df12-5edf-4dc4-868e-18748b3a43d6",
                    "map_to_argument": "",
                    "type": "DATASET",
                    "name": "P1&P3-Demo_Widget-CSV_FILE-KlmW_Tabular",
                }
            ],
            "outputs": [
                {
                    "urn": "f043bc87-4b05-4665-add1-b540822413d3",
                    "map_to_argument": "",
                    "type": "DATASET",
                    "name": "P1&P3-Demo_Widget-MOBO-eEZ9_Tabular",
                }
            ],
            "use_gpu": False,
            "retry_interval_in_sec": 30,
            "retry_count": 30,
            "client_tags": {
                "PositionX": 531.0526315789474,
                "PositionY": 154.71052631578948,
                "Width": 90,
                "Height": 90,
                "Color": "#1A7A7F",
                "ClientType": "MOBO",
            },
        },
        {
            "urn": "abbeee29-25ce-489c-aa3a-6cc14b2db833",
            "name": "Widget-RESCALE-LH6A",
            "description": "DefaultWidgetDescription",
            "type": "RESCALE",
            "config": {
                "widget_type": "RESCALE",
                "rescale_connector_id": "66955348c109e706996ab008",
                "rescale_configs": {
                    "name": "Sample ABAQUS Simulation",
                    "test_mode": True,
                    "run_job": False,
                    "software": {
                        "hardware": {
                            "coreType": "starlite_max",
                            "slots": 1,
                            "coresPerSlot": 4,
                            "walltime": 3,
                            "type": None,
                        },
                        "analysis": {
                            "version": "2021-golden-DSLS",
                            "code": "abaqus-dsls",
                        },
                        "reusable_job_file": "custom_driver.py,MG_Forming.py,MG_Springback.py,MG_Buckling.py,PostProcessing.py,Visualizer.py,scaler.pkl,gp_scaling.pkl,sedata.csv",
                        "dynamic_job_file": "param_values.csv",
                        "pre_python": None,
                        "post_python": "custom_driver.py,scaler.pkl,gp_scaling.pkl",
                        "command": "abaqus cae noGUI=MG_Forming.py; abaqus job=FormingJob.inp cpus=$RESCALE_CORES_PER_SLOT mp_mode=mpi interactive parallel=domain double=both output_precision=full; abaqus cae noGUI=MG_Springback.py; abaqus job=SpringbackJob.inp cpus=$RESCALE_CORES_PER_SLOT mp_mode=mpi interactive double=both output_precision=full; abaqus cae noGUI=MG_Buckling.py; abaqus job=BucklingJob.inp cpus=$RESCALE_CORES_PER_SLOT mp_mode=mpi interactive double=both output_precision=full; abaqus python PostProcessing.py;abaqus cae noGUI=Visualizer.py",
                        "output_file": "PerfMetricsFile.csv",
                        "visualize_files": [
                            "ShellGeometry.png",
                            "ShellGeometry_Closeup.png",
                            "FormingAnimation_Script.avi",
                        ],
                        "envVars": {
                            "DSLS_LICENSE_FILE": "4085@novelis",
                            "LSTC_LICENSE_SERVER": None,
                        },
                        "onDemandLicenseSeller": None,
                    },
                    "files_detail": [
                        {
                            "file_name": "custom_driver.py",
                            "file_path": "/hexaind-data/hexaind-datasets/connection/661fdd495a76ce9ec0f1307e/662ba6bfc846cbdb13191710/custom_driver.py",
                            "upload_rescale": True,
                            "rescale_id": "",
                        },
                        {
                            "file_name": "MG_Forming.py",
                            "file_path": "/hexaind-data/hexaind-datasets/connection/661fdd495a76ce9ec0f1307e/MG_Forming.py",
                            "upload_rescale": True,
                            "rescale_id": "",
                        },
                        {
                            "file_name": "MG_Springback.py",
                            "file_path": "/hexaind-data/hexaind-datasets/connection/661fdd495a76ce9ec0f1307e/MG_Springback.py",
                            "upload_rescale": True,
                            "rescale_id": "",
                        },
                        {
                            "file_name": "MG_Buckling.py",
                            "file_path": "/hexaind-data/hexaind-datasets/connection/661fdd495a76ce9ec0f1307e/MG_Buckling.py",
                            "upload_rescale": True,
                            "rescale_id": "",
                        },
                        {
                            "file_name": "PostProcessing.py",
                            "file_path": "/hexaind-data/hexaind-datasets/connection/661fdd495a76ce9ec0f1307e/PostProcessing.py",
                            "upload_rescale": True,
                            "rescale_id": "",
                        },
                        {
                            "file_name": "Visualizer.py",
                            "file_path": "/hexaind-data/hexaind-datasets/connection/661fdd495a76ce9ec0f1307e/Visualizer.py",
                            "upload_rescale": True,
                            "rescale_id": "",
                        },
                        {
                            "file_name": "scaler.pkl",
                            "file_path": "/hexaind-data/hexaind-datasets/connection/661fdd495a76ce9ec0f1307e/662ba6bfc846cbdb13191710/scaler.pkl",
                            "upload_rescale": True,
                            "rescale_id": "",
                        },
                        {
                            "file_name": "gp_scaling.pkl",
                            "file_path": "/hexaind-data/hexaind-datasets/connection/661fdd495a76ce9ec0f1307e/662ba6bfc846cbdb13191710/gp_scaling.pkl",
                            "upload_rescale": True,
                            "rescale_id": "",
                        },
                        {
                            "file_name": "sedata.csv",
                            "file_path": "/hexaind-data/hexaind-datasets/connection/661fdd495a76ce9ec0f1307e/sedata.csv",
                            "upload_rescale": True,
                            "rescale_id": "",
                        },
                    ],
                },
                "version": "1.0",
            },
            "state": "IDLE",
            "on_success": ["88d4df12-5edf-4dc4-868e-18748b3a43d6"],
            "on_failure": [],
            "on_complete": [],
            "inputs": [
                {
                    "urn": "572fdfaf-ff88-421b-91e5-2fdfc0fc3f59",
                    "map_to_argument": "",
                    "type": "DATASET",
                    "name": "P1&P3-Demo_Widget-MOBO-eEZ9_Tabular",
                }
            ],
            "outputs": [
                {
                    "urn": "abbeee29-25ce-489c-aa3a-6cc14b2db833",
                    "map_to_argument": "",
                    "type": "DATASET",
                    "name": "P1&P3-Demo_Widget-RESCALE-LH6A_Tabular",
                }
            ],
            "use_gpu": False,
            "retry_interval_in_sec": 30,
            "retry_count": 30,
            "client_tags": {
                "PositionX": 531.0526315789474,
                "PositionY": 19.9736842105263,
                "Width": 90,
                "Height": 90,
                "Color": "#1A7A7F",
                "ClientType": "RESCALE",
            },
        },
        {
            "urn": "88d4df12-5edf-4dc4-868e-18748b3a43d6",
            "name": "Widget-LOOP_START-yvnk",
            "description": "DefaultWidgetDescription",
            "type": "LOOP_START",
            "config": {
                "version": "1.0",
                "widget_type": "LOOP_START",
                "loop_start_config": {"xyz": 1, "abc": 1},
            },
            "state": "IDLE",
            "on_success": ["f043bc87-4b05-4665-add1-b540822413d3"],
            "on_failure": [],
            "on_complete": [],
            "inputs": [
                {
                    "urn": "abbeee29-25ce-489c-aa3a-6cc14b2db833",
                    "map_to_argument": "",
                    "type": "DATASET",
                    "name": "P1&P3-Demo_Widget-RESCALE-LH6A_Tabular",
                }
            ],
            "outputs": [
                {
                    "urn": "4ed64d27-f849-4d63-98ba-9f6a187b454b",
                    "map_to_argument": "",
                    "type": "DATASET",
                    "name": "P1&P3-Demo_Widget-CSV_FILE-KlmW_Tabular",
                },
                {
                    "urn": "abbeee29-25ce-489c-aa3a-6cc14b2db833",
                    "map_to_argument": "",
                    "type": "DATASET",
                    "name": "P1&P3-Demo_Widget-RESCALE-LH6A_Tabular",
                },
            ],
            "use_gpu": False,
            "retry_interval_in_sec": 30,
            "retry_count": 30,
            "client_tags": {
                "PositionX": 379.4736842105263,
                "PositionY": 121.02631578947368,
                "Width": 90,
                "Height": 90,
                "Color": "#1A7A7F",
                "ClientType": "LOOP_START",
            },
        },
        {
            "urn": "572fdfaf-ff88-421b-91e5-2fdfc0fc3f59",
            "name": "Widget-LOOP_END-hGVm",
            "description": "DefaultWidgetDescription",
            "type": "LOOP_END",
            "config": {
                "version": "1.0",
                "widget_type": "LOOP_END",
                "termination_criteria": "ON_LOOP_COUNT",
                "loop_end_config": {"loop_count": 2},
                "on_loop": ["abbeee29-25ce-489c-aa3a-6cc14b2db833"],
                "on_termination": ["d67def55-2daa-4e0b-8b51-206b2eb97d6a"],
            },
            "state": "IDLE",
            "on_success": [
                "d67def55-2daa-4e0b-8b51-206b2eb97d6a",
                "abbeee29-25ce-489c-aa3a-6cc14b2db833",
            ],
            "on_failure": [],
            "on_complete": [],
            "inputs": [
                {
                    "urn": "f043bc87-4b05-4665-add1-b540822413d3",
                    "map_to_argument": "",
                    "type": "DATASET",
                    "name": "P1&P3-Demo_Widget-MOBO-eEZ9_Tabular",
                }
            ],
            "outputs": [
                {
                    "urn": "f043bc87-4b05-4665-add1-b540822413d3",
                    "map_to_argument": "",
                    "type": "DATASET",
                    "name": "P1&P3-Demo_Widget-MOBO-eEZ9_Tabular",
                }
            ],
            "use_gpu": False,
            "retry_interval_in_sec": 30,
            "retry_count": 30,
            "client_tags": {
                "PositionX": 660,
                "PositionY": 140,
                "Width": 90,
                "Height": 90,
                "Color": "#1A7A7F",
                "ClientType": "LOOP_END",
            },
        },
    ],
    "start": ["4ed64d27-f849-4d63-98ba-9f6a187b454b"],
    "end": ["d67def55-2daa-4e0b-8b51-206b2eb97d6a"],
    "user_id": "664c569824e6fd041c96c25b",
    "user_name": "Test User",
    "client_tags": {
        "StartWidgetPosition": {"X": 126.84210526315786, "Y": 121.02631578947368},
        "EndWidgetPosition": {"X": 940, "Y": 140},
        "Arrows": [
            {
                "start_urn": "START",
                "start_connector_point_type": 2,
                "end_urn": "4ed64d27-f849-4d63-98ba-9f6a187b454b",
                "end_connector_point_type": 1,
                "arrow_type": 0,
            },
            {
                "start_urn": "4ed64d27-f849-4d63-98ba-9f6a187b454b",
                "start_connector_point_type": 2,
                "end_urn": "88d4df12-5edf-4dc4-868e-18748b3a43d6",
                "end_connector_point_type": 1,
                "arrow_type": 0,
            },
            {
                "start_urn": "88d4df12-5edf-4dc4-868e-18748b3a43d6",
                "start_connector_point_type": 2,
                "end_urn": "f043bc87-4b05-4665-add1-b540822413d3",
                "end_connector_point_type": 1,
                "arrow_type": 0,
            },
            {
                "start_urn": "f043bc87-4b05-4665-add1-b540822413d3",
                "start_connector_point_type": 2,
                "end_urn": "572fdfaf-ff88-421b-91e5-2fdfc0fc3f59",
                "end_connector_point_type": 1,
                "arrow_type": 0,
            },
            {
                "start_urn": "572fdfaf-ff88-421b-91e5-2fdfc0fc3f59",
                "start_connector_point_type": 2,
                "end_urn": "d67def55-2daa-4e0b-8b51-206b2eb97d6a",
                "end_connector_point_type": 1,
                "arrow_type": 0,
            },
            {
                "start_urn": "572fdfaf-ff88-421b-91e5-2fdfc0fc3f59",
                "start_connector_point_type": 0,
                "end_urn": "abbeee29-25ce-489c-aa3a-6cc14b2db833",
                "end_connector_point_type": 2,
                "arrow_type": 0,
            },
            {
                "start_urn": "abbeee29-25ce-489c-aa3a-6cc14b2db833",
                "start_connector_point_type": 1,
                "end_urn": "88d4df12-5edf-4dc4-868e-18748b3a43d6",
                "end_connector_point_type": 2,
                "arrow_type": 0,
            },
            {
                "start_urn": "d67def55-2daa-4e0b-8b51-206b2eb97d6a",
                "start_connector_point_type": 2,
                "end_urn": "END",
                "end_connector_point_type": 1,
                "arrow_type": 0,
            },
        ],
    },
}
