p2wf = {
    "widgets": [
        {
            "urn": "0190c49a-9f4f-761d-92a4-1e3e816cca3c",
            "name": "CSV",
            "description": "DefaultWidgetDescription",
            "type": "DATA_COPY",
            "config": {
                "version": "1.0",
                "widget_type": "DATA_COPY",
                "source": {
                    "type": "LOCAL",
                    "configuration": {
                        "version": "1.0",
                        "dataset_id": "668d27f77208febb3f552572",
                    },
                },
                "sink": {
                    "dataset_name": "csv_dataset",
                    "dataset_description": "csv_dataset_description",
                },
            },
            "state": "IDLE",
            "on_success": ["0190c49a-9f4f-715d-93dd-d374c41de370"],
            "on_failure": [],
            "on_complete": [],
            "inputs": [],
            "outputs": [
                {
                    "urn": "0190c49a-9f4f-761d-92a4-1e3e816cca3c",
                    "map_to_argument": "",
                    "type": "DATASET",
                    "name": "Demo Project_CSV_FILE-7hRf_Tabular",
                }
            ],
            "use_gpu": False,
            "retry_interval_in_sec": 30,
            "retry_count": 30,
            "client_tags": {
                "PositionX": 178.45,
                "PositionY": 74.97500000000001,
                "Width": 90,
                "Height": 90,
                "Color": "#1A7A7F",
                "ClientType": "CSV_FILE",
            },
        },
        {
            "urn": "0190c49a-9f4f-715d-93dd-d374c41de370",
            "name": "LOOP_START",
            "description": "DefaultWidgetDescription",
            "type": "LOOP_START",
            "config": {
                "version": "1.0",
                "widget_type": "LOOP_START",
                "loop_start_config": {"xyz": 1, "abc": 1},
            },
            "state": "IDLE",
            "on_success": ["0190c49a-9f4f-78df-ba79-6bf421099866"],
            "on_failure": [],
            "on_complete": [],
            "inputs": [
                {
                    "urn": "0190c49a-9f4f-761d-92a4-1e3e816cca3c",
                    "map_to_argument": "",
                    "type": "DATASET",
                    "name": "Demo Project_CSV_FILE-7hRf_Tabular",
                }
            ],
            "outputs": [
                {
                    "urn": "0190c49a-9f4f-761d-92a4-1e3e816cca3c",
                    "map_to_argument": "",
                    "type": "DATASET",
                    "name": "Demo Project_CSV_FILE-7hRf_Tabular",
                }
            ],
            "use_gpu": False,
            "retry_interval_in_sec": 30,
            "retry_count": 30,
            "client_tags": {
                "PositionX": 320.8499999999999,
                "PositionY": 92.77499999999998,
                "Width": 90,
                "Height": 90,
                "Color": "#1A7A7F",
                "ClientType": "LOOP_START",
            },
        },
        {
            "urn": "0190c49a-9f4f-7da2-b2e9-887352b8d765",
            "name": "LOOP_END",
            "description": "DefaultWidgetDescription",
            "type": "LOOP_END",
            "config": {
                "version": "1.0",
                "widget_type": "LOOP_END",
                "termination_criteria": "ON_LOOP_COUNT",
                "loop_end_config": {"loop_count": 2},
                "on_loop": ["0190c49a-9f4f-7251-b512-fb9556c8a869"],
                "on_termination": ["0190c49a-9f4f-7fe3-8c9e-6a40e927f1b6"],
            },
            "state": "IDLE",
            "on_success": [
                "0190c49a-9f4f-7251-b512-fb9556c8a869",
                "0190c49a-9f4f-7fe3-8c9e-6a40e927f1b6",
            ],
            "on_failure": [],
            "on_complete": [],
            "inputs": [
                {
                    "urn": "0190c49a-9f4f-78df-ba79-6bf421099866",
                    "map_to_argument": "",
                    "type": "DATASET",
                    "name": "Demo Project_MOBO-sYPC_Tabular",
                }
            ],
            "outputs": [
                {
                    "urn": "0190c49a-9f4f-78df-ba79-6bf421099866",
                    "map_to_argument": "",
                    "type": "DATASET",
                    "name": "Demo Project_MOBO-sYPC_Tabular",
                }
            ],
            "use_gpu": False,
            "retry_interval_in_sec": 30,
            "retry_count": 30,
            "client_tags": {
                "PositionX": 659.05,
                "PositionY": 92.77499999999998,
                "Width": 90,
                "Height": 90,
                "Color": "#1A7A7F",
                "ClientType": "LOOP_END",
            },
        },
        {
            "urn": "0190c49a-9f4f-78df-ba79-6bf421099866",
            "name": "MOBO",
            "description": "DefaultWidgetDescription",
            "type": "MOBO",
            "config": {
                "version": "1.0",
                "widget_type": "MOBO",
                "experiment_type": "OPTIMIZATION",
                "features_detail": [
                    {
                        "name": "Si",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "Fe",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "Cu",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "Mn",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "Mg",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "Cr",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "Ti",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "Zn",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "Zr",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "Sn",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "V",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "Ge",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "HO_Step_1_Temp(C)",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "HO_Step_1_Time(hr)",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "HO_Step_2_Temp(C)",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "HO_Step_2_Time(hr)",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "HO_Step_3_Temp(C)",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "HO_Step_3_Time(hr)",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "HR_Lay_Down_Temp(C)",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "HR_Transfer_Slab_Gauge_(IG)",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "HB_gauge",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "HR_Exit(C)",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "pHR",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "CR_Final_Gauge",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "pCR",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "CASH_PMT",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "CASH_Dwell_time_Above_540(sec)",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "PX_Temp(C)",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "NA_Time(days)",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "AA_Temperature(C)",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "AA_Time(min)",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "Prestrain",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": True,
                        "output": False,
                    },
                    {
                        "name": "Yield_Strength",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": False,
                        "output": True,
                    },
                    {
                        "name": "Uniform_Elongation",
                        "dataType": "Numerical",
                        "selected": True,
                        "input": False,
                        "output": True,
                    },
                ],
                "input_variables": [
                    "Si",
                    "Fe",
                    "Cu",
                    "Mn",
                    "Mg",
                    "Cr",
                    "Ti",
                    "Zn",
                    "Zr",
                    "Sn",
                    "V",
                    "Ge",
                    "HO_Step_1_Temp(C)",
                    "HO_Step_1_Time(hr)",
                    "HO_Step_2_Temp(C)",
                    "HO_Step_2_Time(hr)",
                    "HO_Step_3_Temp(C)",
                    "HO_Step_3_Time(hr)",
                    "HR_Lay_Down_Temp(C)",
                    "HR_Transfer_Slab_Gauge_(IG)",
                    "HB_gauge",
                    "HR_Exit(C)",
                    "pHR",
                    "CR_Final_Gauge",
                    "pCR",
                    "CASH_PMT",
                    "CASH_Dwell_time_Above_540(sec)",
                    "PX_Temp(C)",
                    "NA_Time(days)",
                    "AA_Temperature(C)",
                    "AA_Time(min)",
                    "Prestrain",
                ],
                "input_variables_constraints": [
                    [0.61, 0.82],
                    [0.23, 0.32],
                    [0.09, 0.19],
                    [0.07, 0.32],
                    [0.63, 0.69],
                    [0.01, 0.19],
                    [0.01, 0.04],
                    [0.01, 0.02],
                    [0, 0.12],
                    [0, 0.01],
                    [0, 0.14],
                    [0, 1],
                    [530, 560],
                    [6, 8],
                    [0, 540],
                    [0, 2],
                    [0, 0.67],
                    [0, 0],
                    [515, 540],
                    [40, 76],
                    [5, 10],
                    [330, 395],
                    [0.87, 0.88],
                    [0.9, 1],
                    [0.81, 2],
                    [578, 580],
                    [35, 45],
                    [100, 110],
                    [24, 37],
                    [25, 28],
                    [80, 83],
                    [0, 4],
                ],
                "output_variables": ["Yield_Strength", "Uniform_Elongation"],
                "output_variables_objectives": ["MAXIMUM", "MINIMUM"],
                "output_variables_thresholds": [90, 14],
                "num_iterations": 1,
                "batch_size": 1,
                "constraints_module_id": None,
                "outcome_constraints_active": False,
                "outcome_constraints_variable": None,
                "outcome_constraints_operator": "",
                "outcome_constaints_inputvalue": None,
                "dataset": None,
            },
            "state": "IDLE",
            "on_success": ["0190c49a-9f4f-7da2-b2e9-887352b8d765"],
            "on_failure": [],
            "on_complete": [],
            "inputs": [
                {
                    "urn": "0190c49a-9f4f-715d-93dd-d374c41de370",
                    "map_to_argument": "",
                    "type": "DATASET",
                    "name": "Demo Project_CSV_FILE-7hRf_Tabular",
                }
            ],
            "outputs": [
                {
                    "urn": "0190c49a-9f4f-78df-ba79-6bf421099866",
                    "map_to_argument": "",
                    "type": "DATASET",
                    "name": "Demo Project_MOBO-sYPC_Tabular",
                }
            ],
            "use_gpu": False,
            "retry_interval_in_sec": 30,
            "retry_count": 30,
            "client_tags": {
                "PositionX": 498.8499999999998,
                "PositionY": 181.77499999999998,
                "Width": 90,
                "Height": 90,
                "Color": "#1A7A7F",
                "ClientType": "MOBO",
            },
        },
        {
            "urn": "0190c49a-9f4f-7251-b512-fb9556c8a869",
            "name": "THERMOCALC-fmQq",
            "description": "DefaultWidgetDescription",
            "type": "THERMOCALC",
            "config": {
                "version": "1.0",
                "widget_type": "THERMOCALC",
                "thermocalc_connector_id": "6698ba2a48cbbb13f3f49656",
                "module_id": "668d293571aa5e0e76fc7357",
                "input_features": [
                    "CASH_PMT",
                    "HO_Step_3_Time(hr)",
                    "HB_gauge",
                    "Prestrain",
                    "Ge",
                    "Sn",
                    "Mg",
                    "Mn",
                    "HO_Step_1_Time(hr)",
                    "HR_Transfer_Slab_Gauge_(IG)",
                    "PX_Temp(C)",
                    "Ti",
                    "Zr",
                    "HO_Step_1_Temp(C)",
                    "HO_Step_2_Temp(C)",
                    "Zn",
                    "Cr",
                    "Fe",
                    "Cu",
                    "V",
                    "CASH_Dwell_time_Above_540(sec)",
                    "HR_Exit(C)",
                    "CR_Final_Gauge",
                    "NA_Time(days)",
                    "AA_Time(min)",
                    "Si",
                    "HR_Lay_Down_Temp(C)",
                    "HO_Step_2_Time(hr)",
                    "pHR",
                    "HO_Step_3_Temp(C)",
                    "pCR",
                    "AA_Temperature(C)",
                ],
                "output_features": [
                    "Cu_ss",
                    "Q_ALCUMGSI",
                    "AL2CU_C16",
                    "Fe_ss",
                    "Mg_pss",
                    "DIAMOND_A4",
                    "AL6MN",
                    "Si_pss",
                    "pcpt_radius",
                    "AL15SI2M4",
                    "Mg_ss",
                    "Si_ss",
                    "ALMG_BETA",
                    "Mn_pss",
                    "Fe_pss",
                    "MG2SI_C1",
                    "AL13FE4",
                    "pcpt_volfrac",
                    "AL9FE2SI2",
                    "FCC_A1",
                    "Mn_ss",
                    "solidus_temp",
                    "solvus_temp",
                    "HO_Avg_Temp(C)",
                    "Cu_pss",
                    "ys_cal",
                ],
            },
            "state": "IDLE",
            "on_success": ["0190c49a-9f4f-715d-93dd-d374c41de370"],
            "on_failure": [],
            "on_complete": [],
            "inputs": [],
            "outputs": [
                {
                    "urn": "0190c49a-9f4f-7251-b512-fb9556c8a869",
                    "map_to_argument": "",
                    "type": "DATASET",
                    "name": "Demo Project_THERMOCALC-fmQq_Tabular",
                }
            ],
            "use_gpu": False,
            "retry_interval_in_sec": 30,
            "retry_count": 30,
            "client_tags": {
                "PositionX": 498.8499999999998,
                "PositionY": 3.7749999999999773,
                "Width": 90,
                "Height": 90,
                "Color": "#1A7A7F",
                "ClientType": "THERMOCALC",
            },
        },
        {
            "urn": "0190c49a-9f4f-7fe3-8c9e-6a40e927f1b6",
            "name": "SAVE",
            "description": "DefaultWidgetDescription",
            "type": "SAVE",
            "config": {
                "version": "1.0",
                "widget_type": "SAVE",
                "datasetConfig": [
                    {
                        "dataset_name": "Demo Project_MOBO-sYPC_Tabular",
                        "destination_type": "HEXAIND_PLATFORM",
                        "destination_config": {
                            "file_Format": "CSV",
                            "save_options": "SAVE_AS",
                            "save_option_config": {
                                "file_name": "Demo Project_SAVE-tSOv_752"
                            },
                            "destination_folder_path": "",
                        },
                        "doNotSaveFlag": False,
                    }
                ],
            },
            "state": "IDLE",
            "on_success": [],
            "on_failure": [],
            "on_complete": [],
            "inputs": [
                {
                    "urn": "0190c49a-9f4f-78df-ba79-6bf421099866",
                    "map_to_argument": "",
                    "type": "DATASET",
                    "name": "Demo Project_MOBO-sYPC_Tabular",
                }
            ],
            "outputs": [],
            "use_gpu": False,
            "retry_interval_in_sec": 30,
            "retry_count": 30,
            "client_tags": {
                "PositionX": 801.45,
                "PositionY": 110.57499999999999,
                "Width": 90,
                "Height": 90,
                "Color": "#1A7A7F",
                "ClientType": "SAVE",
            },
        },
    ],
    "start": ["0190c49a-9f4f-761d-92a4-1e3e816cca3c"],
    "end": ["0190c49a-9f4f-7fe3-8c9e-6a40e927f1b6"],
    "client_tags": {
        "StartWidgetPosition": {"X": 36.050000000000125, "Y": 146.17499999999998},
        "EndWidgetPosition": {"X": 943.8500000000003, "Y": 92.77499999999998},
        "Arrows": [
            {
                "start_urn": "START",
                "start_connector_point_type": 2,
                "end_urn": "0190c49a-9f4f-761d-92a4-1e3e816cca3c",
                "end_connector_point_type": 1,
                "arrow_type": 0,
            },
            {
                "start_urn": "0190c49a-9f4f-761d-92a4-1e3e816cca3c",
                "start_connector_point_type": 2,
                "end_urn": "0190c49a-9f4f-715d-93dd-d374c41de370",
                "end_connector_point_type": 1,
                "arrow_type": 0,
            },
            {
                "start_urn": "0190c49a-9f4f-715d-93dd-d374c41de370",
                "start_connector_point_type": 2,
                "end_urn": "0190c49a-9f4f-78df-ba79-6bf421099866",
                "end_connector_point_type": 1,
                "arrow_type": 0,
            },
            {
                "start_urn": "0190c49a-9f4f-78df-ba79-6bf421099866",
                "start_connector_point_type": 2,
                "end_urn": "0190c49a-9f4f-7da2-b2e9-887352b8d765",
                "end_connector_point_type": 1,
                "arrow_type": 0,
            },
            {
                "start_urn": "0190c49a-9f4f-7da2-b2e9-887352b8d765",
                "start_connector_point_type": 1,
                "end_urn": "0190c49a-9f4f-7251-b512-fb9556c8a869",
                "end_connector_point_type": 2,
                "arrow_type": 0,
            },
            {
                "start_urn": "0190c49a-9f4f-7251-b512-fb9556c8a869",
                "start_connector_point_type": 1,
                "end_urn": "0190c49a-9f4f-715d-93dd-d374c41de370",
                "end_connector_point_type": 2,
                "arrow_type": 0,
            },
            {
                "start_urn": "0190c49a-9f4f-7da2-b2e9-887352b8d765",
                "start_connector_point_type": 2,
                "end_urn": "0190c49a-9f4f-7fe3-8c9e-6a40e927f1b6",
                "end_connector_point_type": 1,
                "arrow_type": 0,
            },
            {
                "start_urn": "0190c49a-9f4f-7fe3-8c9e-6a40e927f1b6",
                "start_connector_point_type": 2,
                "end_urn": "END",
                "end_connector_point_type": 1,
                "arrow_type": 0,
            },
        ],
    },
    "user_id": "664c569824e6fd041c96c25b",
    "user_name": "Test User"
}
