# coding: utf-8

"""
    JupyterHub REST API

    The REST API for JupyterHub. <a href=\"./\">Return to JupyterHub documentation</a>. 

    The version of the OpenAPI document: 5.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from jupyterhub_client.models.get_info200_response_authenticator import GetInfo200ResponseAuthenticator
from jupyterhub_client.models.get_info200_response_spawner import GetInfo200ResponseSpawner
from typing import Optional, Set
from typing_extensions import Self

class GetInfo200Response(BaseModel):
    """
    GetInfo200Response
    """ # noqa: E501
    version: Optional[StrictStr] = Field(default=None, description="The version of JupyterHub itself")
    python: Optional[StrictStr] = Field(default=None, description="The Python version, as returned by sys.version")
    sys_executable: Optional[StrictStr] = Field(default=None, description="The path to sys.executable running JupyterHub")
    authenticator: Optional[GetInfo200ResponseAuthenticator] = None
    spawner: Optional[GetInfo200ResponseSpawner] = None
    __properties: ClassVar[List[str]] = ["version", "python", "sys_executable", "authenticator", "spawner"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetInfo200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of authenticator
        if self.authenticator:
            _dict['authenticator'] = self.authenticator.to_dict()
        # override the default output from pydantic by calling `to_dict()` of spawner
        if self.spawner:
            _dict['spawner'] = self.spawner.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetInfo200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "python": obj.get("python"),
            "sys_executable": obj.get("sys_executable"),
            "authenticator": GetInfo200ResponseAuthenticator.from_dict(obj["authenticator"]) if obj.get("authenticator") is not None else None,
            "spawner": GetInfo200ResponseSpawner.from_dict(obj["spawner"]) if obj.get("spawner") is not None else None
        })
        return _obj


