# coding: utf-8

"""
    JupyterHub REST API

    The REST API for JupyterHub. <a href=\"./\">Return to JupyterHub documentation</a>. 

    The version of the OpenAPI document: 5.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from jupyterhub_client.models.shared_server import SharedServer
from typing import Optional, Set
from typing_extensions import Self

class PostShareCode200Response(BaseModel):
    """
    PostShareCode200Response
    """ # noqa: E501
    server: Optional[SharedServer] = Field(default=None, description="the server granting shared access")
    scopes: Optional[List[StrictStr]] = Field(default=None, description="the scopes granted by this Share")
    id: Optional[StrictStr] = Field(default=None, description="the share-code's id. Can be used to revoke share codes. ")
    created_at: Optional[datetime] = Field(default=None, description="when the share code was issued")
    expires_at: Optional[datetime] = Field(default=None, description="When the share code will expire, always in the future. `null` if the code does not expire. ")
    code: Optional[StrictStr] = Field(default=None, description="The share code itself")
    accept_url: Optional[StrictStr] = Field(default=None, description="The URL path for accepting the code")
    full_accept_url: Optional[StrictStr] = Field(default=None, description="The full URL for accepting the code, if JupyterHub.public_url configuration is defined. ")
    __properties: ClassVar[List[str]] = ["server", "scopes", "id", "created_at", "expires_at", "code", "accept_url", "full_accept_url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostShareCode200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of server
        if self.server:
            _dict['server'] = self.server.to_dict()
        # set to None if full_accept_url (nullable) is None
        # and model_fields_set contains the field
        if self.full_accept_url is None and "full_accept_url" in self.model_fields_set:
            _dict['full_accept_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostShareCode200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "server": SharedServer.from_dict(obj["server"]) if obj.get("server") is not None else None,
            "scopes": obj.get("scopes"),
            "id": obj.get("id"),
            "created_at": obj.get("created_at"),
            "expires_at": obj.get("expires_at"),
            "code": obj.get("code"),
            "accept_url": obj.get("accept_url"),
            "full_accept_url": obj.get("full_accept_url")
        })
        return _obj


