# coding: utf-8

"""
    JupyterHub REST API

    The REST API for JupyterHub. <a href=\"./\">Return to JupyterHub documentation</a>. 

    The version of the OpenAPI document: 5.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Server(BaseModel):
    """
    Server
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="The server's name. The user's default server has an empty name ('')")
    ready: Optional[StrictBool] = Field(default=None, description="Whether the server is ready for traffic. Will always be false when any transition is pending. ")
    stopped: Optional[StrictBool] = Field(default=None, description="Whether the server is stopped. Added in JupyterHub 3.0, and only useful when using the `?include_stopped_servers` request parameter. Now that stopped servers may be included (since JupyterHub 3.0), this is the simplest way to select stopped servers. Always equivalent to `not (ready or pending)`. ")
    pending: Optional[StrictStr] = Field(default=None, description="The currently pending action, if any. A server is not ready if an action is pending. ")
    url: Optional[StrictStr] = Field(default=None, description="The URL path where the server can be accessed (typically /user/:name/:server.name/). Will be a full URL if subdomains are configured. ")
    progress_url: Optional[StrictStr] = Field(default=None, description="The URL path for an event-stream to retrieve events during a spawn. ")
    full_url: Optional[StrictStr] = Field(default=None, description="The full URL of the server (`https://hub.example.org/user/:name/:servername`). `null` unless JupyterHub.public_url or subdomains are configured.  Added in 5.0. ")
    full_progress_url: Optional[StrictStr] = Field(default=None, description="The full URL for the progress events (`https://hub.example.org/hub/api/users/:name/servers/:servername/progress`). `null` unless JupyterHub.public_url is configured.  Added in 5.0. ")
    started: Optional[datetime] = Field(default=None, description="UTC timestamp when the server was last started.")
    last_activity: Optional[datetime] = Field(default=None, description="UTC timestamp last-seen activity on this server.")
    state: Optional[Dict[str, Any]] = Field(default=None, description="Arbitrary internal state from this server's spawner. Only available on the hub's users list or get-user-by-name method, and only with admin:users:server_state scope. None otherwise.")
    user_options: Optional[Dict[str, Any]] = Field(default=None, description="User specified options for the user's spawned instance of a single-user server.")
    __properties: ClassVar[List[str]] = ["name", "ready", "stopped", "pending", "url", "progress_url", "full_url", "full_progress_url", "started", "last_activity", "state", "user_options"]

    @field_validator('pending')
    def pending_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['spawn', 'stop']):
            raise ValueError("must be one of enum values ('spawn', 'stop')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Server from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if full_url (nullable) is None
        # and model_fields_set contains the field
        if self.full_url is None and "full_url" in self.model_fields_set:
            _dict['full_url'] = None

        # set to None if full_progress_url (nullable) is None
        # and model_fields_set contains the field
        if self.full_progress_url is None and "full_progress_url" in self.model_fields_set:
            _dict['full_progress_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Server from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "ready": obj.get("ready"),
            "stopped": obj.get("stopped"),
            "pending": obj.get("pending"),
            "url": obj.get("url"),
            "progress_url": obj.get("progress_url"),
            "full_url": obj.get("full_url"),
            "full_progress_url": obj.get("full_progress_url"),
            "started": obj.get("started"),
            "last_activity": obj.get("last_activity"),
            "state": obj.get("state"),
            "user_options": obj.get("user_options")
        })
        return _obj


