# coding: utf-8

"""
    JupyterHub REST API

    The REST API for JupyterHub. <a href=\"./\">Return to JupyterHub documentation</a>. 

    The version of the OpenAPI document: 5.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.paginated_list import PaginatedList

class TestPaginatedList(unittest.TestCase):
    """PaginatedList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedList:
        """Test PaginatedList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedList`
        """
        model = PaginatedList()
        if include_optional:
            return PaginatedList(
                items = [
                    None
                    ],
                pagination = openapi_client.models.pagination.Pagination(
                    total = 1.337, 
                    limit = 1.337, 
                    offset = 1.337, 
                    next = openapi_client.models.pagination_next.Pagination_next(
                        offset = 1.337, 
                        limit = 1.337, 
                        url = '', ), )
            )
        else:
            return PaginatedList(
        )
        """

    def testPaginatedList(self):
        """Test PaginatedList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
