# coding: utf-8

"""
    JupyterHub REST API

    The REST API for JupyterHub. <a href=\"./\">Return to JupyterHub documentation</a>. 

    The version of the OpenAPI document: 5.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_share_code200_response import PostShareCode200Response

class TestPostShareCode200Response(unittest.TestCase):
    """PostShareCode200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostShareCode200Response:
        """Test PostShareCode200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostShareCode200Response`
        """
        model = PostShareCode200Response()
        if include_optional:
            return PostShareCode200Response(
                server = openapi_client.models.shared_server.SharedServer(
                    name = '', 
                    url = '', 
                    full_url = '', 
                    ready = True, 
                    user = openapi_client.models.shared_server_user.SharedServer_user(
                        name = '', ), ),
                scopes = [
                    ''
                    ],
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                code = 'abc123',
                accept_url = '/hub/accept-share?code=abc123',
                full_accept_url = 'https://hub.example.org/hub/accept-share?code=abc123'
            )
        else:
            return PostShareCode200Response(
        )
        """

    def testPostShareCode200Response(self):
        """Test PostShareCode200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
