# coding: utf-8

"""
    JupyterHub REST API

    The REST API for JupyterHub. <a href=\"./\">Return to JupyterHub documentation</a>. 

    The version of the OpenAPI document: 5.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_user_tokens200_response import GetUserTokens200Response

class TestGetUserTokens200Response(unittest.TestCase):
    """GetUserTokens200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUserTokens200Response:
        """Test GetUserTokens200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUserTokens200Response`
        """
        model = GetUserTokens200Response()
        if include_optional:
            return GetUserTokens200Response(
                api_tokens = [
                    openapi_client.models.token.Token(
                        id = '', 
                        user = '', 
                        service = '', 
                        roles = [
                            ''
                            ], 
                        scopes = [
                            ''
                            ], 
                        note = '', 
                        created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_activity = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        session_id = '', )
                    ]
            )
        else:
            return GetUserTokens200Response(
        )
        """

    def testGetUserTokens200Response(self):
        """Test GetUserTokens200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
