# coding: utf-8

"""
    JupyterHub REST API

    The REST API for JupyterHub. <a href=\"./\">Return to JupyterHub documentation</a>. 

    The version of the OpenAPI document: 5.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pagination_next import PaginationNext

class TestPaginationNext(unittest.TestCase):
    """PaginationNext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginationNext:
        """Test PaginationNext
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginationNext`
        """
        model = PaginationNext()
        if include_optional:
            return PaginationNext(
                offset = 1.337,
                limit = 1.337,
                url = ''
            )
        else:
            return PaginationNext(
        )
        """

    def testPaginationNext(self):
        """Test PaginationNext"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
