# coding: utf-8

"""
    JupyterHub REST API

    The REST API for JupyterHub. <a href=\"./\">Return to JupyterHub documentation</a>. 

    The version of the OpenAPI document: 5.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_delete_group(self) -> None:
        """Test case for delete_group

        Delete a group
        """
        pass

    def test_delete_group_shared_server(self) -> None:
        """Test case for delete_group_shared_server

        Leave a share (group)
        """
        pass

    def test_delete_group_users(self) -> None:
        """Test case for delete_group_users

        Remove users from a group 
        """
        pass

    def test_delete_share_code(self) -> None:
        """Test case for delete_share_code

        Revoke share code
        """
        pass

    def test_delete_shares_server(self) -> None:
        """Test case for delete_shares_server

        Revoke all shared access
        """
        pass

    def test_delete_user(self) -> None:
        """Test case for delete_user

        Delete a user
        """
        pass

    def test_delete_user_server(self) -> None:
        """Test case for delete_user_server

        Stop a user's server
        """
        pass

    def test_delete_user_server_name(self) -> None:
        """Test case for delete_user_server_name

        Stop a user's named server
        """
        pass

    def test_delete_user_shared_server(self) -> None:
        """Test case for delete_user_shared_server

        Leave a shared server 
        """
        pass

    def test_delete_user_token(self) -> None:
        """Test case for delete_user_token

        Delete (revoke) a token by id
        """
        pass

    def test_get_api(self) -> None:
        """Test case for get_api

        Get JupyterHub version
        """
        pass

    def test_get_auth_cookie(self) -> None:
        """Test case for get_auth_cookie

        Identify a user from a cookie
        """
        pass

    def test_get_auth_token(self) -> None:
        """Test case for get_auth_token

        Identify a user or service from an API token
        """
        pass

    def test_get_current_user(self) -> None:
        """Test case for get_current_user

        Get current user
        """
        pass

    def test_get_group(self) -> None:
        """Test case for get_group

        Get a group by name
        """
        pass

    def test_get_group_shared(self) -> None:
        """Test case for get_group_shared

        List servers shared with group
        """
        pass

    def test_get_group_shared_server(self) -> None:
        """Test case for get_group_shared_server

        Get group's shared access
        """
        pass

    def test_get_groups(self) -> None:
        """Test case for get_groups

        List groups
        """
        pass

    def test_get_info(self) -> None:
        """Test case for get_info

        Get detailed info about JupyterHub
        """
        pass

    def test_get_oauth_authorize(self) -> None:
        """Test case for get_oauth_authorize

        OAuth 2.0 authorize endpoint
        """
        pass

    def test_get_proxy(self) -> None:
        """Test case for get_proxy

        Get the proxy's routing table
        """
        pass

    def test_get_service(self) -> None:
        """Test case for get_service

        Get a service by name
        """
        pass

    def test_get_services(self) -> None:
        """Test case for get_services

        List services
        """
        pass

    def test_get_share_codes_owner(self) -> None:
        """Test case for get_share_codes_owner

        List share codes by owner
        """
        pass

    def test_get_share_codes_server(self) -> None:
        """Test case for get_share_codes_server

        List share codes
        """
        pass

    def test_get_shares_owner(self) -> None:
        """Test case for get_shares_owner

        List shares by owner
        """
        pass

    def test_get_shares_server(self) -> None:
        """Test case for get_shares_server

        List server shares
        """
        pass

    def test_get_user(self) -> None:
        """Test case for get_user

        Get a user by name
        """
        pass

    def test_get_user_shared(self) -> None:
        """Test case for get_user_shared

        List servers shared with user
        """
        pass

    def test_get_user_shared_server(self) -> None:
        """Test case for get_user_shared_server

        Get user's shared access to server 
        """
        pass

    def test_get_user_token(self) -> None:
        """Test case for get_user_token

        Get one token
        """
        pass

    def test_get_user_tokens(self) -> None:
        """Test case for get_user_tokens

        List tokens for the user
        """
        pass

    def test_get_users(self) -> None:
        """Test case for get_users

        List users
        """
        pass

    def test_patch_proxy(self) -> None:
        """Test case for patch_proxy

        Notify the Hub about a new proxy
        """
        pass

    def test_patch_shares_server(self) -> None:
        """Test case for patch_shares_server

        Revoke shared access
        """
        pass

    def test_patch_user(self) -> None:
        """Test case for patch_user

        Modify a user
        """
        pass

    def test_post_auth_token(self) -> None:
        """Test case for post_auth_token

        Request a new API token
        """
        pass

    def test_post_group(self) -> None:
        """Test case for post_group

        Create a group
        """
        pass

    def test_post_group_users(self) -> None:
        """Test case for post_group_users

        Add users to a group
        """
        pass

    def test_post_oauth_token(self) -> None:
        """Test case for post_oauth_token

        Request an OAuth2 token
        """
        pass

    def test_post_proxy(self) -> None:
        """Test case for post_proxy

        Force the Hub to sync with the proxy
        """
        pass

    def test_post_share_code(self) -> None:
        """Test case for post_share_code

        Issue share code
        """
        pass

    def test_post_shares_server(self) -> None:
        """Test case for post_shares_server

        Grant shared access
        """
        pass

    def test_post_shutdown(self) -> None:
        """Test case for post_shutdown

        Shutdown the Hub
        """
        pass

    def test_post_user(self) -> None:
        """Test case for post_user

        Create a single user
        """
        pass

    def test_post_user_activity(self) -> None:
        """Test case for post_user_activity

        Notify Hub of activity for a given user
        """
        pass

    def test_post_user_server(self) -> None:
        """Test case for post_user_server

        Start a user's single-user notebook server
        """
        pass

    def test_post_user_server_name(self) -> None:
        """Test case for post_user_server_name

        Start a user's named server
        """
        pass

    def test_post_user_tokens(self) -> None:
        """Test case for post_user_tokens

        Create a new token for the user
        """
        pass

    def test_post_users(self) -> None:
        """Test case for post_users

        Create multiple users
        """
        pass

    def test_put_group_properties(self) -> None:
        """Test case for put_group_properties

        Set group properties
        """
        pass


if __name__ == '__main__':
    unittest.main()
