# coding: utf-8

"""
    JupyterHub REST API

    The REST API for JupyterHub. <a href=\"./\">Return to JupyterHub documentation</a>. 

    The version of the OpenAPI document: 5.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_user_shared200_response import GetUserShared200Response

class TestGetUserShared200Response(unittest.TestCase):
    """GetUserShared200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUserShared200Response:
        """Test GetUserShared200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUserShared200Response`
        """
        model = GetUserShared200Response()
        if include_optional:
            return GetUserShared200Response(
                items = [
                    openapi_client.models.share_code.ShareCode(
                        server = openapi_client.models.shared_server.SharedServer(
                            name = '', 
                            url = '', 
                            full_url = '', 
                            ready = True, 
                            user = openapi_client.models.shared_server_user.SharedServer_user(
                                name = '', ), ), 
                        scopes = [
                            ''
                            ], 
                        id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                pagination = openapi_client.models.pagination.Pagination(
                    total = 1.337, 
                    limit = 1.337, 
                    offset = 1.337, 
                    next = openapi_client.models.pagination_next.Pagination_next(
                        offset = 1.337, 
                        limit = 1.337, 
                        url = '', ), )
            )
        else:
            return GetUserShared200Response(
        )
        """

    def testGetUserShared200Response(self):
        """Test GetUserShared200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
