# coding: utf-8

"""
    JupyterHub REST API

    The REST API for JupyterHub. <a href=\"./\">Return to JupyterHub documentation</a>. 

    The version of the OpenAPI document: 5.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_user_activity_request import PostUserActivityRequest

class TestPostUserActivityRequest(unittest.TestCase):
    """PostUserActivityRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostUserActivityRequest:
        """Test PostUserActivityRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostUserActivityRequest`
        """
        model = PostUserActivityRequest()
        if include_optional:
            return PostUserActivityRequest(
                last_activity = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                servers = openapi_client.models.post_user_activity_request_servers.post_user_activity_request_servers(
                    <server_name> = openapi_client.models.post_user_activity_request_servers__server_name_.post_user_activity_request_servers__server_name_(
                        last_activity = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), )
            )
        else:
            return PostUserActivityRequest(
        )
        """

    def testPostUserActivityRequest(self):
        """Test PostUserActivityRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
