# coding: utf-8

"""
    JupyterHub REST API

    The REST API for JupyterHub. <a href=\"./\">Return to JupyterHub documentation</a>. 

    The version of the OpenAPI document: 5.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.delete_group_users_request import DeleteGroupUsersRequest

class TestDeleteGroupUsersRequest(unittest.TestCase):
    """DeleteGroupUsersRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteGroupUsersRequest:
        """Test DeleteGroupUsersRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteGroupUsersRequest`
        """
        model = DeleteGroupUsersRequest()
        if include_optional:
            return DeleteGroupUsersRequest(
                users = [
                    ''
                    ]
            )
        else:
            return DeleteGroupUsersRequest(
        )
        """

    def testDeleteGroupUsersRequest(self):
        """Test DeleteGroupUsersRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
