# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/08_Atomistics_Two_Point_Statistics.ipynb (unless otherwise specified).

__all__ = ['CrystalStructure']

# Cell
#export
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib as mpl
from scipy.spatial import ConvexHull, Delaunay
import scipy.ndimage as ndimg
from mpl_toolkits.mplot3d import Axes3D
from app.services.apps.image_analysis.workflow_widgets.utils.Visualizations import Visualize_Two_Point_Statistics
from app.services.apps.image_analysis.workflow_widgets.utils.Utilities import Counts, Attempts, VariableCheck, accumulate_local_state_FFTs
from pymatgen.util.coord import *
from pymatgen.core import Structure as st
from pymatgen.core.operations import *
from pymatgen.core import *
from pymatgen.core.periodic_table import Species, Element
from pymatgen.symmetry.analyzer import *
from pymatgen.transformations.standard_transformations import *
from pymatgen.analysis.local_env import *
import warnings
import time

# Cell
class CrystalStructure(object):
    def __init__(self, filename, rmax_stats = 8, voxels_per_ang = 5, radius_tol = 0.9, standardize_option = "max_z"):
        '''
        Initialize the base object to store voxelized crystal structure.
        '''

        self.rmax_stats = rmax_stats
        self.radius_tol = radius_tol
        self.voxels_per_ang = voxels_per_ang
        self.standardize_option = standardize_option
        self._spheres = {}
        structure = st.from_file(filename)
        self.structure = SpacegroupAnalyzer(structure).get_conventional_standard_structure()
        self.species_identifier, self.atomic_radii = self._get_species_identifier()
        self.translation, self.rotation = self.get_trans_rot_transforms(self.structure,
                                                                        standardize_option = self.standardize_option)
        if self.translation and self.rotation:
            self.structure.apply_operation(self.translation)
            self.structure.apply_operation(self.rotation)


        self.domain_translation = self.__translate_pos_coords()
        self.structure.apply_operation(self.domain_translation)

        self.extended_sites = self._get_extended_sites()
        self.voxelized_m_sp_atoms, self.voxelized_m_sq_atoms, self.unit_cell_hull = \
                                                                                self.get_m_sp_m_sq_atoms(voxels_per_ang \
                                                                                = self.voxels_per_ang,
                                                                                rmax_stats = self.rmax_stats,
                                                                                radius_tol = self.radius_tol)

        species = list(set(self.structure.species))
        self._attributes_list = None
        self.m_sp, self.m_sq = None, None
        self.tpt_stats = None

    def _get_species_identifier(self, attributes_file = "elem_and_prop.csv"):
        '''
        Function to map each species to an integer identifier (E.g. Species A: 1, Species B: 2, etc.)
        '''
        species = list(set(self.structure.species))
        species_dict = {species[i].symbol : i + 1 for i in range(len(species))}
        
        if attributes_file.endswith("csv"):
            radius_dict = pd.read_csv(attributes_file, header = 0) \
                [['Element', 'crystal_radius']].set_index('Element').to_dict()['crystal_radius']
        elif attributes_file.endswith("parquet"):
            radius_dict = pd.read_parquet(attributes_file) \
                [['Element', 'crystal_radius']].set_index('Element').to_dict()['crystal_radius']

        radii = {s.symbol : radius_dict[s.symbol] for s in species}
        #radii = {s.symbol : s.atomic_radius for s in species}
        return species_dict, radii

    def get_trans_rot_transforms(self, structure, standardize_option = "max_z"):
        """
        Function to standardize the coordinate system for the crystal structure.
        """
        if not standardize_option:
            return None, None

        elif standardize_option == "max_z":
            #Standardizing such that an atom of the species with max atomic weight is at origin. The perpendicular segments along the plane formed by the first two nearest neighbors and the cross product of these vectors form the new coordinate system.
            mod_structure = structure.copy()
            atom_species = mod_structure.species
            if len(atom_species)<=3:
                while len(mod_structure)<8:
                    mod_structure.make_supercell(2)
            #Selecting atom at origin and determining idx
            atom_species = mod_structure.species
            z_values = [atom.Z for atom in atom_species]
            new_origin_idx = np.argmax(z_values)
            new_origin_site = mod_structure.sites[new_origin_idx]
            translation = SymmOp.from_rotation_and_translation(translation_vec = -new_origin_site.coords)

            NN_finder = CrystalNN()
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                nn_data = NN_finder.get_nn_info(mod_structure,new_origin_idx)
            tau_1 = nn_data[0]['site'].coords - new_origin_site.coords

            for nn2 in nn_data[1:]:
                if int(get_angle(tau_1,nn2['site'].coords - new_origin_site.coords)) != 180:
                    tau_2 = nn2['site'].coords - new_origin_site.coords
                    break
            else:
                print("Standardization not possible because atoms were collinear. Returning original structure.")
                return SpacegroupAnalyzer(mod_structure).get_conventional_standard_structure()
            #Gram-Schmidt procedure
            u_1 = tau_1
            u_2 = tau_2 - ((tau_2.dot(tau_1)) / (tau_1.dot(tau_1))) * tau_1
            u_3 = np.cross(u_1,u_2)
            e_1 = u_1/np.linalg.norm(u_1)
            e_2 = u_2/np.linalg.norm(u_2)
            e_3 = u_3/np.linalg.norm(u_3)
            #Creating the rotation transform
            rot_mat = np.vstack([e_1, e_2, e_3]).T
            rotation = SymmOp.from_rotation_and_translation(rotation_matrix = rot_mat)
            return translation, rotation

    def __translate_pos_coords(self):
        '''
        Function to get transform for translation of atoms to allow entire domain to fit in the positive quadrant
        '''
        min_x, min_y, min_z = 0, 0, 0
        for s in self.structure.sites:
            x,y,z = s.coords
            tol = self.radius_tol * self.atomic_radii[s.specie.symbol] + 1/(self.voxels_per_ang)
            min_x = min(min_x, x - tol)
            min_y = min(min_y, y - tol)
            min_z = min(min_z, z - tol)
        domain_trans_vec = np.array([- min_x,- min_y,- min_z])
        domain_trans = SymmOp.from_rotation_and_translation(translation_vec = domain_trans_vec)
        return domain_trans

    def get_m_sp_m_sq_atoms(self, voxels_per_ang = 5, rmax_stats = 6, radius_tol = 0.95):
        '''
        Container function to generate and return both microstructure functions.
        '''
        structure = self.structure
        species = structure.species

        max_radius = max([self.atomic_radii[s.symbol] for s in species])
        grid_side = int(np.ceil((max(structure.lattice.a, structure.lattice.b, structure.lattice.c) + \
                                 max_radius + rmax_stats) * voxels_per_ang))
        grid_size = [grid_side] * 3
        m_sp_atoms, unit_cell_hull = self.__get_m_sp_atoms(self.structure, grid_size)
        m_sq_atoms = self.__get_m_sq_atoms(self.extended_sites, grid_size)

        return m_sp_atoms, m_sq_atoms, unit_cell_hull

    def __get_m_sp_atoms(self, structure, grid_size):
        '''
        Function to generate the m_sp microstructure field. This field contains a single unit cell in the corner of the domain.
        '''
        m_sp_atoms = self.create_voxelized_structure(structure, grid_size, ms_type = 'm_sp')
        hull = self._unit_cell_mask(grid_size,m_sp_atoms)
        m_sp_atoms = np.multiply(hull, m_sp_atoms)
        return m_sp_atoms, hull

    def __get_m_sq_atoms(self, extended_sites, grid_size):
        '''
        Function to generate the m_sq microstructure field. This field contains the unit cell from m_sp tiled throughout the domain.
        '''
        m_sq_atoms = self.create_voxelized_structure(extended_sites, grid_size, ms_type = 'm_sq')
        return m_sq_atoms


    def _unit_cell_mask(self, grid_size, m_sp_atoms):
        '''
        This function yields the convex hull of the unit cell to yield an accurate count of the number of voxels present within the unit cell.
        '''
        #Finding the convex hull around the set of atoms using Delaunay triangulation
        mask = np.zeros(grid_size)
        mask[m_sp_atoms > 0] = 1
        points = np.transpose(np.where(mask))
        hull = ConvexHull(points)
        deln = Delaunay(points[hull.vertices])
        idx = np.stack(np.indices(mask.shape), axis = -1)
        out_idx = np.nonzero(deln.find_simplex(idx) + 1)
        out_img = np.zeros(mask.shape)
        out_img[out_idx] = 1
        return out_img

    def _create_sphere_kernel(self):
        '''
        This function generates voxelized spheres with radius corresponding to the species present in the system.
        '''

        for symbol, identifier in self.species_identifier.items():
            rad = int(np.floor(np.round(self.atomic_radii[symbol] * self.voxels_per_ang,3)))
            sphere_size = [rad * 2] * 3
            ind_sph_0,ind_sph_1, ind_sph_2 = np.indices((sphere_size[0], sphere_size[1], sphere_size[2]))
            ac = sphere_size[0] // 2, sphere_size[1] // 2, sphere_size[2] // 2
            #Depicting the sphere as a binary mask multiplied by the identifier of the species.
            self._spheres[identifier] = (((ind_sph_0 - ac[0]) ** 2 + \
                    (ind_sph_1 - ac[1]) ** 2 + \
                    (ind_sph_2 - ac[2]) ** 2) <= (self.radius_tol * rad) ** 2) * identifier

    def create_voxelized_structure(self, atoms, domain_size, ms_type):
        '''
        This function creates the voxelized domain for both m_sp and m_sq by convolving the atom centers with the spheres corresponding to each species.
        '''
        self._create_sphere_kernel()
        if ms_type == "m_sp":
            assert(isinstance(atoms, st))
            grid_size = domain_size
            voxelized_structure = np.zeros(grid_size)
            species_ct = 1
            species_grid = {}
            #Plotting atom centers by looping through all sites in the unit cell.
            for i,s in enumerate(atoms.sites):
                rad = int(np.floor(np.round(self.atomic_radii[s.specie.symbol] * self.voxels_per_ang,3)))
                xc = int(np.rint(s.x * self.voxels_per_ang))
                yc = int(np.rint(s.y * self.voxels_per_ang))
                zc = int(np.rint(s.z * self.voxels_per_ang))

                atom_center = [xc,yc,zc]

                identifier = self.species_identifier[s.specie.symbol]
                if species_grid.get(identifier) is None:
                    species_grid[identifier] = np.zeros(grid_size)

                #Setting atom center voxel to 1
                species_grid[identifier][xc][yc][zc] = 1

            #Convolving the atom centers with the spherical kernel
            for ident in self._spheres.keys():
                species_grid[ident] = ndimg.convolve(species_grid[ident],
                                                              self._spheres[ident], mode='constant')
                voxelized_structure += species_grid[ident]

        elif ms_type == "m_sq":
            assert(isinstance(atoms, list))
            species = self.structure.species
            max_radius = max([self.atomic_radii[s.symbol] for s in species])
            padding = domain_size[0]
            grid_size = [d + 2 * padding for d in domain_size]
            voxelized_structure = np.zeros(grid_size)
            species_ct = 1
            t0 = time.time()

            species_grid = {}

            #Plotting atom centers by looping through all sites in self.extended_sites
            for i, s in enumerate(self.extended_sites):
                rad = int(np.floor(np.round(self.atomic_radii[s.specie.symbol] * self.voxels_per_ang,3)))
                xc = int(np.rint(s.x * self.voxels_per_ang))
                yc = int(np.rint(s.y * self.voxels_per_ang))
                zc = int(np.rint(s.z * self.voxels_per_ang))

                #Adding the padding to ensure edge atoms (with centers outside immediate domain) are still accounted for in the final chosen domain.
                xc += padding
                yc += padding
                zc += padding

                if xc >= grid_size[0] or yc >= grid_size[1] or zc >= grid_size[2]:
                    continue
                elif xc < 0 or yc < 0 or zc < 0:
                    continue

                atom_center = [xc,yc,zc]

                identifier = self.species_identifier[s.specie.symbol]
                if species_grid.get(identifier) is None:
                    species_grid[identifier] = np.zeros(grid_size)

                #Setting atom center voxel to 1
                species_grid[identifier][xc][yc][zc] = 1

            #Convolving the atom centers with the spherical kernel
            for ident in self._spheres.keys():
                species_grid[ident] = ndimg.convolve(species_grid[ident],
                                                              self._spheres[ident], mode='constant')
                voxelized_structure += species_grid[ident]
            voxelized_structure = voxelized_structure[padding:-padding, padding:-padding, padding:-padding]
            t1 = time.time()
        return voxelized_structure

    def _get_extended_sites(self):
        '''
        This function obtains the coordinates of extended sites beyond the unit cell in m_sp. It is used for finding atom centers for all atoms in m_sq outside the original unit cell.
        '''
        species = self.structure.species
        max_radius = max([self.atomic_radii[s.symbol] for s in species])
        search_radius = max(self.structure.lattice.a,
                                    self.structure.lattice.b,
                                    self.structure.lattice.c) + 2 * max_radius + self.rmax_stats * 3

        extended_sites = self.structure.get_sites_in_sphere(pt = np.array([0,0,0]), r = search_radius)
        return extended_sites

    def fit_attributes(self, attributes_file = "elem_and_prop.csv"):
        '''
        This function is used to fit chemical attributes to each species. See file "elem_and_prop.csv" for an example set of species and attributes.
        '''
        if attributes_file.endswith("csv"):
            attributes_df = pd.read_csv(attributes_file, header = 0).drop("crystal_radius", axis = 1)
        elif attributes_file.endswith("parquet"):
            attributes_df = pd.read_parquet(attributes_file).drop("crystal_radius", axis = 1)

        all_attributes_dict = attributes_df.set_index('Element').T.to_dict()
        attributes_dict = {k:v for (k,v) in all_attributes_dict.items() if k in self.species_identifier}

        attributes_list = []
        for k in attributes_dict.keys():
            attr_list = list(attributes_dict[k].values())
            attributes_list.append(attr_list)
        self._attributes_list = np.array(attributes_list)

    def compute_ms_function(self):
        '''
        This function computes the microstructure functions by fitting the attributes to the voxelized representations of each field.
        '''
        if self._attributes_list is None:
            print("No attributes provided. Please fit attributes before computing MS function.")
            return

        attributes_list = self._attributes_list
        num_attributes = len(attributes_list[0])
        ms_function_shape = [num_attributes+1] + list(self.voxelized_m_sp_atoms.shape)

        voxelized_m_sp = self.voxelized_m_sp_atoms
        voxelized_m_sq = self.voxelized_m_sq_atoms

        m_sp = np.zeros(ms_function_shape)
        m_sq = np.zeros(ms_function_shape)

        for i, species in enumerate(attributes_list):
            for j in range(len(m_sp)-1):
                m_sp[j][voxelized_m_sp == (i+1)] = attributes_list[i][j]
                m_sq[j][voxelized_m_sq == (i+1)] = attributes_list[i][j]

        #Filling entries for void state ms function
        m_sp[-1][(self.unit_cell_hull == 1) & (voxelized_m_sp == 0)] = 1
        m_sq[-1][voxelized_m_sq == 0] = 1

        self.m_sp = m_sp
        self.m_sq = m_sq

    def compute_stats(self, column = -1):
        '''
        This function computes the 2-point statistics of the structure along a specified column.
        '''
        if self.m_sp is None or self.m_sq is None:
            print("MS function has not been created.")
            return

        if column > len(self.m_sq):
            raise IndexError("Column specified is larger than the length of the microstructure functions")

        tpt_stats = np.zeros(self.m_sp.shape)

        denominator = np.count_nonzero(self.unit_cell_hull)
        for i in range(len(tpt_stats)):
            tpt_stats[i] = np.round(np.real(np.fft.ifftn(np.multiply(np.conj(np.fft.fftn(self.m_sp[column])),\
                                                                    np.fft.fftn(self.m_sq[i]) \
                                                                   ))) / denominator,3)
        #Cutting off the grid of 2pt stats based on rmax_stats
        cutoff = int(self.rmax_stats * self.voxels_per_ang)
        self.tpt_stats = tpt_stats[:, :cutoff, :cutoff, :cutoff]