# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03_Chord_Length_Distribution.ipynb (unless otherwise specified).

__all__ = ['ChordLengthDistribution']

# Cell
#export
import numpy as np
import matplotlib.pyplot as plt
from skimage import transform
from scipy.ndimage import correlate
from scipy.interpolate import griddata
from numpy import pi
import matplotlib.colors as colors
from app.services.apps.image_analysis.workflow_widgets.utils.Visualizations import Visualize_ARCLD, Visualize_CLD, Visualize_ARCLD_Angle

# Cell
class ChordLengthDistribution(object):

    def __init__(self, M, num_ls = None, cutoff = None, ang_int = 90, periodicity = False, \
                 coarsening = 1, resolution = 1, resolution_unit = None, consolidate = False):

        # Adding the resolution information to class instance
        self.resolution = resolution
        self.resolution_unit = resolution_unit

        # Consolidation of CLDs over local states (it is mostly used for grain size distributions)
        self.consolidate = consolidate

        # Setting up the peridocity
        if periodicity is False:
            self.periodicity = periodicity
        elif periodicity is True:
            raise ValueError('Chord length distribution has not been implemented for periodic microstructures yet')
        else:
            raise ValueError('Periodicity must be either True or False.')

        # 2-D images
        if M.ndim == 2:

            # Specifying cutoff based on cutoff and resolution values
            n_x = M.shape[1]; n_y = M.shape[0]
            max_cutoff_cell = np.ceil(np.sqrt((n_y - 2) ** 2 + (n_x - 2) ** 2)).astype('int')  # Maximum possible cutoff
            if cutoff is None or cutoff > max_cutoff_cell * resolution:
                self.cutoff_cell = max_cutoff_cell
                self.cutoff = max_cutoff_cell * resolution
            else:
                self.cutoff_cell = np.ceil(cutoff / resolution).astype(int)
                self.cutoff = self.cutoff_cell * self.resolution

            # Setting the angular intervals
            if ang_int >= 90 or ang_int <= 0 or ang_int is None:
                ang_int = 90
            else:
                ang_int = ang_int

            # List of angles based on the angular interval (i.e. ang_int)
            # The angle list is selected as only 0 and 90 for periodic cases. Angularly resolved
            # ARCLDs for periodic case will be implemented later.
            if self.periodicity:
                ang_list = np.arange(0,180, step = 90)
            elif not self.periodicity:
                ang_list = np.arange(0, 180, step = ang_int)
            self.theta = ang_list

            # Indices of local states
            if num_ls is None:
                num_ls = np.max(M) + 1
            num_ls = num_ls.astype(int)

            # Initialization of CLD matrix
            self.ARCLD = np.zeros((num_ls, max_cutoff_cell, ang_list.__len__()))
            self.Chords = np.zeros((num_ls, max_cutoff_cell, ang_list.__len__()))

            # Calculation of CLDs for a every angle in ang_list (i.e. ARCLD)
            for it, ang in enumerate(ang_list):

                # Rotation of the image
                if ang == 0:
                    Mr = M
                elif ang == 90:
                    Mr = M.T
                else:
                    Mr = transform.rotate(M, -1 * ang, order = 0, resize = True, mode = 'constant', \
                                          preserve_range = True)  # Rotation

                # Filter to find the chord ends
                k = np.array([-1, 1, 0])[None,:]

                # Convolution of the image to calculate
                Mc = correlate(Mr, weights = k, mode = 'nearest', output = 'float')
                Mc = (Mc != 0).astype(float)

                # Coordinates of the left ends of chords
                _, J = np.meshgrid(np.arange(Mc.shape[0]), np.arange(Mc.shape[1]), indexing = 'ij')
                J[Mc == 0] = 0  # Marking the inner section of chords

                # Shifting the coordinates to the end and finding the chord lengths
                d = np.argsort(J.astype(float), axis = 1)
                Ml = np.take_along_axis(Mr, d, axis=1)
                Ml = np.roll(Ml, 1, axis = 1)  # Associating local states with chords
                J = np.take_along_axis(J.astype(float), d, axis=1)
                J[J == 0] = np.nan
                chords = np.diff(J, axis = 1)  # Chords
                chords[np.isnan(chords)] = 0 # Extracting the valid entries

                # Distributing chords to their respective local states
                for h in range(num_ls):
                    self.Chords[h, :, it] = np.bincount((chords * (Ml[:,1:] == h)).flatten().astype(int), \
                                                  minlength = max_cutoff_cell + 1)[1:max_cutoff_cell + 1]

            # Chord weights used for normalization
            chord_weights = np.tile(np.arange(1, max_cutoff_cell + 1)[None,:,None], \
                                    (self.Chords.shape[0], 1, self.Chords.shape[2]))

            # Weighted chords
            self.ARCLD = chord_weights * self.Chords

            # CLD (i.e. isotropic CLD accumulated from different angles)
            self.CLD = np.sum(self.ARCLD, axis = 2)

            # Consolidation of local states
            if self.consolidate:
                self.ARCLD = np.sum(self.ARCLD, axis = 0)[None,...]
                self.CLD = np.sum(self.CLD, axis = 0)[None,...]

            # Coarsening
            if coarsening is None or coarsening <= 1:
                self.z = self.resolution * np.arange(1, self.ARCLD.shape[1] + 1)
                self.coarsening = 1
                self.cutoff_cell_coarse = self.cutoff_cell
            else:
                if coarsening > 20:
                    coarsening = 20
                self.coarsening = coarsening
                if np.mod(self.ARCLD.shape[1], self.coarsening) != 0:
                    coarsening_pad = self.coarsening - np.mod(self.ARCLD.shape[1], self.coarsening)
                    self.ARCLD = np.pad(self.ARCLD,((0,0),(0,coarsening_pad),(0,0)))
                    self.CLD = np.pad(self.CLD,((0,0),(0, coarsening_pad)))
                self.ARCLD = self.ARCLD.reshape(self.ARCLD.shape[0], -1, self.coarsening, self.ARCLD.shape[2])
                self.ARCLD = np.sum(self.ARCLD, axis = 2)
                self.CLD = self.CLD.reshape(self.CLD.shape[0], -1, self.coarsening)
                self.CLD = np.sum(self.CLD, axis = 2)
                if np.mod(self.cutoff_cell, self.coarsening) != 0:
                    self.cutoff_cell_coarse = (self.cutoff_cell + np.mod(self.cutoff_cell, self.coarsening)) // self.coarsening
                else:
                    self.cutoff_cell_coarse = self.cutoff_cell // self.coarsening
                self.z = self.resolution * np.arange(1, self.ARCLD.shape[1] + 1)
                self.z = (self.z * self.coarsening) - self.resolution * (self.coarsening - 1) / 2

            # Polar Normalization for ARCLD
            theta, r = np.meshgrid(np.append(ang_list,180) * pi / 180, [*self.z, self.z[-1] + self.z[1] - self.z[0]])
            pol_norm = np.diff( np.diff(0.5 * (r ** 2) * theta , axis = 0) , axis = 1) # Polar normalization matrix
            self.ARCLD = self.ARCLD / \
                         np.sum(self.ARCLD)
            self.ARCLD[np.isnan(self.ARCLD)] = 0

            # Normalization for CLD
            CLD_norm = np.sum(self.CLD)
            self.CLD = self.CLD / CLD_norm
            self.CLD[np.isnan(self.CLD)] = 0

            # Cutoff
            self.ARCLD = self.ARCLD[:,:self.cutoff_cell_coarse,:]
            self.CLD = self.CLD[:,:self.cutoff_cell_coarse]
            self.Chords = self.Chords[:,:self.cutoff_cell_coarse,:]
            self.z = self.z[:self.cutoff_cell_coarse]


        elif M.ndim == 3:  # 3-D microstructures
            raise ValueError('3-D CLD calculations will be implemented later.')

    # Visualization of ARCLD
    def visualize_ARCLD(self, local_state, ax = None, thumbnail = False, imageloc = None, colorbar_lims = None, \
                        interactive = False, fig = None, fig_height = 5, return_fig = False, dpi = 80):

        # Ignoring local state parameter if CLDs are consolidated for polycrystal case
        if self.consolidate:
            local_state = 0

        params = {'ax': ax, 'fig': fig, 'interactive': interactive, 'fig_height': fig_height, \
                  'imageloc': imageloc, 'return_fig': return_fig, 'thumbnail': thumbnail, \
                  'resolution': self.resolution, 'resolution_unit': self.resolution_unit, \
                  'colorbar_lims': colorbar_lims, 'coarsening': self.coarsening}

        # Calling TwoPoint visualization in feature_engineering Visualization module as method
        fig_out = Visualize_ARCLD(self.ARCLD, self.theta[1], local_state, **params)

        # Return figure (for platform purposes)
        if return_fig:
            return fig_out


    # Method for visualization of CLD
    def visualize_CLD(self, local_state = 0, ax = None, thumbnail = False, imageloc = None,
                      interactive = False, fig = None, fig_height = 5, y_lims = None, \
                      return_fig = False):

        # Ignoring local state parameter if CLDs are consolidated for polycrystal case
        if self.consolidate:
            local_state = 0

        params = {'ax': ax, 'fig': fig, 'interactive': interactive, 'fig_height': fig_height, \
                  'imageloc': imageloc, 'return_fig': return_fig, 'thumbnail': thumbnail, \
                  'resolution': self.resolution, 'resolution_unit': self.resolution_unit, \
                  'y_lims': y_lims, 'coarsening': self.coarsening}

        # Calling TwoPoint visualization in feature engineering visualizations module as method
        fig_out = Visualize_CLD(self.CLD, local_state, **params)

        # Return figure (for platform purposes)
        if return_fig:
            return fig_out


    # Method for visualization of CLD
    def visualize_ARCLD_Angle(self, angles, local_state = 0, ax = None, thumbnail = False, \
                              imageloc = None, interactive = False, fig = None, fig_height = 5, \
                              y_lims = None, return_fig = False):

        # Ignoring local state parameter if CLDs are consolidated for polycrystal case
        if self.consolidate:
            local_state = 0

        params = {'ax': ax, 'fig': fig, 'interactive': interactive, 'fig_height': fig_height, \
                  'imageloc': imageloc, 'return_fig': return_fig, 'thumbnail': thumbnail, \
                  'resolution': self.resolution, 'resolution_unit': self.resolution_unit, \
                  'y_lims': y_lims, 'coarsening': self.coarsening}

        # Calling TwoPoint visualization in feature engineering visualizations module as method
        fig_out = Visualize_ARCLD_Angle(self.ARCLD, self.theta[1], local_state, angles, **params)

        # Return figure (for platform purposes)
        if return_fig:
            return fig_out