# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/04_Dimensionality_Reduction.ipynb (unless otherwise specified).

__all__ = ['PrincipalComponentAnalysis', 'HighDimPrincipalComponentAnalysis', 'BigDataPrincipalComponentAnalysis']

# Cell
#export
from app.services.apps.image_analysis.workflow_widgets.utils.Visualizations import Visualize_PC_Scores
from sklearn.decomposition import PCA
import numbers
from scipy.sparse import issparse
from sklearn.utils.extmath import svd_flip
from sklearn.preprocessing import normalize, StandardScaler
import pandas as pd
import numpy as np
import dask.array as da
from dask_ml.decomposition import PCA as DaskPCA
from dask_ml.preprocessing import StandardScaler as DaskStandardScaler
from app.services.apps.image_analysis.workflow_widgets.utils.Utilities import feature_scaler
import time
import h5py as hf
import os

# Cell
class PrincipalComponentAnalysis(PCA):

    def __init__(self, stat_list, stat_params = None, n_components = 20, svd_solver = 'full', \
                 scale = 'max_variance', save_stat_list = False):

        # Writing the type of scaling as attributed
        self.scale = scale

        # Set n_components to min dimension of full statistics data matrix
        min_dim = np.min(np.hstack(stat_list).shape)
        if n_components > min_dim:
            n_components = min_dim

        # Inheritance of PCA class of sklearn package
        PCA.__init__(self, n_components = n_components, svd_solver = svd_solver)

        # Scaling the features based on user input
        if stat_list.__len__() > 1:
            stat_list, scaling_factors = feature_scaler(stat_list, scale)
            self.scaling_factors = scaling_factors

        # Converting the list of set of statistics to a single data matrix
        stat_list = np.hstack(stat_list)

        # Calculation of PC scores
        self.Scores = self.fit_transform(stat_list)

        # Writing the scaled stat_list as attribute
        if save_stat_list:
            self.scaled_stats = stat_list


    # Method for saving PC scores for later use in model builder
    def save_scores_model_builder(self, trunc_level, save_path, sample_id = None, mat_proc_prop = None, \
                                  averaging = False):

        # Setting the truncation level for PC basis
        if trunc_level > self.Scores.shape[1]:
            trunc_level = self.Scores.shape[1]

        # Preparing feature names of the dataframe
        feature_names = ['PC ' + str(i + 1) for i in range(trunc_level)]

        # Preparing the dataframe of PC scores
        df = pd.DataFrame(self.Scores[:, :trunc_level], columns = feature_names)

        # Writing process parameters/properties to dataframe
        if mat_proc_prop is not None:
            for key in mat_proc_prop.keys():
                if mat_proc_prop[key].shape[0] != self.Scores.shape[0]:
                    raise ValueError('The number of entries in material properties, process conditions '\
                                     'and sample_id must be equal to the number of entries in PC scores '\
                                     '(i.e. the number of microstructures or rows in tabular data)')
                else:
                    df[key] = mat_proc_prop[key]

        # Writing the sample key to dataframe
        if sample_id is not None:

            if sample_id.__len__() != self.Scores.shape[0]:
                raise ValueError('The number of entries in material properties, process conditions '\
                                 'and sample_id must be equal to the number of entries in PC scores '\
                                 '(i.e. the number of microstructures or rows in tabular data)')
            else:
                df['sample_id'] = sample_id
                # Taking the mean of the PC scores, process conditions and properties
                if averaging:
                    df = df.groupby('sample_id').mean()

        # Saving the dataframe to parquet file
        df.to_parquet(save_path) #to_csv(save_path, index = False)


    # Transformation (i.e. projecting new data to the existing PC space)
    def fit_pca(self, new_stat_list):

        # Scale the new_stat_list based on the scaling factors
        if new_stat_list.__len__() > 1:
            # The case with featurewise_variance
            if isinstance(self.scaling_factors, StandardScaler):
                new_stat_list = sc.transform(np.hstack(new_stat_list))
            else:
                for i in range(len(new_stat_list)):
                    new_stat_list[i] = new_stat_list[i] / self.scaling_factors[i]

        # Converting the list of set of statistics to a single data matrix
        new_stat_list = np.hstack(new_stat_list)

        return self.transform(new_stat_list)


    # Visualization of PC scores
    def visualize_scores(self, indices, feature = None, feature_name = None, feature_unit = None, \
                         fig = None, ax = None, return_fig = False):

        params = {'ax': ax, 'fig': fig, 'return_fig': return_fig, 'feature': feature, \
                  'feature_name': feature_name, 'feature_unit': feature_unit}

        # Calling TwoPoint visualization in FeatureEngineeringVisualization module as method
        fig_out = Visualize_PC_Scores(self.Scores, indices, **params)

        # Return figure (for platform purposes)
        if return_fig:
            return fig_out


# Cell
class HighDimPrincipalComponentAnalysis(PCA):
    def __init__(self, stat_list, n_components = 20, scale = 'max_variance'):

        # Set n_components to min dimension of full statistics data matrix
        min_dim = np.min(np.hstack(stat_list).shape)
        if n_components > min_dim:
            n_components = min_dim

        # Inheritance of PCA class of sklearn package
        PCA.__init__(self, n_components = n_components)

        #Scaling the features based on user input
        stat_list, scaling_factors = feature_scaler(stat_list,scale)

        # Converting the list of set of statistics to a single data matrix
        stat_list = np.hstack(stat_list)

        # Calculation of PC scores
        self.Scores = self.fit_transform(stat_list)

    def fit(self, X, y = None):
        """Fit the model with X.
        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
            Training data, where n_samples is the number of samples
            and n_features is the number of features.
        y : Ignored
        Returns
        -------
        self : object
            Returns the instance itself.
        """
        self._fit(X)
        return self

    def fit_transform(self, X, y = None):
        """Fit the model with X and apply the dimensionality reduction on X.
        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
            Training data, where n_samples is the number of samples
            and n_features is the number of features.
        y : Ignored
        Returns
        -------
        X_new : ndarray of shape (n_samples, n_components)
            Transformed values.
        Notes
        -----
        This method returns a Fortran-ordered array. To convert it to a
        C-ordered array, use 'np.ascontiguousarray'.
        """

        U, S, Vt = self._fit(X)
        U = U[:, :self.n_components_]
        return U

    def _fit(self, X):
        """Dispatch to the right submethod depending on the chosen solver."""

        # Raise an error for sparse input.
        # This is more informative than the generic one raised by check_array.
        if issparse(X):
            raise TypeError('PCA does not support sparse input. See '
                            'TruncatedSVD for a possible alternative.')

        X = self._validate_data(X, dtype=[np.float64, np.float32],
                                ensure_2d=True, copy=self.copy)

        # Handle n_components==None
        if self.n_components is None:
            if self.svd_solver != 'arpack':
                n_components = min(X.shape)
            else:
                n_components = min(X.shape) - 1
        else:
            n_components = self.n_components


        # Call fit for transpose trick method
        return self._fit_full(X, n_components)


    def _fit_full(self, X, n_components):
        n_samples, n_features = X.shape
        min_dim = np.min(X.shape)

        if n_components == 'mle':
            if n_samples < n_features:
                raise ValueError("n_components='mle' is only supported "
                                 "if n_samples >= n_features")
        elif not 0 <= n_components <= min(n_samples, n_features):
            raise ValueError("n_components=%r must be between 0 and "
                             "min(n_samples, n_features)=%r with "
                             "svd_solver='full'"
                             % (n_components, min(n_samples, n_features)))
        elif n_components >= 1:
            if not isinstance(n_components, numbers.Integral):
                raise ValueError("n_components=%r must be of type int "
                                 "when greater than or equal to 1, "
                                 "was of type=%r"
                                 % (n_components, type(n_components)))

        # Center data
        self.mean_ = np.mean(X, axis=0)
        X -= self.mean_
        ##################
        #Transpose trick
        # PCA - transpose trick
        M = np.dot(X,X.T)
        e,EV = np.linalg.eigh(M)
        tmp = np.dot(X.T,EV).T
        Vt = tmp[::-1]
        S = np.sqrt(np.abs(e))[::-1]

        Vt /= S[:,np.newaxis]
        U = (X.dot(Vt.T))
        U,Vt = svd_flip(U,Vt)
        ##################
        components_ = Vt

        # Get variance explained by singular values
        explained_variance_ = (S ** 2) / (n_samples - 1)
        total_var = explained_variance_.sum()
        explained_variance_ratio_ = explained_variance_ / total_var
        singular_values_ = S.copy()  # Store the singular values.

        # Compute noise covariance using Probabilistic PCA model
        # The sigma2 maximum likelihood (cf. eq. 12.46)
        if n_components < min(n_features, n_samples):
            self.noise_variance_ = explained_variance_[n_components:].mean()
        else:
            self.noise_variance_ = 0.

        self.n_samples_, self.n_features_ = n_samples, n_features
        self.components_ = components_[:n_components]
        self.n_components_ = n_components
        self.explained_variance_ = explained_variance_[:n_components]
        self.explained_variance_ratio_ = \
            explained_variance_ratio_[:n_components]
        self.singular_values_ = singular_values_[:n_components]
        return U, S, Vt

    def visualize_scores(self, indices, feature = None, feature_name = None, feature_unit = None):
        Visualize_PC_Scores(self.Scores, indices, feature = feature, feature_name = feature_name, \
                        feature_unit = feature_unit, fig = None, fig_height = 5, dpi = 80)

# Cell
class BigDataPrincipalComponentAnalysis(DaskPCA):
#class BigDataPCA(PCA):
    def __init__(self, filename, filepath=os.getcwd(), n_components = 20, svd_solver = 'full',
                 scale='max_variance', pre_scaled=False,save_stat_list=True):

        #Initializing Dask PCA solver
        DaskPCA.__init__(self, n_components = n_components, svd_solver = svd_solver)

        #Storing path and name of hdf5 file from storage.
        self.filepath = filepath
        self.filename = filename
        self.scale_type = scale

        #Determining paths of unscaled and scaled datasets
        self.unscaled_file_path = os.path.join(self.filepath,self.filename+'.hdf5')
        self.scaled_file_path = os.path.join(self.filepath,self.filename+'_'+self.scale_type+'_scaled.hdf5')

        #Validating stats to ensure that each set has the same number of microstructures.
        if not self.__validate_stats():
            raise ValueError('The number of microstructures in each of the stats is different.')

        #Checking if data is already pre-scaled (Flag provided by user)
        if not pre_scaled:
            #Scaling stats based on scale preference.
            scaled_stats = self.compute_scaled_stats()
        else:
            scaled_stats = []
            with hf.File(self.scaled_file_path, "r") as f_scaled:
                for k in f_scaled.keys():
                    scaled_stats.append(f_scaled[k])
            scaled_stats = da.concatenate(scaled_stats, axis=1)

        if save_stat_list:
            self.scaled_stats = scaled_stats.compute()

        # Calculation of PC scores
        scores = self.fit_transform(scaled_stats)
        self.Scores = scores.compute()

    def __validate_stats(self):
        val_shape = (0,0)
        with hf.File(self.unscaled_file_path,'r') as f_unscaled:
            for k in f_unscaled.keys():
                if val_shape==(0,0):
                    val_shape = f_unscaled[k].shape
                    continue
                elif val_shape != f_unscaled[k].shape:
                    return False
        return True

    def compute_scaled_stats(self):
        var_values = {}
        with hf.File(self.unscaled_file_path,"r") as f_unscaled:
            for k in f_unscaled.keys():
                d = f_unscaled[k]

                stats = da.from_array(d, chunks=(1000, 1000))
                var_stats = stats.var().compute()
                var_values[k] = var_stats

        return self.scale_stats(var_values,self.scale_type)

    def scale_stats(self,var_values,scale):
        all_stats = []
        with hf.File(self.scaled_file_path, "w") as f_scaled:
            with hf.File(self.unscaled_file_path,'r') as f_unscaled:
                for k in f_unscaled.keys():
                    stats = f_unscaled[k]
                    if scale == 'max_variance':
                        # Getting the indices of stats with from lowest to largest variance
                        max_var = max(var_values.values())

                        var_ratio = max_var / var_values[k]
                        stats = np.sqrt(var_ratio) * stats
                    elif scale == 'statwise_variance':
                        stats /= var_vals[k]
                    elif scale == 'featurewise_variance':
                        sc = DaskStandardScaler()
                        stats = sc.fit_transform(stats)
                    all_stats.append(stats)
                    f_scaled.create_dataset(str(k),stats.shape,data=stats)
        all_stats = da.concatenate(all_stats, axis=1)
        return all_stats

    # Visualization of PC scores
    def visualize_scores(self, indices, feature = None, feature_name = None, feature_unit = None):
        Visualize_PC_Scores(self.Scores, indices, feature = feature, feature_name = feature_name, \
                            feature_unit = feature_unit, fig = None, fig_height = 5, dpi = 80)