# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_Pair_Correlation.ipynb (unless otherwise specified).

__all__ = ['PairCorr', 'PairCorr_Batch']

# Cell
#export
import numpy as np
from app.services.apps.image_analysis.workflow_widgets.utils.Utilities import Counts, Attempts, VariableCheck, accumulate_local_state_FFTs
from app.services.apps.image_analysis.workflow_widgets.utils.Visualizations import Visualize_Pair_Correlation

# Cell
class PairCorr(object):

    def __init__(self, M1, M2 = None, cutoff = None, mask = None, periodicity = True, \
                 resolution = 1, resolution_unit = None, ls_ind = None):

        # Checking for compatiblity of variables
        VariableCheck(M1, M2, mask, periodicity)

        # Adding the resolution information to class instance
        self.resolution = resolution
        self.resolution_unit = resolution_unit

        # Writing the local state indices to the class instance
        self.ls_ind = ls_ind

        # Specifying cutoff based on cutoff and resolution values
        max_vec_mag = np.ceil(np.sqrt(2 * ((np.min(M1.shape)-1) // 2)**2)).astype('int')
        if cutoff is None or cutoff > max_vec_mag * resolution:
            self.cutoff_cell = max_vec_mag
            self.cutoff = max_vec_mag * resolution
        else:
            self.cutoff_cell = np.ceil(cutoff / self.resolution).astype(int)
            self.cutoff = self.cutoff_cell * self.resolution

        # Calling ImageCorr class to obtain counts and attempts
        C = Counts(M1, M2, self.cutoff_cell, mask, periodicity).astype('int')
        A = Attempts(M1.shape, self.cutoff_cell, mask, periodicity).astype('int')

        # Generating the array for vector magnitude
        coord_lin = []
        for n in range(0,np.ndim(C)):
            coord_lin.append(np.linspace(-np.ceil((C.shape[n]-1)/2),np.floor((C.shape[n]-1)/2),\
                                         C.shape[n]))
        d = np.meshgrid(*coord_lin, indexing = 'ij')
        vec_mag_sq = sum([i ** 2 for i in d])

        # Unique values of raw vector magnitudes
        raw_mag_sq = np.unique(vec_mag_sq.flatten())
        raw_mag = np.sqrt(raw_mag_sq)

        # # Sorting the counts and attempts according to ascending order of vector magnitudes
        ID = np.argsort(vec_mag_sq.flatten())
        vec_mag_sq = vec_mag_sq.flatten()[ID]
        C = C.flatten()[ID]
        A = A.flatten()[ID]

        # Calculations of coarsened PCF
        C = C[vec_mag_sq < (self.cutoff_cell + 1) ** 2]
        A = A[vec_mag_sq < (self.cutoff_cell + 1) ** 2]
        vec_mag_sq = vec_mag_sq[vec_mag_sq < (self.cutoff_cell + 1) ** 2]
        vec_mag = np.sqrt(vec_mag_sq)

        vec_dist_low = vec_mag-np.floor(vec_mag)
        vec_dist_high = np.ceil(vec_mag)-vec_mag

        wl_counts = np.bincount(np.floor(vec_mag).astype('int'), weights = C * vec_dist_high)
        wh_counts = np.bincount(np.ceil(vec_mag).astype('int'), weights = C * vec_dist_low)
        wl_attempts = np.bincount(np.floor(vec_mag).astype('int'), weights = A * vec_dist_high)
        wh_attempts = np.bincount(np.ceil(vec_mag).astype('int'), weights = A * vec_dist_low)

        int_loc = (np.ceil(vec_mag)-np.floor(vec_mag)) == 0
        int_counts = np.bincount(vec_mag[int_loc].astype('int'), weights = C[int_loc])
        int_attempts = np.bincount(vec_mag[int_loc].astype('int'), weights = A[int_loc])

        C_int = wl_counts + wh_counts[:wl_counts.shape[0]] + \
                np.append(int_counts,[0] * (wl_counts.shape[0] - int_counts.shape[0])).astype(int)
        A_int = wl_attempts + wh_attempts[:wl_counts.shape[0]] + \
                np.append(int_attempts,[0] * (wl_attempts.shape[0] - int_attempts.shape[0])).astype(int)
        self.PC = C_int/A_int
        self.PC = self.PC[:(self.cutoff_cell+1)]
        self.rmag = np.arange(self.PC.shape[0]) * self.resolution


    # Method to visualize pair-correlation
    def visualize(self, ax = None, thumbnail = False, imageloc = None, y_lims = None, interactive = False, \
                  fig = None, fig_height = 5, return_fig = False, dpi = 80):

        params = {'ax': ax, 'fig': fig, 'interactive': interactive, 'fig_height': fig_height, \
                  'imageloc': imageloc, 'dpi': dpi, 'return_fig': return_fig, 'thumbnail': thumbnail, \
                  'ls_ind': self.ls_ind, 'resolution': self.resolution, 'resolution_unit': self.resolution_unit, \
                  'y_lims': y_lims}

        # Calling pair-correlation visualization in feature engineering Visualizations module as method
        fig_out = Visualize_Pair_Correlation(self.PC, **params)

        # Return figure (for platform purposes)
        if return_fig:
            return fig_out

# Cell
class PairCorr_Batch(object):

    def __init__(self, M, local_state_combinations, cutoff = None, mask = None, \
                 periodicity = True, resolution = 1, resolution_unit = None):

        # Adding the resolution information to class instance
        self.resolution = resolution
        self.resolution_unit = resolution_unit

        # Writing the local state indices to the class instance
        self.local_state_combinations = local_state_combinations

        # Specifying cutoff based on cutoff and resolution values
        max_vec_mag = np.ceil(np.sqrt(2 * ((np.min(M.shape)-1) // 2)**2)).astype('int')
        if cutoff is None or cutoff > max_vec_mag * resolution:
            self.cutoff_cell = max_vec_mag
            self.cutoff = max_vec_mag * resolution
        else:
            self.cutoff_cell = np.ceil(cutoff / self.resolution).astype(int)
            self.cutoff = self.cutoff_cell * self.resolution

        # Extract the FFTs of all local states contained in local_state_combinations list
        M_sf = accumulate_local_state_FFTs(M, local_state_combinations, self.cutoff_cell, \
                                           mask, periodicity)

        # Attempts used to calculate two-point statistics
        A = Attempts(M.shape, self.cutoff_cell, mask, periodicity).astype('int')

        # Generating the array for vector magnitude
        coord_lin = []
        for n in range(0,np.ndim(A)):
            coord_lin.append(np.linspace(-np.ceil((A.shape[n]-1)/2),np.floor((A.shape[n]-1)/2),\
                                         A.shape[n]))
        d = np.meshgrid(*coord_lin, indexing = 'ij')
        vec_mag_sq = sum([i ** 2 for i in d])

        # Unique values of raw vector magnitudes
        raw_mag_sq = np.unique(vec_mag_sq.flatten())
        raw_mag = np.sqrt(raw_mag_sq)

        # Sorting the attempts according to ascending order of vector magnitudes
        ID = np.argsort(vec_mag_sq.flatten())
        vec_mag_sq = vec_mag_sq.flatten()[ID]
        A = A.flatten()[ID]

        # Removing attempts entries larger than specified vector magnitude
        A = A[vec_mag_sq < (self.cutoff_cell + 1) ** 2]
        vec_mag_sq_cutoff = vec_mag_sq[vec_mag_sq < (self.cutoff_cell + 1) ** 2]
        vec_mag = np.sqrt(vec_mag_sq_cutoff)

        # Vector magnitudes corresponding to low and high side of the calculations
        vec_dist_low = vec_mag-np.floor(vec_mag)
        vec_dist_high = np.ceil(vec_mag)-vec_mag
        wl_attempts = np.bincount(np.floor(vec_mag).astype('int'), weights = A * vec_dist_high)
        wh_attempts = np.bincount(np.ceil(vec_mag).astype('int'), weights = A * vec_dist_low)

        int_loc = (np.ceil(vec_mag)-np.floor(vec_mag)) == 0
        int_attempts = np.bincount(vec_mag[int_loc].astype('int'), weights = A[int_loc])

        # Counts for all local state combinations and obtaining pair-correlation function
        self.PC_batch = {}
        for ls_comb in local_state_combinations:

            C = np.fft.fftshift( np.fft.ifftn( np.conj(M_sf['M_sf_{}'.format(ls_comb[0])]) * \
                                          M_sf['M_sf_{}'.format(ls_comb[1])] ).real )

            # Sorting the attempts according to ascending order of vector magnitudes
            C = C.flatten()[ID]

            # Removing counts entries larger than specified vector magnitude
            C = C[vec_mag_sq < (self.cutoff_cell + 1) ** 2]

            wl_counts = np.bincount(np.floor(vec_mag).astype('int'), weights = C * vec_dist_high)
            wh_counts = np.bincount(np.ceil(vec_mag).astype('int'), weights = C * vec_dist_low)
            int_counts = np.bincount(vec_mag[int_loc].astype('int'), weights = C[int_loc])
            C_int = wl_counts + wh_counts[:wl_counts.shape[0]] + \
                    np.append(int_counts,[0] * (wl_counts.shape[0] - int_counts.shape[0])).astype(int)
            A_int = wl_attempts + wh_attempts[:wl_counts.shape[0]] + \
                    np.append(int_attempts,[0] * (wl_attempts.shape[0] - int_attempts.shape[0])).astype(int)

            self.PC_batch['PC_{}{}'.format(ls_comb[0], ls_comb[1])] = C_int / A_int
            self.PC_batch['PC_{}{}'.format(ls_comb[0], ls_comb[1])] = self.PC_batch['PC_{}{}'.\
                                                                      format(ls_comb[0], ls_comb[1])][:(self.cutoff_cell + 1)]

    # Method to visualize two-point statistics
    def visualize(self, ls_comb, ax = None, thumbnail = False, imageloc = None, y_lims = None, \
                  interactive = False, fig = None, fig_height = 5, dpi = 80, return_fig = False):

        params = {'ax': ax, 'fig': fig, 'interactive': interactive, 'fig_height': fig_height, \
                  'imageloc': imageloc, 'dpi': dpi, 'return_fig': return_fig, 'thumbnail': thumbnail, \
                  'resolution': self.resolution, 'resolution_unit': self.resolution_unit, \
                  'y_lims': y_lims, 'ls_ind': ls_comb}

        # Calling TwoPoint visualization in feature engineering Visualizations module as method
        fig_out = Visualize_Pair_Correlation(self.PC_batch['PC_{}{}'.format(ls_comb[0],ls_comb[1])], **params)

        # Return figure (for platform purposes)
        if return_fig:
            return fig_out