# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_Rotationally_Invariant_Statistics.ipynb (unless otherwise specified).

__all__ = ['RotInv', 'RotInv_Batch']

# Cell
#export
import numpy as np
from app.services.apps.image_analysis.workflow_widgets.utils.Two_Point_Statistics import TwoPoint, TwoPoint_Batch
from app.services.apps.image_analysis.workflow_widgets.utils.Visualizations import Visualize_Rotationally_Invariant_Statistics
from numpy import pi
from scipy.interpolate import RegularGridInterpolator

# Cell
class RotInv(object):

    def __init__(self, M1, M2 = None, ang_int = 5, cutoff = None, mask = None, periodicity = True, \
                 resolution = 1, resolution_unit = None, ls_ind = None):

        # Setting up angular increment
        if ang_int > 15:
            self.ang_int = 15
        else:
            self.ang_int = ang_int

        # Adding the resolution information to class instance
        self.resolution = resolution
        self.resolution_unit = resolution_unit

        # Writing the local state indices to the class instance
        self.ls_ind = ls_ind

        # Specifying cutoff based on cutoff and resolution values
        max_cutoff_cell = ((np.min(M1.shape)-1) // 2).astype(int)  # Maximum possible cutoff in spatial bins
        if cutoff is None or cutoff > max_cutoff_cell * resolution:
            self.cutoff_cell = max_cutoff_cell
            self.cutoff = max_cutoff_cell * resolution
        else:
            self.cutoff_cell = np.ceil(cutoff / resolution).astype(int)
            self.cutoff = self.cutoff_cell * self.resolution

        # Obtaining two-point statistics
        ftp = TwoPoint(M1, M2 = M2, cutoff = cutoff, mask = mask, periodicity = periodicity, \
                       resolution = self.resolution, resolution_unit = resolution_unit)

        # 2-d version
        if M1.ndim == 2:

            # Building the grid of two-point statistics in cartesian coordinates (assumes the grid is square)
            x_range = np.arange(-self.cutoff_cell, self.cutoff_cell + 1)

            # Regular grid of two-point statistics in polar coordinates
            self.theta = np.arange(-180, 180, step = ang_int)
            self.r = np.arange(self.cutoff_cell + 1)
            theta_i, r_i = np.meshgrid(self.theta * pi/180, self.r)
            x_i = r_i * np.cos(theta_i)
            y_i = r_i * np.sin(theta_i)
            X_i = np.concatenate((x_i.flatten()[:,None], y_i.flatten()[:,None]), axis = 1)

            # Interpolating for regular grid of r-θ (i.e. X_i) in cartesian coordinates based on two-point
            # statistics in cartesian coordinates (i.e. X)
            R_i2 = RegularGridInterpolator((x_range, x_range), ftp.TP, method = 'linear')
            R_i2 = R_i2(X_i).reshape(self.cutoff_cell + 1, theta_i.shape[1])

            # Removing the dependency to rotational invariance
            R_i2 = np.fft.ifft( np.abs(np.fft.fft(R_i2, axis = 1)), axis = 1).real
            self.RI = np.fft.fftshift(R_i2, axes = 1)

        # Raise value error since 3-d version has not been implemented yet
        elif M1.ndim == 3:

            raise ValueError('Rotationally invariant two-point statistics has not been implemented '\
                             'for 3-d microstructures yet.')


    # Method to visualize rotationally invariant two-point statistics
    def visualize(self, ax = None, thumbnail = False, imageloc = None, colorbar_lims = None, interactive = False, \
                  fig = None, fig_height = 5, return_fig = False, dpi = 80):

        params = {'ax': ax, 'fig': fig, 'interactive': interactive, 'fig_height': fig_height, \
                  'imageloc': imageloc, 'dpi': dpi, 'return_fig': return_fig, 'thumbnail': thumbnail, \
                  'ls_ind': self.ls_ind, 'resolution': self.resolution, 'resolution_unit': self.resolution_unit, \
                  'colorbar_lims': colorbar_lims, 'ang_int': self.ang_int}

        # Calling TwoPoint visualization in FeatureEngineeringVisualization module as method
        fig_out = Visualize_Rotationally_Invariant_Statistics(self.RI, **params)

        # Return figure (for platform purposes)
        if return_fig:
            return fig_out

# Cell
class RotInv_Batch(object):

    def __init__(self, M, local_state_combinations, ang_int = 5, cutoff = None, mask = None, \
                 periodicity = True, resolution = 1, resolution_unit = None):

        # Setting up angular increment
        if ang_int > 15:
            self.ang_int = 15
        else:
            self.ang_int = ang_int

        # Adding the resolution information to class instance
        self.resolution = resolution
        self.resolution_unit = resolution_unit

        # Writing the local state indices to the class instance
        self.local_state_combinations = local_state_combinations

        # Specifying cutoff based on cutoff and resolution values
        max_cutoff_cell = ((np.min(M.shape)-1) // 2).astype(int)  # Maximum possible cutoff in spatial bins
        if cutoff is None or cutoff > max_cutoff_cell * resolution:
            self.cutoff_cell = max_cutoff_cell
            self.cutoff = max_cutoff_cell * resolution
        else:
            self.cutoff_cell = np.ceil(cutoff / resolution).astype(int)
            self.cutoff = self.cutoff_cell * self.resolution

        # 2-D version
        if M.ndim == 2:

            # Building the grid of two-point statistics in cartesian coordinates (assumes the grid is square)
            x_range = np.arange(-self.cutoff_cell, self.cutoff_cell + 1)

            # Regular grid of two-point statistics in polar coordinates
            self.theta = np.arange(-180, 180, step = ang_int)
            self.r = np.arange(self.cutoff_cell + 1)
            theta_i, r_i = np.meshgrid(self.theta * pi/180, self.r)
            x_i = r_i * np.cos(theta_i)
            y_i = r_i * np.sin(theta_i)
            X_i = np.concatenate((x_i.flatten()[:,None], y_i.flatten()[:,None]), axis = 1)

            # Generating the two-point statistics collection
            TP_coll = TwoPoint_Batch(M, local_state_combinations, periodicity = periodicity, cutoff = self.cutoff, \
                                     resolution = self.resolution, resolution_unit = self.resolution_unit)

            # Counts for all local state combinations and obtaining two-point statistics
            self.RI_batch = {}
            for ls_comb in local_state_combinations:

                # Interpolating for regular grid of r-θ (i.e. X_i) in cartesian coordinates based on two-point
                # statistics in cartesian coordinates (i.e. X)
                R_i2 = RegularGridInterpolator((x_range, x_range), TP_coll.TP_batch['TP_{}{}'.format(ls_comb[0], ls_comb[1])], \
                                               method = 'linear')
                R_i2 = R_i2(X_i).reshape(self.cutoff_cell + 1, theta_i.shape[1])

                # Removing the dependency to rotational invariance
                R_i2 = np.fft.ifft( np.abs(np.fft.fft(R_i2, axis = 1)), axis = 1).real
                RI = np.fft.fftshift(R_i2, axes = 1)

                self.RI_batch['RI_{}{}'.format(ls_comb[0], ls_comb[1])] = RI

        # Raise value error since 3-d version has not been implemented yet
        elif M1.ndim == 3:

            raise ValueError('Rotationally invariant two-point statistics has not been implemented '\
                             'for 3-d microstructures yet.')


    # Method to visualize rotationally invariant two-point statistics
    def visualize(self, ls_comb, ax = None, thumbnail = False, imageloc = None, colorbar_lims = None, interactive = False, \
                  fig = None, fig_height = 5, dpi = 80, return_fig = False):

        params = {'ax': ax, 'fig': fig, 'interactive': interactive, 'fig_height': fig_height, \
                  'imageloc': imageloc, 'dpi': dpi, 'return_fig': return_fig, 'thumbnail': thumbnail, \
                  'resolution': self.resolution, 'resolution_unit': self.resolution_unit, \
                  'colorbar_lims': colorbar_lims, 'ls_ind': ls_comb, 'ang_int': self.ang_int}

        # Calling TwoPoint visualization in feature engineering Visualizations module as method
        fig_out = Visualize_Rotationally_Invariant_Statistics(self.RI_batch['RI_{}{}'.format(ls_comb[0],ls_comb[1])], **params)

        # Return figure (for platform purposes)
        if return_fig:
            return fig_out