# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_Two_Point_Statistics.ipynb (unless otherwise specified).

__all__ = ['TwoPoint', 'TwoPoint_Batch']

# Cell
#export
import numpy as np
from app.services.apps.image_analysis.workflow_widgets.utils.Visualizations import Visualize_Two_Point_Statistics
from app.services.apps.image_analysis.workflow_widgets.utils.Utilities import Counts, Attempts, VariableCheck, accumulate_local_state_FFTs

# Cell
class TwoPoint(object):

    # Calculation of two-point statistics
    def __init__(self, M1, M2 = None, cutoff = None, mask = None, periodicity = True, \
                 resolution = 1, resolution_unit = None, ls_ind = None):

        # Checking for compatiblity of variables
        VariableCheck(M1, M2, mask, periodicity)

        # Adding the resolution information to class instance
        self.resolution = resolution
        self.resolution_unit = resolution_unit

        # Writing the local state indices to the class instance
        self.ls_ind = ls_ind

        # Specifying cutoff based on cutoff and resolution values
        max_cutoff_cell = ((np.min(M1.shape)-1) // 2).astype(int)  # Maximum possible cutoff in spatial bins
        if cutoff is None or cutoff > max_cutoff_cell * resolution:
            self.cutoff_cell = max_cutoff_cell
            self.cutoff = max_cutoff_cell * resolution
        else:
            self.cutoff_cell = np.ceil(cutoff / resolution).astype(int)
            self.cutoff = self.cutoff_cell * self.resolution

        # Calling Counts and Attempts functions
        C = Counts(M1, M2, self.cutoff_cell, mask, periodicity)
        A = Attempts(M1.shape, self.cutoff_cell, mask, periodicity)

        # Specification of indices to extract cutoff region
        center_slice = []  # Initialization of index list
        for n in range(0,np.ndim(M1)):
            center_slice.append(slice(np.floor(C.shape[n]/2).astype(int) - self.cutoff_cell, \
                                      np.floor(C.shape[n]/2).astype(int) + self.cutoff_cell + 1))
        center_slice = tuple(center_slice)  # Converting the index list to tuple

        # Extraction of center region based on cutoff value
        C = C[center_slice]
        A = A[center_slice]

        # Calculation of two-point statistics, Counts / Attempts
        self.TP = C / A

    # Method to visualize two-point statistics
    def visualize(self, ax = None, thumbnail = False, imageloc = None, colorbar_lims = None, interactive = False, \
                  fig = None, fig_height = 5, return_fig = False, dpi = 80):

        params = {'ax': ax, 'fig': fig, 'interactive': interactive, 'fig_height': fig_height, \
                  'imageloc': imageloc, 'dpi': dpi, 'return_fig': return_fig, 'thumbnail': thumbnail, \
                  'ls_ind': self.ls_ind, 'resolution': self.resolution, 'resolution_unit': self.resolution_unit, \
                  'colorbar_lims': colorbar_lims}

        # Calling TwoPoint visualization in FeatureEngineeringVisualization module as method
        fig_out = Visualize_Two_Point_Statistics(self.TP, **params)

        # Return figure (for platform purposes)
        if return_fig:
            return fig_out

# Cell
class TwoPoint_Batch(object):

    def __init__(self, M, local_state_combinations, cutoff = None, mask = None, periodicity = True, \
                 resolution = 1, resolution_unit = None):

        # Adding the resolution information to class instance
        self.resolution = resolution
        self.resolution_unit = resolution_unit

        # Writing the local state indices to the class instance
        self.local_state_combinations = local_state_combinations

        # Specifying cutoff based on cutoff and resolution values
        max_cutoff_cell = ((np.min(M.shape)-1) // 2).astype(int)  # Maximum possible cutoff in spatial bins
        if cutoff is None or cutoff > max_cutoff_cell * resolution:
            self.cutoff_cell = max_cutoff_cell
            self.cutoff = max_cutoff_cell * resolution
        else:
            self.cutoff_cell = np.ceil(cutoff / resolution).astype(int)
            self.cutoff = self.cutoff_cell * self.resolution

        # Extract the FFTs of all local states contained in local_state_combinations list
        M_sf = accumulate_local_state_FFTs(M, local_state_combinations, self.cutoff_cell, \
                                           mask, periodicity)

        # Attempts used to calculate two-point statistics
        A = Attempts(M.shape, self.cutoff_cell, mask, periodicity)

        # Specification of indices to extract cutoff region
        center_slice = []  # Initialization of index list
        for n in range(0,np.ndim(M)):
            center_slice.append(slice(np.floor(A.shape[n]/2).astype(int) - self.cutoff_cell, \
                                      np.floor(A.shape[n]/2).astype(int) + self.cutoff_cell + 1))
        center_slice = tuple(center_slice)  # Converting the index list to tuple

        # Extraction of center region in attempts array
        A = A[center_slice]

        # Counts for all local state combinations and obtaining two-point statistics
        self.TP_batch = {}
        for ls_comb in local_state_combinations:

            TP = np.fft.fftshift( np.fft.ifftn( np.conj(M_sf['M_sf_{}'.format(ls_comb[0])]) * \
                                          M_sf['M_sf_{}'.format(ls_comb[1])] ).real )[center_slice] / A

            self.TP_batch['TP_{}{}'.format(ls_comb[0], ls_comb[1])] = TP

    # Method to visualize two-point statistics
    def visualize(self, ls_comb, ax = None, thumbnail = False, imageloc = None, colorbar_lims = None, interactive = False, \
                  fig = None, fig_height = 5, dpi = 80, return_fig = False):

        params = {'ax': ax, 'fig': fig, 'interactive': interactive, 'fig_height': fig_height, \
                  'imageloc': imageloc, 'dpi': dpi, 'return_fig': return_fig, 'thumbnail': thumbnail, \
                  'resolution': self.resolution, 'resolution_unit': self.resolution_unit, \
                  'colorbar_lims': colorbar_lims, 'ls_ind': ls_comb}

        # Calling TwoPoint visualization in feature engineering Visualizations module as method
        fig_out = Visualize_Two_Point_Statistics(self.TP_batch['TP_{}{}'.format(ls_comb[0],ls_comb[1])], **params)

        # Return figure (for platform purposes)
        if return_fig:
            return fig_out