# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/06_Utilities.ipynb (unless otherwise specified).

__all__ = ['VariableCheck', 'Counts', 'Attempts', 'accumulate_local_state_FFTs', 'get_y_lims', 'feature_scaler']

# Cell
#export
import numpy as np

# Cell
def VariableCheck(M1, M2, mask, periodicity):

    # Raise value error if microstructure is not defined as a 2-D or 3-D microstructure
    if not np.ndim(M1) in (2, 3):
        raise ValueError('M1 (i.e. microstructure) must be a 2-D or 3-D numpy array.')

    # Raise value error if periodicity is not periodic or nonperiodic
    if not isinstance(periodicity, bool):
        raise ValueError('Periodicity value must be either True or False.')

    # Setting mask to ones for default selection (i.e. no mask). Raise value error if mask does
    # not have the same shape as the microstructure or is not a numpy array.
    if not mask is None and (not mask.shape == M1.shape or not type(mask) is np.ndarray):
        raise ValueError('Mask must be an array with the same shape as the microstructure'\
                         '. Alternatively, it can be left out to assume no mask.')

    # Raise value error if M2 is not None (i.e. autocorrelation) and does not have the same size
    # as M1
    if not M2 is None and not M1.shape == M2.shape:
        raise ValueError('M2 must have the same shape as M1. Alternatively, it can be left out'\
                         ' to perform autocorrelation on M1')

# Cell
def Counts(M1, M2, cutoff, mask, periodicity):

    # Setting M1 and its spatial FFT response
    if not mask is None:
        M1 = M1 * mask  # Masking operation of unreliable regions
    if not periodicity:  # Padding wit1h zeros for nonperiodic case
        M1 = np.pad(M1,tuple([(0,cutoff)]*np.ndim(M1)),'constant')
    M1f = np.fft.fftn(M1)  # FFT response of M1

    if M2 is None: # Autocorrelation
        M2f = M1f
    else:  # Cross-correlation
        # Setting M2 and its spatial FFT response
        if not mask is None:
            M2 = M2 * mask  # Masking operation of unreliable regions
        if not periodicity:  # Padding with zeros for nonperiodic case
            M2 = np.pad(M2,tuple([(0,cutoff)]*np.ndim(M2)),'constant')
        M2f = np.fft.fftn(M2)  # FFT response of M1

    # Calculation of counts (via convolution)
    return np.fft.fftshift( np.fft.ifftn( np.conj(M1f) * M2f ).real )

# Cell
def Attempts(mic_shape, cutoff, mask, periodicity):

    if mask is None:
        mask = np.ones(mic_shape) # Creating the field of ones

    if not periodicity:  # Padding with zeros for nonperiodic case
        mask = np.pad(mask,tuple([(0,cutoff)]*np.ndim(mask)),'constant')
    maskf = np.fft.fftn(mask)

    # Calculation of attempts (via convolution)
    return np.fft.fftshift( np.fft.ifftn( maskf * np.conj(maskf) ).real )

# Cell
def accumulate_local_state_FFTs(M, local_state_combinations, cutoff, mask, periodicity):

    # Finding the unique indices
    uniq_ls = np.unique(local_state_combinations)

    # Adjusting microstructure and mask for nonperiodic case
    if not periodicity:

        # Padding microstructure
        M = np.pad(M, tuple([(0, cutoff)] * np.ndim(M)), mode = 'constant', \
               constant_values = tuple([(0, -1)] * np.ndim(M)))

        # Padding mask
        if not mask is None:
            mask = np.pad(mask, tuple([(0, cutoff)] * np.ndim(mask)), 'constant')

    M_sf = {}  # Initialization of local state dictionary
    for ls in uniq_ls:

        # Extracting microstructure function associated with index 0
        M_ls = M == ls

        # Apply mask if specified
        if not mask is None:
            M_ls = M_ls * mask

        # Write spatial frequency response to dictionary
        M_sf['M_sf_{}'.format(ls)] = np.fft.fftn(M_ls)

    return M_sf

# Cell
def get_y_lims(y1, y2):

    # Concatenating the array
    y = np.concatenate((y1, y2))

    y_range = np.ptp(y) # Range
    y_min = np.min(y) - 0.05 * y_range # Minimum value of y axis
    if y_min < 0:
        y_min = 0
    y_max = np.max(y) + 0.05 * y_range # Maximum value of y axis

    return [y_min, y_max]

# Cell
def feature_scaler(stat_list, scale = 'max_variance'):

    if scale == 'max_variance':

        if isinstance(stat_list, list) and stat_list.__len__() > 1:

            # Calculating the variances of stats in the stat_list
            var_list = [np.var(stats) for stats in stat_list]

            # Getting the indices of stats with from largest to lowest variance
            I = np.argsort(var_list)[::-1]

            # Scaling each set of statistics based on its ratio between the set
            # with the largest variance
            scaling_factors = np.ones(len(stat_list))
            for i in I[:-1]:
                stats = stat_list[i]
                var_ratio = var_list[i] / var_list[I[-1]]
                scaling_factors[i] = np.sqrt(var_ratio)
                stat_list[i] = stats / scaling_factors[i]

    elif scale == 'statwise_variance':

        # Initialization of scaling factor
        scaling_factors = []

        if isinstance(stat_list, list) and stat_list.__len__() > 1:

            # Calculating the variances of stats in the stat_list
            var_list = [np.var(stats) for stats in stat_list]
            for i in range(len(stat_list)):
                stat_list[i] = stat_list[i] / np.sqrt(var_list[i])
            scaling_factors = [np.sqrt(v) for v in var_list]

    elif scale == 'featurewise_variance':

        # Returning entire StandardScaler() object since we scale w.r.t. each component independently.
        scaling_factors = StandardScaler()
        if isinstance(stat_list, list) and stat_list.__len__() > 1:
            scaling_factors.fit_transform(np.hstack(stat_list))

    return stat_list, scaling_factors