# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05_Visualizations.ipynb (unless otherwise specified).

__all__ = ['Visualize_Microstructure', 'Visualize_Two_Point_Statistics', 'Visualize_Pair_Correlation',
           'Visualize_Rotationally_Invariant_Statistics', 'Visualize_ARCLD', 'Visualize_ARCLD_Angle', 'Visualize_CLD',
           'Visualize_PC_Scores', 'Visualize_Explained_Variance']

# Cell
#export
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objs as go
import plotly.express as px
from matplotlib.ticker import FormatStrFormatter, ScalarFormatter, FuncFormatter
from numpy import pi
from scipy.interpolate import griddata

# Cell
def Visualize_Microstructure(M, num_ls = None, ax = None, resolution = 1, resolution_unit = None, interactive = False, \
                             colormap = None, thumbnail = False, imageloc = None, fig = None, fig_height = 5, dpi = 80, \
                             return_fig = False):

    # Setting up the colormap
    if num_ls is None:
        num_ls = np.unique(M).shape[0]

    if num_ls == 2:
        colormap = 'gray'
        if interactive:
            color_lims = [0, 1.07]
        else:
            color_lims = [0, 1]
    elif num_ls > 2:
        colormap = 'viridis'
        color_lims = [np.min(M), np.max(M)]

    # Setting axes limits and ticks based on resolution information
    axlims_x = [0, resolution * M.shape[1]]
    axlims_y = [0, resolution * M.shape[0]]
    axticks_x = np.linspace(*axlims_x, 5)
    axticks_y = np.linspace(*axlims_y, 5)
    if axticks_x[-1] <= 0.1:
        str_format = '{:.3f}'
    elif axticks_x[-1] >= 100:
        str_format = '{:.1f}'
    else:
        str_format = '{:.2f}'
    ax_ticks_x_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in axticks_x]
    if axticks_x[-1] <= 0.1:
        str_format = '{:.3f}'
    elif axticks_x[-1] >= 100:
        str_format = '{:.1f}'
    else:
        str_format = '{:.2f}'
    ax_ticks_y_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in axticks_y]

    # 2-D images
    if np.ndim(M) == 2:

        if not interactive:

            # Creating a new set of axes if ax is not defined (i.e. ax = None)
            if ax is None:
                fig = plt.figure(figsize = (fig_height * M.shape[1]/M.shape[0], fig_height))
                ax = fig.gca()

            # Plot two-point statistics as image
            mic_plot = ax.imshow(M, extent = [*axlims_x, *axlims_y], cmap = colormap)

            # Setting the axes limits of the microstructure plots
            ax.set_xlim(axlims_x)
            ax.set_ylim(axlims_y)

            # Setting the ticks and tick label fontsize
            ax.set_xticks(axticks_x); ax.set_yticks(axticks_y)
            ax.set_xticklabels(ax_ticks_x_labels)
            ax.set_yticklabels(ax_ticks_y_labels)
            ax.tick_params(axis='both', which = 'major', labelsize = 14)

            # Setting the labels for plots
            x_ax_label = 'x'; y_ax_label = 'y';
            if not resolution_unit is None:
                x_ax_label = x_ax_label + ' (' + resolution_unit + ')'
                y_ax_label = y_ax_label + ' (' + resolution_unit + ')'
            ax.set_xlabel(x_ax_label, fontsize = 14)
            ax.set_ylabel(y_ax_label, fontsize = 14)

            # Setting up the color limit
            mic_plot.set_clim(color_lims)

            # Removing the axes ticks and labels for thumbnail images
            if thumbnail:
                ax.axis('off')

            if not imageloc is None:  # Save the file to the location
                plt.savefig(imageloc + '.png', dpi = 150, facecolor = 'w', edgecolor = 'k', orientation = 'portrait', \
                            transparent = False, bbox_inches = 'tight', pad_inches = 0)

            # Returns the fig object as output (used for platform purposes)
            if return_fig:
                return fig

        elif interactive:

            # Generate plotly figure if None is entered for fig parameter
            if fig is None:
                fig = go.Figure()

            # Plotting the heatmap
            plotdata = go.Heatmap(z = np.flipud(M), x = np.linspace(*axlims_x, M.shape[1] + 1), y = np.linspace(*axlims_y, M.shape[0] + 1), \
                                  colorscale = colormap, showscale = False)
            fig.add_trace(plotdata)

            # Setting the axes labels
            xlabel = 'x'; ylabel = 'y'
            if not resolution_unit is None:
                xlabel = xlabel + ' (' + resolution_unit + ')'
                ylabel = ylabel + ' (' + resolution_unit + ')'

            # Setting up layout
            layout = go.Layout(xaxis = dict(tickmode = 'array', tickvals = axticks_x, ticktext = ax_ticks_x_labels, title = xlabel, \
                                            titlefont = dict(size = 16), tickfont = dict(size = 14), title_standoff = 10), \
                               yaxis = dict(tickmode = 'array', tickvals = axticks_y, ticktext = ax_ticks_y_labels, title = ylabel, \
                                            titlefont = dict(size = 16), tickfont = dict(size = 14), title_standoff = 10), \
                               showlegend = False, margin_autoexpand = True, autosize = True, margin = dict(t = 35, b = 10, r = 15), \
                               plot_bgcolor='rgba(0,0,0,0)')

            # Changing the color limits to custom range. Used for comparison of two-point statistics in the same color limits
            if not color_lims is None:
                fig.data[0].update(zmin = color_lims[0], zmax = color_lims[1])

            fig.update_layout(layout)

            # Prevents the pop up of html page if return_fig is set to True.
            config = {'responsive': True, 'displayModeBar': True, 'displaylogo': False, \
                      'modeBarButtonsToRemove':['lasso2d', 'autoScale2d','toggleSpikelines']}

            if not return_fig:
                fig.show(config = config)


    # 3-D microstructure visualization
    if np.ndim(M) == 3:

        # Use plotly if interactive is selected
        if interactive:

            # Generate plotly figure if None is entered for fig parameter
            if fig is None:
                fig = go.Figure()

            # z axis information
            axlims_x = [0, resolution * M.shape[0]]
            axlims_y = [0, resolution * M.shape[1]]
            axlims_z = [0, resolution * M.shape[2]]
            axticks_x = np.linspace(*axlims_x, 5)
            axticks_y = np.linspace(*axlims_y, 5)
            axticks_z = np.linspace(*axlims_z, 5)
            if axticks_x[-1] <= 0.1:
                str_format = '{:.3f}'
            elif axticks_x[-1] >= 100:
                str_format = '{:.1f}'
            else:
                str_format = '{:.2f}'
            ax_ticks_x_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in axticks_x]
            if axticks_x[-1] <= 0.1:
                str_format = '{:.3f}'
            elif axticks_x[-1] >= 100:
                str_format = '{:.1f}'
            else:
                str_format = '{:.2f}'
            ax_ticks_y_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in axticks_y]
            if axticks_z[-1] <= 0.1:
                str_format = '{:.3f}'
            elif axticks_z[-1] >= 100:
                str_format = '{:.1f}'
            else:
                str_format = '{:.2f}'
            ax_ticks_z_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in axticks_z]

            # Function to extract the slice
            def _get_the_slice(x, y, z, surfacecolor,  colorscale = 'gray', showscale = False):
                return go.Surface(x = x, y = y, z = z, surfacecolor = surfacecolor, colorscale = colorscale, \
                                  showscale = showscale)

            # Specifying the vector space
            x_range = np.linspace(*axlims_x, M.shape[0])
            y_range = np.linspace(*axlims_y, M.shape[1])
            z_range = np.linspace(*axlims_z, M.shape[2])

            # Outer x planes
            y,z = np.meshgrid(y_range, z_range, indexing = 'ij')
            x_minus = np.zeros((M.shape[1], M.shape[2]))
            x_plus = M.shape[0] * np.ones((M.shape[1], M.shape[2]))
            surf_data_minus = M[0,:,:]
            surf_data_plus = M[-1,:,:]
            slice_x_minus = _get_the_slice(x_minus, y, z, surf_data_minus, colorscale = colormap)
            slice_x_plus = _get_the_slice(x_plus, y, z, surf_data_plus, colorscale = colormap)

            # Slice y plane
            x,z = np.meshgrid(x_range, z_range, indexing = 'ij')
            y_minus = np.zeros((M.shape[0], M.shape[2]))
            y_plus = M.shape[1] * np.ones((M.shape[0], M.shape[2]))
            surf_data_minus = M[:,0,:]
            surf_data_plus = M[:,-1,:]
            slice_y_minus = _get_the_slice(x,y_minus,z, surf_data_minus, colorscale = colormap)
            slice_y_plus = _get_the_slice(x,y_plus,z, surf_data_plus, colorscale = colormap)

            # Slice z plane
            x,y = np.meshgrid(x_range, y_range, indexing = 'ij')
            z_minus = np.zeros((M.shape[0],M.shape[1]))
            z_plus = M.shape[2] * np.ones((M.shape[0],M.shape[1]))
            surf_data_minus = M[:,:,0]
            surf_data_plus = M[:,:,-1]
            slice_z_minus = _get_the_slice(x,y,z_minus, surf_data_minus, colorscale = colormap)
            slice_z_plus = _get_the_slice(x,y,z_plus, surf_data_plus, colorscale = colormap)

            # Setting axes labels
            xtickname = 'x'; ytickname = 'y'; ztickname = 'z'
            if not resolution_unit is None:
                xtickname = xtickname + ' (' + resolution_unit + ')'
                ytickname = ytickname + ' (' + resolution_unit + ')'
                ztickname = ztickname + ' (' + resolution_unit + ')'

            slicelist = [slice_x_minus, slice_x_plus, slice_y_minus, slice_y_plus, \
                         slice_z_minus, slice_z_plus]

            # Figure colors (i.e. background, grid, zero lines)
            axis = dict(showbackground = True, backgroundcolor = "rgb(255, 255, 255)", \
                        gridcolor = "rgb(0, 0, 0)", zerolinecolor = "rgb(0, 0, 0)")

            layout = go.Layout(scene = dict(xaxis = dict(axis, tickmode = 'array', title = xtickname, range = axlims_x, \
                                             tickvals = axticks_x, ticktext = ax_ticks_x_labels, \
                                             titlefont = dict(size = 16), tickfont = dict(size = 14)), \
                                yaxis = dict(axis, tickmode = 'array', title = ytickname, range = axlims_y, \
                                             tickvals = axticks_y, ticktext = ax_ticks_y_labels, \
                                             titlefont = dict(size = 16), tickfont = dict(size = 14)), \
                                zaxis = dict(axis, tickmode = 'array', title = ztickname, range = axlims_z, \
                                             tickvals = axticks_z, ticktext = ax_ticks_z_labels, \
                                             titlefont = dict(size = 16), tickfont = dict(size = 14))), \
                   margin_autoexpand = True, autosize = True, margin = dict(t = 35, b = 10, r = 15, l = 10), \
                   scene_camera = dict(eye = dict(x = 1.35, y = 1.35, z = 1.35), \
                                       center = dict(x = 0.1, y = 0, z = -0.1)))

            # Limits for color scale
            vmin = min(M.ravel())
            vmax = max(M.ravel())

            for i in slicelist:
                i.update(cmin = vmin, cmax = vmax)

            fig = go.Figure(data = slicelist, layout=layout)

            # Prevents the pop up of html page if return_fig is set to True.
            config = {'responsive': True, 'displayModeBar': True, 'displaylogo': False, \
                      'modeBarButtonsToRemove':['lasso2d', 'autoScale2d','toggleSpikelines']}

            if not return_fig:
                fig.show(config = config)


        # Matplotlib for static image of 3-d plot
        elif not interactive:

            M = np.pad(M,((0,1),(0,1),(0,1)), mode = 'edge')
            if num_ls == 2:
                M[M == 1] = 0.93 # Setting the 1 value to 0.93 to prevent white phase blending with background
                colormap = plt.cm.gray
                color_lims = [0, 1.07]
            else:
                M = M / np.max(M)
                colormap = plt.cm.viridis
                color_lims = [np.min(M), np.max(M)]

            # Generate 3-d axes if not specified
            if ax is None:
                fig = plt.figure(figsize = (fig_height, fig_height))
                ax = fig.add_subplot(111, projection = '3d')

            # Plotting the faces of the microstructure
            Y, Z = np.mgrid[0:M.shape[1], 0:M.shape[2]]
            X = np.zeros((M.shape[1],M.shape[2]))
            ax.plot_surface(X,Y,Z, facecolors = colormap(M[0,...]), shade = False, rstride = 1, cstride = 1)
            X, Z = np.mgrid[0:M.shape[0], 0:M.shape[2]]
            Y = np.zeros((M.shape[0],M.shape[2]))
            ax.plot_surface(X,Y,Z, facecolors = colormap(M[:,0,:]), shade = False, rstride = 1, cstride = 1)
            X, Y = np.mgrid[0:M.shape[0], 0:M.shape[1]]
            Z = (M.shape[2]-1) * np.ones((M.shape[0],M.shape[1]))
            ax.plot_surface(X,Y,Z, facecolors = colormap(M[...,-1]), shade = False, rstride = 1, cstride = 1)
            ax.view_init(elev = 30, azim = -135)

            # Setting the background of axis planes to white
            ax.w_xaxis.set_pane_color((0,0,0))
            ax.w_yaxis.set_pane_color((0,0,0))
            ax.w_zaxis.set_pane_color((0,0,0))
            ax.set_box_aspect((M.shape[0], M.shape[1], M.shape[2]))

            # Axis ticks and lims
            ax.set_xlim([0, M.shape[0] - 1])
            ax.set_ylim([0, M.shape[1] - 1])
            ax.set_zlim([0, M.shape[2] - 1])
            ax_ticks = []
            ax_ticks.append(np.linspace(0, M.shape[0]-1, 5))
            ax_ticks.append(np.linspace(0, M.shape[1]-1, 5))
            ax_ticks.append(np.linspace(0, M.shape[2]-1, 5))

            # Axes labels
            xlabel = 'X'; ylabel = 'Y'; zlabel = 'Z'
            if not resolution_unit is None:
                xlabel = xlabel + ' (' + resolution_unit + ')'
                ylabel = ylabel + ' (' + resolution_unit + ')'
                zlabel = zlabel + ' (' + resolution_unit + ')'
            ax.set_xlabel(xlabel, fontsize = 14, labelpad = 10)
            ax.set_ylabel(ylabel, fontsize = 14, labelpad = 10)
            ax.set_zlabel(zlabel, fontsize = 14, labelpad = 10)

            # Setting the ticks and tick label fontsize
            ax.set_xticks(ax_ticks[0]); ax.set_yticks(ax_ticks[1]); ax.set_zticks(ax_ticks[2])
            ax_ticks_labels = []
            for i in range(3):
                if ax_ticks[i][-1] <= 1:
                    str_format = '{:.3f}'
                elif ax_ticks[i][-1] >= 100:
                    str_format = '{:.1f}'
                else:
                    str_format = '{:.2f}'
                ax_ticks_labels.append([str_format.format(i * resolution).rstrip('0').rstrip('.') for i in ax_ticks[i]])
            ax.set_xticklabels(ax_ticks_labels[0])
            ax.set_yticklabels(ax_ticks_labels[1])
            ax.set_zticklabels(ax_ticks_labels[2])
            ax.tick_params(axis = 'both', which = 'major', labelsize = 14)

            # Removing the axes ticks and labels for thumbnail images
            if thumbnail:
                ax.set_axis_off()

            # Saving the visualization to an image file if a location is specified
            if not imageloc is None:  # Save the file to the location
                plt.savefig(imageloc + '.png', dpi = 150, facecolor = 'w', edgecolor = 'w',
                    orientation = 'portrait', transparent = False, bbox_inches = 'tight', pad_inches = 0)

            # Returns the fig object as output (used for platform purposes)
            if return_fig:
                return fig

# Cell
def Visualize_Two_Point_Statistics(TP, ax = None, fig = None, resolution = 1, resolution_unit = None, thumbnail = False, \
                                   imageloc = None, ls_ind = None, colorbar_lims = None, interactive = False, fig_height = 6, \
                                   dpi = 80, return_fig = False):

    # Setting the cutoff variable in pixels/voxels from two-point statistics array (assuming the array have the
    # same dimensions in all directions)
    cutoff_cell = TP.shape[0] // 2

    # Setting up ranges of axes ticks based on resolution information
    cutoff = cutoff_cell * resolution

    # Colorbar limits
    if colorbar_lims is None:
        colorbar_lims = [np.min(TP), np.max(TP)]

    # 2-D case
    if TP.ndim == 2:

        if not interactive: # Noninteractive matplotlib plot

            # Creating a new set of axes if ax is not defined (i.e. ax = None)
            if ax is None:
                fig = plt.figure(figsize = (fig_height * 1.2, fig_height))
                ax = fig.gca()
            else:
                fig = ax.get_figure()

            # Setting axes limits and ticks based on resolution information
            axlims = [-cutoff - resolution/2, cutoff + resolution/2]
            ax_ticks = np.linspace(-cutoff, cutoff, 5)

            # Plot two-point statistics as image
            tp_plot = ax.imshow(TP, extent = 2 * axlims, cmap = 'jet', vmin = colorbar_lims[0], vmax = colorbar_lims[1])

            # Setting the axes limits of the plots
            ax.set_xlim(axlims); ax.set_ylim(axlims)

            # Setting the ticks and tick label fontsize
            ax.set_xticks(ax_ticks); ax.set_yticks(ax_ticks)
            if ax_ticks[-1] <= 0.1:
                str_format = '{:.3f}'
            elif ax_ticks[-1] >= 100:
                str_format = '{:.1f}'
            else:
                str_format = '{:.2f}'
            ax_ticks_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in ax_ticks]
            ax.set_xticklabels(ax_ticks_labels)
            ax.set_yticklabels(ax_ticks_labels)
            ax.tick_params(axis='both', which = 'major', labelsize = 16)

            # Setting the labels for plots
            x_ax_label = 'r$_x$'; y_ax_label = 'r$_y$';
            if not resolution_unit is None:
                x_ax_label = x_ax_label + ' (' + resolution_unit + ')'
                y_ax_label = y_ax_label + ' (' + resolution_unit + ')'
            ax.set_xlabel(x_ax_label, fontsize = 16)
            ax.set_ylabel(y_ax_label, fontsize = 16)

            # Setting the colorbar and colormap
            cbaxticks = np.linspace(*colorbar_lims, 5)
            if cbaxticks[-1] <= 0.1:
                str_format = '{:.3f}'
            elif cbaxticks[-1] >= 100:
                str_format = '{:.1f}'
            else:
                str_format = '{:.2f}'
            cb_ticks_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in cbaxticks]
            cbaxes = fig.add_axes([0.88, 0.125, 0.03, 0.67])
            cb = ax.figure.colorbar(tp_plot, ax = ax, cax = cbaxes, ticks = cbaxticks)
            cb.ax.tick_params(labelsize = 16)
            cb.set_ticks(cbaxticks)
            cb.set_ticklabels(cb_ticks_labels)

            # Setting the colorbar title
            if ls_ind is None:
                title_text = 'f$_{{\mathbf{r}}}$'
            else:
                title_text = 'f$_{{\mathbf{r}}}^{' + '{0}{1}'.format(*ls_ind) + '}$'
            cb.ax.set_title(title_text, fontsize = 18, pad = fig_height * 3)
            ax.figure.canvas.draw()

            # Removing the axes ticks and labels for thumbnail images
            if thumbnail:
                ax.axis('off')
                cb.remove()

            if not imageloc is None:  # Save the file to the location
                plt.savefig(imageloc + '.png', dpi = 150, facecolor = 'w', edgecolor = 'k', orientation = 'portrait', \
                            transparent=False, bbox_inches='tight', pad_inches = 0)

            # Returns the fig object as output (used for platform purposes)
            if return_fig:
                return fig


        elif interactive:  # Interactive plotly plot

            # Generate plotly figure if None is entered for fig parameter
            if fig is None:
                fig = go.Figure()

            # Writing the statistics title (e.g. f11, f10) based on ls_ind parameter
            if ls_ind is None:
                title_text = 'f'
            else:
                title_text = 'f<sup>{}</sup>'.format(str(ls_ind[0]) + str(ls_ind[1]))

            # Plotting the heatmap
            plotdata = go.Heatmap(z = np.flipud(TP), x = np.linspace(-cutoff, cutoff, TP.shape[0]), \
                                  y = np.linspace(-cutoff, cutoff, TP.shape[0]), colorscale = 'Jet', \
                                  colorbar = dict(title = title_text, titleside = "top", thicknessmode = 'fraction', \
                                                  thickness = 0.05, lenmode = 'fraction', len = 1, yanchor = 'top', \
                                                  y = 1, titlefont = dict(size = 16), tickfont = dict(size = 14), \
                                                  tickvals = np.linspace(colorbar_lims[0],colorbar_lims[1],5), \
                                                  ticktext = np.linspace(colorbar_lims[0],colorbar_lims[1],5).round(2)))
            fig.add_trace(plotdata)

            # Setting the axes labels
            xtickname = 'r<sub>x</sub>'; ytickname = 'r<sub>y</sub>'
            if not resolution_unit is None:
                xtickname = xtickname + ' (' + resolution_unit + ')'
                ytickname = ytickname + ' (' + resolution_unit + ')'

            # Setting the appropriate axes tick labels
            ax_ticks = np.linspace(-cutoff, cutoff, 5)
            if ax_ticks[-1] <= 1:
                str_format = '{:.3f}'
            elif ax_ticks[-1] >= 100:
                str_format = '{:.1f}'
            else:
                str_format = '{:.2f}'
            ax_ticks_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in ax_ticks]

            layout = go.Layout(xaxis = dict(tickmode = 'array', tickvals = ax_ticks, ticktext = ax_ticks_labels, title = xtickname, \
                                            titlefont = dict(size = 16), tickfont = dict(size = 14)), \
                               yaxis = dict(tickmode = 'array', tickvals = ax_ticks, ticktext = ax_ticks_labels, title = ytickname, \
                                            titlefont = dict(size = 16), tickfont = dict(size = 14)), \
                               showlegend = False, margin_autoexpand = True, autosize = True, margin = dict(t = 35, b = 10, r = 15), \
                               plot_bgcolor='rgba(0,0,0,0)')

            # Changing the color limits to custom range. Used for comparison of two-point statistics in the same color limits
            if not colorbar_lims is None:
                fig.data[0].update(zmin = colorbar_lims[0], zmax = colorbar_lims[1])

            fig.update_layout(layout)

            # Prevents the pop up of html page if return_fig is set to True.
            config = {'responsive': True, 'displayModeBar': True, 'displaylogo': False, \
                      'modeBarButtonsToRemove':['lasso2d', 'autoScale2d','toggleSpikelines']}

            if not return_fig:
                fig.show(config = config)


    elif TP.ndim == 3:  # 3-D case

        if not interactive:
            warnings.warn(
                """
                Noninteractive plot of two-point statistics of 3-D microstructures has not been implemented \
                yet due to rendering issues in matplotlib packages.
                """
                )

        elif interactive:

            # Generate plotly figure if None is entered for fig parameter
            if fig is None:
                fig = go.Figure()

            TP = TP.transpose((1,0,2))[...,::-1]  # Transposing x and z for plotly

            x_range = np.linspace(-cutoff, cutoff, TP.shape[0])
            y_range = np.linspace(-cutoff, cutoff, TP.shape[1])
            z_range = np.linspace(-cutoff, cutoff, TP.shape[2])

            # Function to extract the slice
            def _get_the_slice(x, y, z, surfacecolor, title_text, colorbar_lims, colorscale = 'jet', showscale = False):
                surfacecolor = surfacecolor[::-1,::-1]
                colorbar = dict(title = title_text, thickness = 20, ticklen = 4, titlefont = dict(size = 14), \
                                tickfont = dict(size = 16), tickvals = np.linspace(colorbar_lims[0],colorbar_lims[1],5), \
                                ticktext = np.linspace(colorbar_lims[0],colorbar_lims[1],5).round(2))
                return go.Surface(x = y, y = x, z = z, surfacecolor = surfacecolor, colorscale = colorscale, \
                                  showscale = showscale, colorbar = colorbar)

            # Writing the statistics title (e.g. f11, f10) based on ls_ind parameter
            if ls_ind is None:
                title_text = 'f'
            else:
                title_text = 'f<sup>{}</sup>'.format(str(ls_ind[0]) + str(ls_ind[1]))

            # Slice x plane
            y, z = np.meshgrid(y_range, z_range, indexing = 'ij')
            x = np.zeros((TP.shape[1],TP.shape[2]))
            surf_data = TP[TP.shape[0] // 2,:,:]
            slice_x = _get_the_slice(x, y, z, surf_data, title_text, colorbar_lims)

            # Slice y plane
            x, z = np.meshgrid(x_range, z_range, indexing = 'ij')
            y = np.zeros((TP.shape[0],TP.shape[2]))
            surf_data = TP[:, TP.shape[1] // 2,:]
            slice_y = _get_the_slice(x, y, z, surf_data, title_text, colorbar_lims)

            # Slice z plane
            x, y = np.meshgrid(x_range, y_range, indexing = 'ij')
            z = np.zeros((TP.shape[0],TP.shape[1]))
            surf_data = TP[:,:,TP.shape[2] // 2]
            slice_z = _get_the_slice(x, y, z, surf_data, title_text, colorbar_lims)

            # Setting the appropriate axes tick labels
            axlims = [-cutoff, cutoff]
            ax_ticks = np.linspace(*axlims, 5)
            if ax_ticks[-1] <= 0.1:
                str_format = '{:.3f}'
            elif ax_ticks[-1] >= 100:
                str_format = '{:.1f}'
            else:
                str_format = '{:.2f}'
            ax_ticks_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in ax_ticks]

            # Setting axes labels
            xtickname = 'r<sub>x</sub>'; ytickname = 'r<sub>y</sub>'; ztickname = 'r<sub>z</sub>'
            if not resolution_unit is None:
                xtickname = xtickname + ' (' + resolution_unit + ')'
                ytickname = ytickname + ' (' + resolution_unit + ')'
                ztickname = ztickname + ' (' + resolution_unit + ')'

            # Figure colors (i.e. background, grid, zero lines)
            axis = dict(showbackground = True, backgroundcolor = "rgb(255, 255, 255)", \
                        gridcolor = "rgb(0, 0, 0)", zerolinecolor = "rgb(0, 0, 0)")

            layout = go.Layout(scene = dict(xaxis = dict(axis, tickmode = 'array', title = xtickname, range = axlims, \
                                                         tickvals = ax_ticks, ticktext = ax_ticks_labels, \
                                                         titlefont = dict(size = 16), tickfont = dict(size = 14)), \
                                            yaxis = dict(axis, tickmode = 'array', title = ytickname, range = axlims, \
                                                         tickvals = ax_ticks, ticktext = ax_ticks_labels, \
                                                         titlefont = dict(size = 16), tickfont = dict(size = 14)), \
                                            zaxis = dict(axis, tickmode = 'array', title = ztickname, range = axlims, \
                                                         tickvals = ax_ticks, ticktext = ax_ticks_labels, \
                                                         titlefont = dict(size = 16), tickfont = dict(size = 14))), \
                               margin_autoexpand = True, autosize = True, margin = dict(t = 35, b = 10, r = 15), \
                               scene_camera = dict(eye = dict(x = 1.35, y = 1.35, z = 1.35), \
                                                   center = dict(x = 0.1, y = 0, z = -0.1)))

            slice_x.update(cmin = colorbar_lims[0], cmax = colorbar_lims[1])
            slice_y.update(cmin = colorbar_lims[0], cmax = colorbar_lims[1])
            slice_z.update(cmin = colorbar_lims[0], cmax = colorbar_lims[1], showscale = True)
            fig = go.Figure(data = [slice_x, slice_y, slice_z], layout = layout)

            # Prevents the pop up of html page if return_fig is set to True.
            config = {'responsive': True, 'displayModeBar': True, 'displaylogo': False, \
                      'modeBarButtonsToRemove':['lasso2d', 'autoScale2d','toggleSpikelines']}

            if not return_fig:
                fig.show(config = config)

# Cell
def Visualize_Pair_Correlation(PC, ax = None, resolution = 1, resolution_unit = None, thumbnail = False, \
                               imageloc = None, ls_ind = None, fig = None, fig_height = 5, y_lims = None, \
                               interactive = False, dpi = 80, return_fig = False):

    # Setting the cutoff variable in pixels/voxels from pair-correlation array (assuming the array have the
    # same dimensions in all directions)
    cutoff_cell = PC.shape[0] - 1

    # Setting up ranges of axes ticks based on resolution information
    cutoff = cutoff_cell * resolution

    # Limits of y axis and tick labels
    if y_lims is None:  # Setting y_lims manually with y_lims parameter. Used for comparison screen
        y_min = np.min(PC) - 0.05 * np.ptp(PC)
        if y_min < 0:
            y_min = 0
        y_lims = [y_min, np.max(PC) + 0.05 * np.ptp(PC)]
    axticks_y = np.linspace(*y_lims,5)

    # Axes ranges and ticks
    x_lims = [0, cutoff] # x_lims
    if y_lims is None:  # Setting y_lims manually with y_lims parameter. Used for comparison screen
        y_min = np.min(PC) - 0.05 * np.ptp(PC)
        if y_min < 0:
            y_min = 0
        y_lims = [y_min, np.max(PC) + 0.05 * np.ptp(PC)]
    axticks_x = np.linspace(*x_lims, 5) # x axis ticks
    axticks_y = np.linspace(*y_lims, 5) # y axis ticks

    # Format of axis ticks
    if axticks_x[-1] <= 0.1:
        str_format = '{:.3f}'
    elif axticks_x[-1] >= 100:
        str_format = '{:.1f}'
    else:
        str_format = '{:.2f}'
    ax_xticks_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in axticks_x]
    if axticks_y[-1] <= 0.1:
        str_format = '{:.3f}'
    elif axticks_y[-1] >= 100:
        str_format = '{:.1f}'
    else:
        str_format = '{:.2f}'
    ax_yticks_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in axticks_y]

    # Interactive plotly plot
    if interactive:

        # Generate plotly figure if not specified (i.e. fig = None)
        if fig is None:
            fig = go.Figure()

        # Adding the pair-correlation function to the plot
        data = go.Scatter(x = np.linspace(0, cutoff, PC.shape[0]), y = PC, mode = 'lines', \
                          line = dict(width = 1.5, color = 'rgb(29,150,157)'), \
                          hovertemplate = '%{x:.3f} , %{y:.3f}<extra></extra>', showlegend = False)
        fig.add_trace(data)

        # Writing the statistics title (e.g. f11, f10) based on ls_ind parameter
        if ls_ind is None:
            y_ax_label = 'P'
        else:
            y_ax_label = 'P<sup>{}</sup>'.format(str(ls_ind[0]) + str(ls_ind[1]))
        x_ax_label = '<b>|r|</b>'
        if not resolution_unit is None:
            x_ax_label = x_ax_label + ' (' + resolution_unit + ')'

        # Setting up layout of the plot
        layout = go.Layout(xaxis = go.layout.XAxis(tickmode = 'array', tickvals = axticks_x, range = x_lims, showgrid = True, \
                                                   title_text = x_ax_label, titlefont = dict(size = 16), \
                                                   tickfont = dict(size = 14), ticktext = ax_xticks_labels, \
                                                   title_standoff = 10), \
                           yaxis = go.layout.YAxis(tickmode = 'array', tickvals = axticks_y, range = y_lims, showgrid = True, \
                                                   title_text = y_ax_label, titlefont = dict(size = 16), \
                                                   tickfont = dict(size = 14), ticktext = ax_yticks_labels, \
                                                   title_standoff = 10), \
                           margin_autoexpand = True, autosize = True, margin = dict(t = 35, b = 10, r = 15))

        fig.update_layout(layout)

        # Prevents the pop up of html page if return_fig is set to True.
        config = {'responsive': True, 'displayModeBar': True, 'displaylogo': False, \
                  'modeBarButtonsToRemove':['lasso2d', 'autoScale2d','toggleSpikelines']}

        if not return_fig:
            fig.show(config = config)

    elif not interactive:

        # Creating a new set of axes if ax is not defined (i.e. ax = None)
        if ax is None:
            fig = plt.figure(figsize = (fig_height * 1.25, fig_height))
            ax = fig.gca()

        # Adding gridlines
        ax.grid(linestyle = '--', linewidth = 0.5)   # Showing the grid lines

        # Plotting the coarsened PCF
        ax.plot(np.linspace(0, cutoff, PC.shape[0]), PC, '-', linewidth = 1.5, color = np.array([29,150,157])/255)

        # Setting the axes labels and the range of x values based on resolution information
        x_ax_label = '$|\mathbf{r}|$'
        if not resolution_unit is None:
            x_ax_label = x_ax_label + ' (' + resolution_unit + ')'
        if ls_ind is None:
            y_ax_label = '$P_{{|\mathbf{r}|}}$'
        else:
            y_ax_label = '$P_{{|\mathbf{r}|}}^{' + '{0}{1}'.format(*ls_ind) + '}$'
        ax.set_xlabel(x_ax_label, fontsize = 18)
        ax.set_ylabel(y_ax_label, fontsize = 18)

        # Setting axes limits and ticks based on resolution information
        axticks_x = np.linspace(0, cutoff, 5)
        ax.set_xlim(x_lims)
        if y_lims is None:  # Setting y_lims manually with y_lims parameter. Used for comparison screen
            y_min = np.min(PC) - 0.05 * np.ptp(PC)
            if y_min < 0:
                y_min = 0
            y_lims = [y_min, np.max(PC) + 0.05 * np.ptp(PC)]
        axticks_y = np.linspace(*y_lims,5)
        ax.set_ylim(y_lims)

        # Setting the ticks and tick label fontsize
        ax.set_xticks(axticks_x)
        ax.set_yticks(axticks_y)
        ax.set_xticklabels(ax_xticks_labels)
        ax.set_yticklabels(ax_yticks_labels)
        ax.tick_params(axis='both', which = 'major', labelsize = 14)

        # Removing the axes ticks and labels for thumbnail images
        if thumbnail:
            ax.axes.get_xaxis().set_visible(False)
            ax.axes.get_yaxis().set_visible(False)

        # Saving the visualization to an image file if a location is specified
        if not imageloc is None:  # Save the file to the location
            plt.savefig(imageloc + '.png', dpi = 150, facecolor = 'w', edgecolor = 'w',
                orientation = 'portrait', transparent = False, bbox_inches = 'tight', pad_inches = 0)

        # Returns the fig object as output (used for platform purposes)
        if return_fig:
            return fig

# Cell
def Visualize_Rotationally_Invariant_Statistics(RI, ang_int, ax = None, resolution = 1, resolution_unit = None, \
                                                thumbnail = False, imageloc = None, ls_ind = None, colorbar_lims = None, \
                                                interactive = False, fig_height = 5, fig = None, return_fig = False, \
                                                dpi = 80):

    # Setting the cutoff variable in pixels/voxels from rotationally invariant statistics array (assuming the
    # array have the same dimensions in all directions)
    cutoff_cell = RI.shape[0] - 1

    # Setting up ranges of axes ticks based on resolution information
    cutoff = cutoff_cell * resolution

    # Colorbar limits
    if colorbar_lims is None:
        colorbar_lims = [np.min(RI), np.max(RI)]

    if RI.shape.__len__() == 2:

        if interactive:
            print('Rotationally invariant two-point statistics cannot be plotted in interactive mode due to'\
                  'lack of contour plot capabilities on polar coordinates.')
            pass

        elif not interactive:

            # Creating a new set of axes if ax is not defined (i.e. ax = None)
            if ax is None:
                fig = plt.figure(figsize = (fig_height * 1.25, fig_height))
                ax = fig.add_subplot(111, polar = True)
            else:
                fig = ax.get_figure()

            ax.set_rmax(cutoff_cell * resolution)
            ax.set_rticks([cutoff])
            ax.tick_params(axis='both', which = 'major', labelsize = 14, pad=8)
            theta_p = np.arange(-180, 180, step = ang_int) * pi/180
            theta_p = np.pad(theta_p, (0,1), mode = 'constant', constant_values = pi)
            r_p = np.arange(RI.shape[0] * resolution, step = resolution)
            theta_p, r_p = np.meshgrid(theta_p,r_p)
            RI = np.pad(RI,((0,0),(0,1)),'wrap')

            # Setting up the color limits
            if not colorbar_lims is None:
                levels = np.linspace(colorbar_lims[0], colorbar_lims[1], 30)
            else:
                levels = 30
            ri_plot = ax.contourf(theta_p, r_p, RI, levels, cmap = 'jet')
            ax.tick_params(axis = 'both', which = 'major', labelsize = 16, pad = 8)

            # Setting the grids and their labels
            ax.set_thetagrids(np.arange(0,360,45), fontsize = 16)
            ax.yaxis.get_gridlines()[0].set_color("w")
            rtick = cutoff
            if rtick <= 0.1:
                str_format = '{:.3f}'
            elif rtick >= 100:
                str_format = '{:.1f}'
            else:
                str_format = '{:.2f}'
            rtick_labels = ['', str_format.format(rtick).rstrip('0').rstrip('.')]
            rtick_labels[-1] = '$|\mathbf{r}|$ = ' + rtick_labels[-1]
            if not resolution_unit is None:
                rtick_labels[-1] = rtick_labels[-1] + ' ' + resolution_unit
            ax.set_rgrids([cutoff / 2, cutoff], labels = rtick_labels)
            rgrid_lines = ax.yaxis.get_gridlines()
            thetagrid_lines = ax.xaxis.get_gridlines()
            rgrid_lines[0].set_color('w')
            rgrid_lines[0].set_linestyle('--')
            [i.set_linestyle("--") for i in thetagrid_lines]
            [i.set_color('w') for i in thetagrid_lines]
            ax.set_rlabel_position(75)

            # Setting the colorbar and colormap
            cbaxticks = np.linspace(*colorbar_lims, 5)
            if cbaxticks[-1] <= 0.1:
                str_format = '{:.3f}'
            elif cbaxticks[-1] >= 100:
                str_format = '{:.1f}'
            else:
                str_format = '{:.2f}'
            cb_ticks_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in cbaxticks]
            cbax = fig.add_axes([0.93, 0.1, 0.03, 0.7])
            cb = ax.figure.colorbar(ri_plot, ax = ax, cax = cbax, pad = 0.05, ticks = cbaxticks)
            cb.ax.tick_params(labelsize = 16)
            cb.set_ticks(cbaxticks)
            cb.set_ticklabels(cb_ticks_labels)

            # Setting the title on top of colorbar
            if ls_ind is None:
                title_text = '$\\tilde{f}$$_{{|\mathbf{r}|,\\psi}}$'
            else:
                title_text = '$\\tilde{f}$$_{|\mathbf{r}|,\psi}^{\ ' + '{0}{1}'.format(*ls_ind) + '}$'
            cb.ax.set_title(title_text, fontsize = 20, pad = fig_height * 4)
            ax.figure.canvas.draw()

            # Removing the axes ticks and labels for thumbnail images
            if thumbnail:
                ax.axis('off')
                plt_title.set_visible(False)
                cb.remove()

            # Saving plot to a png format image file
            if not imageloc is None:  # Save the file to the location
                plt.savefig(imageloc + '.png', dpi = 150, facecolor = 'w', edgecolor = 'k', \
                            orientation = 'portrait', transparent = False, bbox_inches = 'tight', \
                            pad_inches = 0)

            # Returns the fig object as output (used for platform purposes)
            if return_fig:
                return fig

# Cell
def Visualize_ARCLD(ARCLD, ang_int, local_state, ax = None, fig = None, coarsening = 1, resolution = 1, \
                   resolution_unit = None, thumbnail = False, imageloc = None, colorbar_lims = None, \
                   fig_height = 5, interactive = False, return_fig = False):

    # Extracting the ARCLD associated with the selected local state
    ARCLD = ARCLD[local_state]

    # Colorbar limits
    if colorbar_lims is None:
        colorbar_lims = [np.min(ARCLD), np.max(ARCLD)]

    # Cutoff in cells after coarsening factor is accounted for
    cutoff_cell = ARCLD.shape[0] * coarsening

    # Setting up cutoff value based on resolution value
    cutoff = cutoff_cell * resolution

    # Interactive case
    if interactive:
        print('Angularly resolved chord length distribution cannot be plotted in interactive mode due to'\
              'lack of contour plot capabilities of plotly on polar coordinates.')
        pass

    # Noninteractive case
    elif not interactive:

        # Creating a new set of axes if ax is not defined (i.e. ax = None)
        if ax is None:
            fig = plt.figure(figsize = (fig_height * 1.25, fig_height))
            ax = fig.add_subplot(111, polar = True)
        else:
            fig = ax.get_figure()

        # Concatenating ARCLD with angles from 180 to 360 to have full circle
        ARCLD = np.concatenate((ARCLD, ARCLD[:, 0, None], ARCLD[:,1:], ARCLD[:, 0, None]), axis = 1)

        # Setting up the list of angles and chord lengths
        ax.tick_params(axis = 'both', which = 'major', labelsize = 14, pad = 8)
        theta = np.arange(0, 180, step = ang_int)
        theta = np.concatenate((theta, [180], 180 + theta[1:], [360]))
        theta = np.repeat(theta[None,:], ARCLD.shape[0], axis = 0)

        # Radius array for polar plot
        rmin = resolution * (1 + (coarsening - 1)/2)
        rmax = cutoff - resolution * (coarsening - 1)/2
        r = np.linspace(rmin, rmax, theta.shape[0])
        r = np.repeat(r[:,None], theta.shape[1], axis = 1)

        if ang_int > 15:

            # Interpolation on the regular polar coordinates based on cartesian points
            theta_interp = np.arange(0, 361, step = 15)
            theta0 = theta
            theta, r = np.meshgrid(theta_interp, np.arange(1, ARCLD.shape[0] + 1))
            r = np.repeat(np.arange(1, ARCLD.shape[0] + 1)[:,None], theta.shape[1], axis = 1)
            r0 = np.repeat(np.arange(1, ARCLD.shape[0] + 1)[:,None], theta0.shape[1], axis = 1)
            polar_coord_list = np.concatenate((theta0.flatten()[:,None], \
                                               r0.flatten()[:,None]), axis = 1)
            ARCLD = griddata(polar_coord_list, ARCLD.flatten()[:,None], (theta, r), \
                                method = 'linear').reshape(theta.shape)

        # Setting up the color limits
        if colorbar_lims is not None:
            levels = np.linspace(colorbar_lims[0], colorbar_lims[1], 30)
        else:
            levels = 30
        arcld_plot = ax.contourf(theta * pi / 180, r, ARCLD, levels, cmap = 'jet')
        ax.set_rmin(resolution * (1 + (coarsening - 1)/2))

        # Setting the grids and their labels
        ax.set_rmax(rmax)
        ax.set_thetagrids(np.arange(0,360,45), fontsize = 16)
        ax.yaxis.get_gridlines()[0].set_color("w")
        rtick = rmax
        if rtick <= 0.1:
            str_format = '{:.3f}'
        elif rtick >= 100:
            str_format = '{:.1f}'
        else:
            str_format = '{:.2f}'
        rtick_labels = ['', str_format.format(rtick).rstrip('0').rstrip('.')]
        rtick_labels[-1] = '$z$ = ' + rtick_labels[-1]
        if not resolution_unit is None:
            rtick_labels[-1] = rtick_labels[-1] + ' ' + resolution_unit
        ax.set_rgrids([(rmax - rmin) / 2, rmax], labels = rtick_labels)
        rgrid_lines = ax.yaxis.get_gridlines()
        thetagrid_lines = ax.xaxis.get_gridlines()
        rgrid_lines[0].set_color('w')
        rgrid_lines[0].set_linestyle('--')
        [i.set_linestyle("--") for i in thetagrid_lines]
        [i.set_color('w') for i in thetagrid_lines]
        ax.set_rlabel_position(75)

        # Setting the colorbar and colormap
        cbaxticks = np.linspace(*colorbar_lims, 5)
        if cbaxticks[-1] <= 0.1:
            str_format = '{:.4f}'
        elif cbaxticks[-1] >= 100:
            str_format = '{:.2f}'
        else:
            str_format = '{:.3f}'
        cb_ticks_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in cbaxticks]
        cbax = fig.add_axes([0.93, 0.08, 0.03, 0.75])
        cb = ax.figure.colorbar(arcld_plot, ax = ax, cax = cbax, pad = 0.05, ticks = cbaxticks)
        cb.ax.tick_params(labelsize = 16)
        cb.set_ticks(cbaxticks)
        cb.set_ticklabels(cb_ticks_labels)

        # Setting the title on top of colorbar
        title_text = '$C_z^{ ' + '{}'.format(local_state) + '}$'
        cb.ax.set_title(title_text, fontsize = 20, pad = fig_height * 4)
        ax.figure.canvas.draw()

        # Removing the axes ticks and labels for thumbnail images
        if thumbnail:
            ax.axis('off')
            plt_title.set_visible(False)
            cb.remove()

        # Saving plot to a png format image file
        if not imageloc is None:  # Save the file to the location
            plt.savefig(imageloc + '.png', dpi = 150, facecolor = 'w', edgecolor = 'k', \
                        orientation = 'portrait', transparent = False, bbox_inches = 'tight', \
                        pad_inches = 0)

        # Returns the fig object as output (used for platform purposes)
        if return_fig:
            return fig

# Cell
def Visualize_ARCLD_Angle(ARCLD, ang_int, local_state, angles, ax = None, coarsening = 1, resolution = 1, \
                          resolution_unit = None, thumbnail = False, imageloc = None, fig = None, \
                          interactive = False, dpi = 80, y_lims = None, fig_height = 5, return_fig = False):

    # Extracting the ARCLD associated with the selected local state
    ARCLD = ARCLD[local_state]

    # Extracting the corresponding angles
    theta = np.arange(0, 180, step = ang_int)
    if not all(item in theta for item in angles):
        raise ValueError('CLDs corresponding to the entries of angles parameter do not exist in the ARCLD.')
    else:
        angles_ind = [np.argwhere(theta == i)[0][0] for i in angles]
        CLD = ARCLD[..., angles_ind]

    # Setting the cutoff variable in pixels from CLD array
    cutoff_cell_coarse = CLD.shape[0]
    cutoff_cell = cutoff_cell_coarse * coarsening

    # Setting up ranges of axes ticks based on resolution information
    cutoff = cutoff_cell_coarse * resolution * coarsening - resolution * (coarsening - 1) / 2

    # Axes ranges and ticks
    x_lims = [resolution + resolution * (coarsening - 1) / 2, cutoff] # x_lims
    if y_lims is None:  # Setting y_lims manually with y_lims parameter. Used for comparison screen
        y_min = np.min(CLD) - 0.05 * np.ptp(CLD)
        if y_min < 0:
            y_min = 0
    y_lims = [y_min, np.max(CLD) + 0.05 * np.ptp(CLD)]
    axticks_x = np.linspace(*x_lims, 5) # x axis ticks
    axticks_y = np.linspace(*y_lims, 5) # y axis ticks

    # Format of axis ticks
    if axticks_x[-1] <= 0.1:
        str_format = '{:.3f}'
    elif axticks_x[-1] >= 100:
        str_format = '{:.1f}'
    else:
        str_format = '{:.2f}'
    ax_xticks_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in axticks_x]
    if axticks_y[-1] <= 0.1:
        str_format = '{:.4f}'
    elif axticks_y[-1] >= 100:
        str_format = '{:.1f}'
    else:
        str_format = '{:.2f}'
    ax_yticks_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in axticks_y]

    # x axis label
    x_ax_label = 'z'
    if not resolution_unit is None:
        x_ax_label = x_ax_label + ' (' + resolution_unit + ')'

    # Temporary color scheme for platform
    colors = ([255, 0, 0], [0, 185, 0], [0, 0, 255])
    temp_colors = []
    for i in angles_ind:
        temp_colors.append(colors[int(i/3)])

    # Interactive plotly plot
    if interactive:

        # Generate plotly figure if not specified (i.e. fig = None)
        if fig is None:
            fig = go.Figure()

        # Adding the CLD to the plot
        for i in range(CLD.shape[1]):
            data = go.Scatter(x = np.linspace(*x_lims, CLD.shape[0]), y = CLD[..., i], mode = 'lines', \
                              line = dict(width = 1.5, color = 'rgb({}, {}, {})'.format(*temp_colors[i])), \
                              hovertemplate = '%{x:.3f} , %{y:.3f}<extra></extra>', showlegend = True, \
                              name = str(angles[i]) + '°')
            fig.add_trace(data)

        # Writing the statistics title (e.g. C^1, C^0) based on ls_ind parameter
        y_ax_label = 'C<sup>{}</sup>'.format(local_state)

        # Setting up layout of the plot
        layout = go.Layout(xaxis = go.layout.XAxis(tickmode = 'array', tickvals = axticks_x, range = x_lims, showgrid = True, \
                                                   title_text = x_ax_label, titlefont = dict(size = 16), \
                                                   tickfont = dict(size = 14), ticktext = ax_xticks_labels, \
                                                   title_standoff = 10, zeroline = False), \
                           yaxis = go.layout.YAxis(tickmode = 'array', tickvals = axticks_y, range = y_lims, showgrid = True, \
                                                   title_text = y_ax_label, titlefont = dict(size = 16), \
                                                   tickfont = dict(size = 14), ticktext = ax_yticks_labels, \
                                                   title_standoff = 10, zeroline = False), \
                           margin_autoexpand = True, autosize = True, margin = dict(t = 35, b = 10, r = 15), \
                           legend = dict(x = 0.85, y = 0.95, orientation = 'h', font = dict(size = 14)))

        fig.update_layout(layout)

        # Prevents the pop up of html page if return_fig is set to True.
        config = {'responsive': True, 'displayModeBar': True, 'displaylogo': False, \
                  'modeBarButtonsToRemove':['lasso2d', 'autoScale2d','toggleSpikelines']}

        if not return_fig:
            fig.show(config = config)


    # Noninteractive matplotlib plot
    elif not interactive:

        # Creating a new set of axes if ax is not defined (i.e. ax = None)
        if ax is None:
            fig = plt.figure(figsize = (fig_height * 1.25, fig_height))
            ax = fig.gca()

        # Adding gridlines
        ax.grid(linestyle = '--', linewidth = 0.5)   # Showing the grid lines

        # Plotting the coarsened PCF
        legend_line_obj = []
        legend_names = []
        for i in range(CLD.shape[1]):
            ax.plot(np.linspace(*x_lims, CLD.shape[0]), CLD[..., i], '-', linewidth = 1.5, \
                        color = np.asarray(temp_colors[i])/255, label = str(angles[i]) + '°')
        ax.legend(loc = 'upper right', fontsize = 14)

        # Setting the axes labels and the range of x values based on resolution information
        x_ax_label = 'z'
        if not resolution_unit is None:
            x_ax_label = x_ax_label + ' (' + resolution_unit + ')'
        y_ax_label = '$C_z^{ ' + '{}'.format(local_state) + '}$'
        ax.set_xlabel(x_ax_label, fontsize = 16, labelpad = 10)
        ax.set_ylabel(y_ax_label, fontsize = 16)

        # Setting the ticks and tick label fontsize
        ax.set_xticks(axticks_x)
        ax.set_yticks(axticks_y)
        ax.set_xlim(x_lims)
        ax.set_ylim(y_lims)
        ax.set_xticklabels(ax_xticks_labels)
        ax.set_yticklabels(ax_yticks_labels)
        ax.tick_params(axis='both', which = 'major', labelsize = 14)

        # Removing the axes ticks and labels for thumbnail images
        if thumbnail:
            ax.axes.get_xaxis().set_visible(False)
            ax.axes.get_yaxis().set_visible(False)


        # Saving the visualization to an image file if a location is specified
        if not imageloc is None:  # Save the file to the location
            plt.savefig(imageloc + '.png', dpi = 150, facecolor = 'w', edgecolor = 'w',
                orientation = 'portrait', transparent = False, bbox_inches = 'tight', pad_inches = 0)

        # Returns the fig object as output (used for platform purposes)
        if return_fig:
            return fig

# Cell
def Visualize_CLD(CLD, local_state, ax = None, coarsening = 1, resolution = 1, resolution_unit = None, \
                  thumbnail = False, imageloc = None, fig = None, interactive = False, dpi = 80, \
                  y_lims = None, fig_height = 5, return_fig = False):


    # Extracting the ARCLD associated with the selected local state
    CLD = CLD[local_state]

    # Setting the cutoff variable in pixels from CLD array
    cutoff_cell_coarse = CLD.shape[0]
    cutoff_cell = cutoff_cell_coarse * coarsening

    # Setting up ranges of axes ticks based on resolution information
    cutoff = cutoff_cell_coarse * resolution * coarsening - resolution * (coarsening - 1) / 2

    # Axes ranges and ticks
    x_lims = [resolution + resolution * (coarsening - 1) / 2, cutoff] # x_lims
    if y_lims is None:  # Setting y_lims manually with y_lims parameter. Used for comparison screen
        y_min = np.min(CLD) - 0.05 * np.ptp(CLD)
        if y_min < 0:
            y_min = 0
        y_lims = [y_min, np.max(CLD) + 0.05 * np.ptp(CLD)]
    axticks_x = np.linspace(*x_lims, 5) # x axis ticks
    axticks_y = np.linspace(*y_lims, 5) # y axis ticks

    # Format of axis ticks
    if axticks_x[-1] <= 0.1:
        str_format = '{:.3f}'
    elif axticks_x[-1] >= 100:
        str_format = '{:.1f}'
    else:
        str_format = '{:.2f}'
    ax_xticks_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in axticks_x]
    if axticks_y[-1] <= 0.1:
        str_format = '{:.4f}'
    elif axticks_y[-1] >= 100:
        str_format = '{:.1f}'
    else:
        str_format = '{:.2f}'
    ax_yticks_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in axticks_y]

    # x axis label
    x_ax_label = 'z'
    if not resolution_unit is None:
        x_ax_label = x_ax_label + ' (' + resolution_unit + ')'

    # Interactive plotly plot
    if interactive:

        # Generate plotly figure if not specified (i.e. fig = None)
        if fig is None:
            fig = go.Figure()

        # Adding the CLD to the plot
        data = go.Scatter(x = np.linspace(*x_lims, CLD.shape[0]), y = CLD, mode = 'lines', \
                          line = dict(width = 1.5, color = 'rgb(29,150,157)'), \
                          hovertemplate = '%{x:.3f} , %{y:.3f}<extra></extra>', showlegend = False)
        fig.add_trace(data)

        # Writing the statistics title (e.g. C^1, C^0) based on ls_ind parameter
        y_ax_label = 'C<sup>{}</sup>'.format(local_state)

        # Setting up layout of the plot
        layout = go.Layout(xaxis = go.layout.XAxis(tickmode = 'array', tickvals = axticks_x, range = x_lims, showgrid = True, \
                                                   title_text = x_ax_label, titlefont = dict(size = 16), \
                                                   tickfont = dict(size = 14), ticktext = ax_xticks_labels, \
                                                   title_standoff = 10, zeroline = False), \
                           yaxis = go.layout.YAxis(tickmode = 'array', tickvals = axticks_y, range = y_lims, showgrid = True, \
                                                   title_text = y_ax_label, titlefont = dict(size = 16), \
                                                   tickfont = dict(size = 14), ticktext = ax_yticks_labels, \
                                                   title_standoff = 10, zeroline = False), \
                           margin_autoexpand = True, autosize = True, margin = dict(t = 35, b = 10, r = 15))

        fig.update_layout(layout)

        # Prevents the pop up of html page if return_fig is set to True.
        config = {'responsive': True, 'displayModeBar': True, 'displaylogo': False, \
                  'modeBarButtonsToRemove':['lasso2d', 'autoScale2d','toggleSpikelines']}

        if not return_fig:
            fig.show(config = config)


    # Noninteractive matplotlib plot
    elif not interactive:

        # Creating a new set of axes if ax is not defined (i.e. ax = None)
        if ax is None:
            fig = plt.figure(figsize = (fig_height * 1.25, fig_height))
            ax = fig.gca()

        # Adding gridlines
        ax.grid(linestyle = '--', linewidth = 0.5)   # Showing the grid lines

        # Plotting the coarsened PCF
        ax.plot(np.linspace(*x_lims, CLD.shape[0]), CLD, '-', linewidth = 1.5, color = np.array([29,150,157])/255)

        # Setting the axes labels and the range of x values based on resolution information
        x_ax_label = 'z'
        if not resolution_unit is None:
            x_ax_label = x_ax_label + ' (' + resolution_unit + ')'
        y_ax_label = '$C_z^{ ' + '{}'.format(local_state) + '}$'
        ax.set_xlabel(x_ax_label, fontsize = 18, labelpad = 10)
        ax.set_ylabel(y_ax_label, fontsize = 18)

        # Setting the ticks and tick label fontsize
        ax.set_xticks(axticks_x)
        ax.set_yticks(axticks_y)
        ax.set_xlim(x_lims)
        ax.set_ylim(y_lims)
        ax.set_xticklabels(ax_xticks_labels)
        ax.set_yticklabels(ax_yticks_labels)
        ax.tick_params(axis='both', which = 'major', labelsize = 14)

        # Removing the axes ticks and labels for thumbnail images
        if thumbnail:
            ax.axes.get_xaxis().set_visible(False)
            ax.axes.get_yaxis().set_visible(False)

        # Saving the visualization to an image file if a location is specified
        if not imageloc is None:  # Save the file to the location
            plt.savefig(imageloc + '.png', dpi = 150, facecolor = 'w', edgecolor = 'w',
                orientation = 'portrait', transparent = False, bbox_inches = 'tight', pad_inches = 0)

        # Returns the fig object as output (used for platform purposes)
        if return_fig:
            return fig

# Cell
def Visualize_PC_Scores(W, indices, feature = None, feature_name = None, feature_unit = None, \
                        fig = None, fig_height = 5, dpi = 80, return_fig = False, ax = None):

    # Check for type of input for parameter name and unit
    if not type(feature_name) in (str, type(None)):
        raise ValueError('Feature name must be str type.')
    if not type(feature_unit) in (str, type(None)):
        raise ValueError('Feature unit must be str type.')

    # Axis limits and ticks
    x_range = np.ptp(W[:,indices[0]])
    y_range = np.ptp(W[:,indices[1]])
    x_lims = [np.min(W[:,indices[0]]) - 0.05 * x_range, np.max(W[:,indices[0]]) + 0.05 * x_range]
    y_lims = [np.min(W[:,indices[1]]) - 0.05 * y_range, np.max(W[:,indices[1]]) + 0.05 * y_range]
    axticks_x = np.linspace(*x_lims, 5)
    axticks_y = np.linspace(*y_lims, 5)
    x_ax_label = 'PC{}'.format(indices[0] + 1)
    y_ax_label = 'PC{}'.format(indices[1] + 1)
    if axticks_x[-1] <= 0.1:
        str_format = '{:.3f}'
    elif axticks_x[-1] >= 100:
        str_format = '{:.1f}'
    else:
        str_format = '{:.2f}'
    ax_xticks_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in axticks_x]
    if axticks_y[-1] <= 0.1:
        str_format = '{:.3f}'
    elif axticks_y[-1] >= 100:
        str_format = '{:.1f}'
    else:
        str_format = '{:.2f}'
    ax_yticks_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in axticks_y]

    # Hovertext format
    hovertextformat = 'PC{}: '.format(indices[0] + 1) + '%{x:.3f}' + \
                      '<br>PC{}: '.format(indices[1] + 1) + '%{y:.3f}' + '<extra></extra>'
    if indices.__len__() ==3:
        hovertextformat = hovertextformat + '<br>PC{}: '.format(indices[2] + 1) + '%{z:.3f}'
    hovertextfeature = ''
    if feature is None:
        marker_color = 'rgb(29,150,157)'
        colorbar_params = None
    elif feature.shape[0] != W.shape[0]:
        raise ValueError('Feature must be a list with the same number of entries as the number of data'\
                         'points (i.e. W.shape[0])')
    else:
        marker_color = feature
        feature_lims = [np.min(feature), np.max(feature)]
        colorbar_params = dict(title = feature_name + '<br>' + '(' + feature_unit + ')<br> <br>', \
                               titleside = "top", thicknessmode = 'fraction', thickness = 0.05, \
                               lenmode = 'fraction', len = 1, yanchor = 'top', y = 1, \
                               titlefont = dict(size = 16), tickfont = dict(size = 14), \
                               ticktext = np.linspace(*feature_lims, 5).round(2), \
                               tickvals = np.linspace(*feature_lims, 5).round(2))
        if np.min(feature) < 0.1:
            customdataformat = '3f}'
        elif np.min(feature) > 100:
            customdataformat = '1f}'
        else:
            customdataformat = '2f}'
        if not feature_name is None:
            hovertextfeature = '<br>' + feature_name + ': %{customdata:.' + customdataformat
            if not feature_unit is None:
                hovertextfeature = hovertextfeature + ' {}'.format(feature_unit)

        # Setting the colorbar and colormap
        cbaxticks = np.linspace(*feature_lims, 5)
        if cbaxticks[-1] <= 0.1:
            str_format = '{:.4f}'
        elif cbaxticks[-1] >= 100:
            str_format = '{:.2f}'
        else:
            str_format = '{:.3f}'
        cb_ticks_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in cbaxticks]

    # Generating a figure if not specified
    if fig is None:
        fig = go.Figure()

    # 2-D PC plots
    if indices.__len__() == 2:

        data = go.Scatter(x = W[:,indices[0]], y = W[:,indices[1]], customdata = feature, mode = 'markers', \
                          marker = dict(size = 14, colorscale = 'jet', color = marker_color, \
                                        line = dict(width = 1, color = 'black'), colorbar = colorbar_params), \
                          hovertemplate = hovertextformat + hovertextfeature, showlegend = False)

        # Setting up layout of the plot
        layout = go.Layout(xaxis = go.layout.XAxis(tickmode = 'array', tickvals = axticks_x, range = x_lims, showgrid = True, \
                                                   title_text = x_ax_label, titlefont = dict(size = 16), \
                                                   tickfont = dict(size = 14), ticktext = ax_xticks_labels, \
                                                   title_standoff = 10, zeroline = False), \
                           yaxis = go.layout.YAxis(tickmode = 'array', tickvals = axticks_y, range = y_lims, showgrid = True, \
                                                   title_text = y_ax_label, titlefont = dict(size = 16), \
                                                   tickfont = dict(size = 14), ticktext = ax_yticks_labels, \
                                                   title_standoff = 10, zeroline = False), \
                           margin_autoexpand = True, autosize = True, margin = dict(t = 35, b = 10, r = 15))

    elif indices.__len__() == 3:

        # z axis limits and ticks
        z_range = np.ptp(W[:,indices[2]])
        z_lims = [np.min(W[:,indices[2]]) - 0.05 * z_range, np.max(W[:,indices[2]]) + 0.05 * z_range]
        axticks_z = np.linspace(*z_lims, 5)
        z_ax_label = 'PC{}'.format(indices[2] + 1)
        if axticks_z[-1] <= 0.1:
            str_format = '{:.3f}'
        elif axticks_z[-1] >= 100:
            str_format = '{:.1f}'
        else:
            str_format = '{:.2f}'
        ax_zticks_labels = [str_format.format(i).rstrip('0').rstrip('.') for i in axticks_z]

        # Figure colors (i.e. background, grid, zero lines)
        axis = dict(showbackground = True, backgroundcolor = "rgb(255, 255, 255)", \
                    gridcolor = "rgb(0, 0, 0)", zerolinecolor = "rgb(0, 0, 0)")

        data = go.Scatter3d(x = W[:,indices[0]], y = W[:,indices[1]], z = W[:,indices[2]], customdata = feature, \
                            mode = 'markers', \
                            marker = dict(size = 6, colorscale = 'jet', color = marker_color, \
                                          line = dict(width = 1, color = 'black'), \
                                          colorbar = colorbar_params), \
                            hovertemplate = hovertextformat + hovertextfeature, showlegend = False)

        # Setting up layout of the plot
        layout = go.Layout(scene = dict(xaxis = dict(axis, tickmode = 'array', title = x_ax_label, range = x_lims, \
                                                     tickvals = axticks_x, ticktext = ax_xticks_labels, \
                                                     titlefont = dict(size = 16), tickfont = dict(size = 14), \
                                                     zeroline = False), \
                                        yaxis = dict(axis, tickmode = 'array', title = y_ax_label, range = y_lims, \
                                                     tickvals = axticks_y, ticktext = ax_yticks_labels, \
                                                     titlefont = dict(size = 16), tickfont = dict(size = 14), \
                                                     zeroline = False), \
                                        zaxis = dict(axis, tickmode = 'array', title = z_ax_label, range = z_lims, \
                                                     tickvals = axticks_z, ticktext = ax_zticks_labels, \
                                                     titlefont = dict(size = 16), tickfont = dict(size = 14), \
                                                     zeroline = False), \
                                        aspectmode = 'auto'), \
                           margin_autoexpand = True, autosize = True, margin = dict(t = 35, b = 10, r = 15), \
                           scene_camera = dict(eye = dict(x = 1.55, y = 1.55, z = 1.55), \
                                               center = dict(x = 0.1, y = 0, z = -0.1)))

    else:   # Raise error if indices contains entries other than 2 and 3.
        raise ValueError('Indices must be a list of integers of length 2 or 3.')

    # Plotting the figure
    fig.add_trace(data)
    fig.update_layout(layout)
    if feature is None:
        fig.update(layout_coloraxis_showscale = False)

    # Prevents the pop up of html page if return_fig is set to True.
    config = {'responsive': True, 'displayModeBar': True, 'displaylogo': False, \
              'modeBarButtonsToRemove':['lasso2d', 'autoScale2d','toggleSpikelines']}

    if not return_fig:
        fig.show(config = config)


# Cell
def Visualize_Explained_Variance(S, n_components = None, fig = None, ax = None, interactive = True, fig_height = 5, \
                                 dpi = 80, imageloc = None, return_fig = False):

    # Multiplying explained variance values by 100 for visualization purposes
    S = S * 100

    # Adjusting S and n_components according to n_components parameter
    if n_components is None or n_components > S.shape[0]:
        n_components = S.shape[0]
    else:
        S = S[:n_components]

    axticks_x = np.arange(1, n_components + 1)
    axticks_y = np.linspace(0, 100, 6)
    ax_xticks_labels = ['PC ' + str(i) for i in axticks_x]
    axlims_x = [0.5, n_components + 0.5]
    axlims_y = [0, 105]
    line_legend = 'Cumulative variance'
    bar_legend = 'Individual variance'

    # Axes labels
    y_ax_label = 'Explained variance, %'

    # Hovertext format
    hovertextformat_bar = 'Individual variance' + \
                          '<br>%{x} : %{y:.2f} %<extra></extra>'
    hovertextformat_line = 'Cumulative variance up to' + \
                           '<br>%{x} : %{y:.2f} %<extra></extra>'

    if interactive:

        # Generate plotly figure if not specified (i.e. fig = None)
        if fig is None:
            fig = go.Figure()

        # Adding the CLD to the plot
        data_bars = go.Bar(x = axticks_x, y = S, showlegend = False, marker_color = 'rgb(29,150,157)', \
                           hovertemplate = hovertextformat_bar)
        data_line = go.Scatter(x = axticks_x, y = np.cumsum(S), showlegend = False, marker_color = 'black', \
                               hovertemplate = hovertextformat_line, marker = dict(size = 10))
        fig.add_trace(data_bars)
        fig.add_trace(data_line)

        # Setting up layout of the plot
        layout = go.Layout(xaxis = go.layout.XAxis(tickmode = 'array', tickvals = axticks_x, range = axlims_x, showgrid = True, \
                                                   titlefont = dict(size = 16), \
                                                   tickfont = dict(size = 14), ticktext = ax_xticks_labels, \
                                                   title_standoff = 10), \
                           yaxis = go.layout.YAxis(tickmode = 'array', tickvals = axticks_y, range = axlims_y, showgrid = True, \
                                                   title_text = y_ax_label, titlefont = dict(size = 16), \
                                                   tickfont = dict(size = 14), ticktext = axticks_y, \
                                                   title_standoff = 10), \
                           margin_autoexpand = True, autosize = True, margin = dict(t = 35, b = 10, r = 15))

        fig.update_layout(layout)

        # Prevents the pop up of html page if return_fig is set to True.
        config = {'responsive': True, 'displayModeBar': True, 'displaylogo': False, \
                  'modeBarButtonsToRemove':['lasso2d', 'autoScale2d','toggleSpikelines']}

        if not return_fig:
            fig.show(config = config)

    # Noninteractive matplotlib plot
    elif not interactive:

        # Creating a new set of axes if ax is not defined (i.e. ax = None)
        if ax is None:
            fig = plt.figure(figsize = (fig_height * n_components * 0.20, fig_height))
            ax = fig.gca()

        # Adding gridlines
        ax.grid(linestyle = '--', linewidth = 0.5)   # Showing the grid lines

        # Plotting the coarsened PCF
        ax.plot(np.arange(1, n_components + 1), np.cumsum(S), 'o-', linewidth = 1.5, color = 'black')
        ax.bar(np.arange(1, n_components + 1), S, width = 0.7, color = np.array([29,150,157])/255)

        # Setting the axes labels and the range of x values based on resolution information
        ax.set_ylabel(y_ax_label, fontsize = 18)

        # Setting the ticks and tick label fontsize
        ax.set_xticks(axticks_x)
        ax.set_yticks(axticks_y)
        ax.set_xlim(axlims_x)
        ax.set_ylim(axlims_y)
        ax.set_xticklabels(ax_xticks_labels)
        ax.tick_params(axis='both', which = 'major', labelsize = 14)

        # Saving the visualization to an image file if a location is specified
        if not imageloc is None:  # Save the file to the location
            plt.savefig(imageloc + '.png', dpi = 150, facecolor = 'w', edgecolor='w',
                orientation = 'portrait', transparent = False, bbox_inches = 'tight', pad_inches = 0)

        # Returns the fig object as output (used for platform purposes)
        if return_fig:
            return fig